version: '3'

services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "$POSTGRES_PORT:$POSTGRES_PORT"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  euroguessr:
    container_name: euroguessr
    image: euroguessr
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.euroguessr.rule=Host(`www.$DOMAIN_NAME`) || Host(`$DOMAIN_NAME`)"
      - "traefik.http.routers.euroguessr.entrypoints=websecure"
      - "traefik.http.services.euroguessr.loadbalancer.server.port=$EUROGUESSR_PORT"
      - "traefik.http.routers.euroguessr.tls.certresolver=euroguessr"
    expose:
      - $EUROGUESSR_PORT
    ports:
      - "$EUROGUESSR_PORT:$EUROGUESSR_PORT"
    volumes:
      - ./Euroguessr.Data/SongsData.json:/Euroguessr.Data/SongsData.json
    # environment:
      # ASPNETCORE_ENVIRONMENT: Development
volumes:
  postgres-data:
