version: '3'

services:

  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "$POSTGRES_PORT:$POSTGRES_PORT"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  traefik:
    container_name: traefik
    image: traefik:latest
    command:
      - "--api=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.euroguessr.acme.tlschallenge=true"
      - "--certificatesresolvers.euroguessr.acme.email=loangayrard@gmail.com"
      - "--certificatesresolvers.euroguessr.acme.storage=/letsencrypt/acme.json"
    labels:
      - "traefik.http.routers.api.rule=Host (`traefik.$DOMAIN_NAME`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=$TRAEFIK_AUTH_USER"
      - "traefik.http.routers.api.tls.certresolver=euroguessr"
    ports:
      - "$TRAEFIK_PORT1:$TRAEFIK_PORT1"
      - "$TRAEFIK_PORT2:$TRAEFIK_PORT2"
      - "$TRAEFIK_PORT3:$TRAEFIK_PORT3"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - /var/run/docker.sock:/var/run/docker.sock:ro

  backend:
    build:
      context: .
    container_name: euroguessr-backend
    environment:
      - ConnectionStrings__DatabaseConnection=Server=db;Port=$POSTGRES_PORT;Database=$POSTGRES_DB;Username=$POSTGRES_USER;Password=$POSTGRES_PASSWORD;Integrated Security=true;Pooling=true;
    depends_on:
      - db
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.$DOMAIN_NAME`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.services.backend.loadbalancer.server.port=$BACKEND_PORT"
      - "traefik.http.routers.backend.tls.certresolver=euroguessr"

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    expose:
      - PORTAINER_PORT1
      - PORTAINER_PORT2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.$DOMAIN_NAME`)" 
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.services.portainer.loadbalancer.server.port=$PORTAINER_PORT2"
      - "traefik.http.routers.portainer.tls.certresolver=euroguessr"
  
  frontend:
    build:
      context: ./euroguessr-front
    container_name: euroguessr-frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`$DOMAIN_NAME`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.services.frontend.loadbalancer.server.port=$FRONTEND_PORT"
      - "traefik.http.routers.frontend.tls.certresolver=euroguessr"
    depends_on:
      - backend
      - traefik

volumes:
  postgres-data:
  portainer_data:
