version: '3'

services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  euroguessr:
    container_name: euroguessr
    image: euroguessr
    build: ./Euroguessr 
    ports:
      - "80:80"
    # environment:
      # ASPNETCORE_ENVIRONMENT: Development

volumes:
  postgres-data: