using Euroguessr.Data.Tables;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace Euroguessr.Data
{
    public class EntityContext : DbContext
    {
        protected readonly IConfiguration Configuration;

        public EntityContext(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        protected override void OnConfiguring(DbContextOptionsBuilder options)
        {
            // connect to postgres with connection string from app settings
            options.UseNpgsql(Configuration.GetConnectionString("DatabaseConnection"));
        }

        public DbSet<User> User { get; set; }
        public DbSet<Score> Score { get; set; }
        public DbSet<TodayGuessNumber> TodayGuessNumber { get; set; }
        public DbSet<TodayGuessNumberRange> TodayGuessNumberRange { get; set; }
        public DbSet<Song> Song { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {

            //TABLES WITH 2+ PRIMARY KEYS

            modelBuilder.Entity<Score>()
                .HasKey(e => new { e.Userunique_token, e.date });

            modelBuilder.Entity<TodayGuessNumberRange>()
                .HasKey(e => new { e.min_value, e.max_value });

            //AUTO INCREMENT ID

            modelBuilder.Entity<Song>()
                .Property(s => s.id)
                .ValueGeneratedOnAdd();

            //DEFAULT VALUES FOR TESTING

            modelBuilder.Entity<User>()
                .HasData(
                new User { unique_token = "a2a72798-690c-4301-9a01-1cf88e2080cc" }
            );

            modelBuilder.Entity<TodayGuessNumberRange>()
                .HasData(
                new TodayGuessNumberRange { min_value = 503, max_value = 528 }
            );

            modelBuilder.Entity<Score>()
                .HasData(
                new Score { Userunique_token = "a2a72798-690c-4301-9a01-1cf88e2080cc", date = DateOnly.FromDateTime(DateTime.Now.ToUniversalTime()), attempts = 3, win = true }
            );

            #region Default Song Dataset
            
            //DEFAULT SONG DATASET
            modelBuilder.Entity<Song>()
                .HasData(
                new Song { id = 528, year = 2022, country = "Albania", artist_name = "Ronela Hajati", song_name = "Sekret", video_id = "iMu47raqbcc", seek_to = 10 },
                new Song { id = 527, year = 2022, country = "Latvia", artist_name = "Citi Zeni", song_name = "Eat Your Salad", video_id = "Ni5UEqfoOu0", seek_to = 0 },
                new Song { id = 526, year = 2022, country = "Lithuania", artist_name = "Monika Liu", song_name = "Sentimentai", video_id = "acya6UcJP1k", seek_to = 4 },
                new Song { id = 525, year = 2022, country = "Switzerland", artist_name = "Marius Bear", song_name = "Boys Do Cry", video_id = "ubNIpxo-gMo", seek_to = 0 },
                new Song { id = 524, year = 2022, country = "Slovenia", artist_name = "LPS", song_name = "Disko", video_id = "S9fhdc-e4_Y", seek_to = 0 },
                new Song { id = 523, year = 2022, country = "Ukraine", artist_name = "Kalush Orchestra", song_name = "Stefania", video_id = "Z8Z51no1TD0", seek_to = 0 },
                new Song { id = 522, year = 2022, country = "Bulgaria", artist_name = "Intelligent Music Project", song_name = "Intention", video_id = "UBIj9VGdT-A", seek_to = 0 },
                new Song { id = 521, year = 2022, country = "Netherlands", artist_name = "S10", song_name = "De diepte", video_id = "I7NyzU1ob_M", seek_to = 0 },
                new Song { id = 520, year = 2022, country = "Moldova", artist_name = "Zdob si Zdub and Advahov Brothers", song_name = "Trenuletul", video_id = "3Mc_QsVPf7k", seek_to = 0 },
                new Song { id = 519, year = 2022, country = "Portugal", artist_name = "Maro", song_name = "Saudade, saudade", video_id = "tIgwFHV78jg", seek_to = 0 },
                new Song { id = 518, year = 2022, country = "Croatia", artist_name = "Mia Dimsic", song_name = "Guilty Pleasure", video_id = "VdOitl6KekY", seek_to = 0 },
                new Song { id = 517, year = 2022, country = "Denmark", artist_name = "Reddi", song_name = "The Show", video_id = "kjZnFKceS3M", seek_to = 0 },
                new Song { id = 516, year = 2022, country = "Austria", artist_name = "Lumix feat. Pia Maria", song_name = "Halo", video_id = "lyRUUshYqDM", seek_to = 0 },
                new Song { id = 515, year = 2022, country = "Iceland", artist_name = "Systur", song_name = "Meo aekkandi sol", video_id = "PAItdosVx8g", seek_to = 0 },
                new Song { id = 514, year = 2022, country = "Greece", artist_name = "Amanda Georgiadi Tenfjord", song_name = "Die Together", video_id = "SDICrEVOh6o", seek_to = 0 },
                new Song { id = 513, year = 2022, country = "Norway", artist_name = "Subwoolfer", song_name = "Give That Wolf a Banana", video_id = "sDvXhZtcp0w", seek_to = 0 },
                new Song { id = 512, year = 2022, country = "Armenia", artist_name = "Rosa Linn", song_name = "Snap", video_id = "gVqGKkm7xBE", seek_to = 4 },
                new Song { id = 511, year = 2022, country = "Finland", artist_name = "The Rasmus", song_name = "Jezebel", video_id = "FDpTiIectII", seek_to = 0 },
                new Song { id = 510, year = 2022, country = "Israel", artist_name = "Michael Ben David", song_name = "I.M", video_id = "D3LEEpIsxSs", seek_to = 0 },
                new Song { id = 509, year = 2022, country = "Serbia", artist_name = "Konstrakta", song_name = "In corpore sano", video_id = "2ilIAT5WbtI", seek_to = 0 },
                new Song { id = 508, year = 2022, country = "Azerbaijan", artist_name = "Nadir Rustamli", song_name = "Fade to Black", video_id = "hkE2ISzZDnc", seek_to = 0 },
                new Song { id = 507, year = 2022, country = "Georgia", artist_name = "Circus Mircus", song_name = "Lock Me In", video_id = "O6UqeUwCldM", seek_to = 0 },
                new Song { id = 506, year = 2022, country = "Malta", artist_name = "Emma Muscat", song_name = "I Am What I Am", video_id = "F_bT29reBkI", seek_to = 0 },
                new Song { id = 505, year = 2022, country = "San Marino", artist_name = "Achille Lauro", song_name = "Stripper", video_id = "PtKc-GaEiR8", seek_to = 0 },
                new Song { id = 504, year = 2022, country = "Australia", artist_name = "Sheldon Riley", song_name = "Not the Same", video_id = "QL3uK_sR-Xw", seek_to = 0 },
                new Song { id = 503, year = 2022, country = "Cyprus", artist_name = "Andromache", song_name = "Ela", video_id = "YcGNhJhR4HY", seek_to = 5 },
                new Song { id = 502, year = 2022, country = "Ireland", artist_name = "Brooke", song_name = "That's Rich", video_id = "", seek_to = 0 },
                new Song { id = 501, year = 2022, country = "North Macedonia", artist_name = "Andrea", song_name = "Circles", video_id = "", seek_to = 0 },
                new Song { id = 500, year = 2022, country = "Estonia", artist_name = "Stefan", song_name = "Hope", video_id = "", seek_to = 0 },
                new Song { id = 499, year = 2022, country = "Romania", artist_name = "WRS", song_name = "Llamame", video_id = "", seek_to = 0 },
                new Song { id = 498, year = 2022, country = "Poland", artist_name = "Ochman", song_name = "River", video_id = "", seek_to = 0 },
                new Song { id = 497, year = 2022, country = "Montenegro", artist_name = "Vladana", song_name = "Breathe", video_id = "", seek_to = 0 },
                new Song { id = 496, year = 2022, country = "Belgium", artist_name = "Jeremie Makiese", song_name = "Miss You", video_id = "", seek_to = 0 },
                new Song { id = 495, year = 2022, country = "Sweden", artist_name = "Cornelia Jakobs", song_name = "Hold Me Closer", video_id = "", seek_to = 0 },
                new Song { id = 494, year = 2022, country = "Czech Republic", artist_name = "We Are Domi", song_name = "Lights Off", video_id = "", seek_to = 0 },
                new Song { id = 493, year = 2022, country = "Italy", artist_name = "Mahmood and Blanco", song_name = "Brividi", video_id = "", seek_to = 0 },
                new Song { id = 492, year = 2022, country = "Spain", artist_name = "Chanel", song_name = "SloMo", video_id = "", seek_to = 0 },
                new Song { id = 491, year = 2022, country = "Germany", artist_name = "Malik Harris", song_name = "Rockstars", video_id = "", seek_to = 0 },
                new Song { id = 490, year = 2022, country = "United Kingdom", artist_name = "Sam Ryder", song_name = "Space Man", video_id = "", seek_to = 0 },
                new Song { id = 489, year = 2022, country = "France", artist_name = "Alvan and Ahez", song_name = "Fulenn", video_id = "", seek_to = 0 },
                new Song { id = 488, year = 2021, country = "Lithuania", artist_name = "The Roop", song_name = "Discoteque", video_id = "", seek_to = 0 },
                new Song { id = 487, year = 2021, country = "Slovenia", artist_name = "Ana Soklic", song_name = "Amen", video_id = "", seek_to = 0 },
                new Song { id = 486, year = 2021, country = "Russia", artist_name = "Manizha", song_name = "Russian Woman", video_id = "", seek_to = 0 },
                new Song { id = 485, year = 2021, country = "Sweden", artist_name = "Tusse", song_name = "Voices", video_id = "", seek_to = 0 },
                new Song { id = 484, year = 2021, country = "Australia", artist_name = "Montaigne", song_name = "Technicolour", video_id = "", seek_to = 0 },
                new Song { id = 483, year = 2021, country = "North Macedonia", artist_name = "Vasil", song_name = "Here I Stand", video_id = "", seek_to = 0 },
                new Song { id = 482, year = 2021, country = "Ireland", artist_name = "Lesley Roy", song_name = "Maps", video_id = "", seek_to = 0 },
                new Song { id = 481, year = 2021, country = "Cyprus", artist_name = "Elena Tsagrinou", song_name = "El Diablo", video_id = "", seek_to = 0 },
                new Song { id = 480, year = 2021, country = "Norway", artist_name = "Tix", song_name = "Fallen Angel", video_id = "", seek_to = 0 },
                new Song { id = 479, year = 2021, country = "Croatia", artist_name = "Albina", song_name = "Tick-Tock", video_id = "", seek_to = 0 },
                new Song { id = 478, year = 2021, country = "Belgium", artist_name = "Hooverphonic", song_name = "The Wrong Place", video_id = "", seek_to = 0 },
                new Song { id = 477, year = 2021, country = "Israel", artist_name = "Eden Alene", song_name = "Set Me Free", video_id = "", seek_to = 0 },
                new Song { id = 476, year = 2021, country = "Romania", artist_name = "Roxen", song_name = "Amnesia", video_id = "", seek_to = 0 },
                new Song { id = 475, year = 2021, country = "Azerbaijan", artist_name = "Efendi", song_name = "Mata Hari", video_id = "", seek_to = 0 },
                new Song { id = 474, year = 2021, country = "Ukraine", artist_name = "Go_A", song_name = "Shum", video_id = "", seek_to = 0 },
                new Song { id = 473, year = 2021, country = "Malta", artist_name = "Destiny", song_name = "Je me casse", video_id = "", seek_to = 0 },
                new Song { id = 472, year = 2021, country = "San Marino", artist_name = "Senhit", song_name = "Adrenalina", video_id = "", seek_to = 0 },
                new Song { id = 471, year = 2021, country = "Estonia", artist_name = "Uku Suviste", song_name = "The Lucky One", video_id = "", seek_to = 0 },
                new Song { id = 470, year = 2021, country = "Czech Republic", artist_name = "Benny Cristo", song_name = "Omaga", video_id = "", seek_to = 0 },
                new Song { id = 469, year = 2021, country = "Greece", artist_name = "Stefania", song_name = "Last Dance", video_id = "", seek_to = 0 },
                new Song { id = 468, year = 2021, country = "Austria", artist_name = "Vincent Bueno", song_name = "Amen", video_id = "", seek_to = 0 },
                new Song { id = 467, year = 2021, country = "Poland", artist_name = "Rafal", song_name = "The Ride", video_id = "", seek_to = 0 },
                new Song { id = 466, year = 2021, country = "Moldova", artist_name = "Natalia Gordienko", song_name = "Sugar", video_id = "", seek_to = 0 },
                new Song { id = 465, year = 2021, country = "Iceland", artist_name = "Dadi og Gagnamagnio", song_name = "10 Years", video_id = "", seek_to = 0 },
                new Song { id = 464, year = 2021, country = "Serbia", artist_name = "Hurricane", song_name = "Loco Loco", video_id = "", seek_to = 0 },
                new Song { id = 463, year = 2021, country = "Georgia", artist_name = "Tornike Kipiani", song_name = "You", video_id = "", seek_to = 0 },
                new Song { id = 462, year = 2021, country = "Albania", artist_name = "Anxhela Peristeri", song_name = "Karma", video_id = "", seek_to = 0 },
                new Song { id = 461, year = 2021, country = "Portugal", artist_name = "The Black Mamba", song_name = "Love Is on My Side", video_id = "", seek_to = 0 },
                new Song { id = 460, year = 2021, country = "Bulgaria", artist_name = "Victoria", song_name = "Growing Up Is Getting Old", video_id = "", seek_to = 0 },
                new Song { id = 459, year = 2021, country = "Finland", artist_name = "Blind Channel", song_name = "Dark Side", video_id = "", seek_to = 0 },
                new Song { id = 458, year = 2021, country = "Latvia", artist_name = "Samanta Tina", song_name = "The Moon Is Rising", video_id = "", seek_to = 0 },
                new Song { id = 457, year = 2021, country = "Switzerland", artist_name = "Gjon's Tears", song_name = "Tout l'univers", video_id = "", seek_to = 0 },
                new Song { id = 456, year = 2021, country = "Denmark", artist_name = "Fyr og Flamme", song_name = "Ove os pa hinanden", video_id = "", seek_to = 0 },
                new Song { id = 455, year = 2021, country = "Netherlands", artist_name = "Jeangu Macrooy", song_name = "Birth of a New Age", video_id = "", seek_to = 0 },
                new Song { id = 454, year = 2021, country = "Spain", artist_name = "Blas Canto", song_name = "Voy a quedarme", video_id = "", seek_to = 0 },
                new Song { id = 453, year = 2021, country = "United Kingdom", artist_name = "James Newman", song_name = "Embers", video_id = "", seek_to = 0 },
                new Song { id = 452, year = 2021, country = "Germany", artist_name = "Jendrik", song_name = "I Don't Feel Hate", video_id = "", seek_to = 0 },
                new Song { id = 451, year = 2021, country = "France", artist_name = "Barbara Pravi", song_name = "Voila", video_id = "", seek_to = 0 },
                new Song { id = 450, year = 2021, country = "Italy", artist_name = "Maneskin", song_name = "Zitti e buoni", video_id = "", seek_to = 0 },
                new Song { id = 449, year = 2019, country = "Cyprus", artist_name = "Tamta", song_name = "Replay", video_id = "", seek_to = 0 },
                new Song { id = 448, year = 2019, country = "Montenegro", artist_name = "D mol", song_name = "Heaven", video_id = "", seek_to = 0 },
                new Song { id = 447, year = 2019, country = "Finland", artist_name = "Darude feat. Sebastian Rejman", song_name = "Look Away", video_id = "", seek_to = 0 },
                new Song { id = 446, year = 2019, country = "Poland", artist_name = "Tulia", song_name = "Fire of Love", video_id = "", seek_to = 0 },
                new Song { id = 445, year = 2019, country = "Slovenia", artist_name = "Zala Kralj & Gasper santl", song_name = "Sebi", video_id = "", seek_to = 0 },
                new Song { id = 444, year = 2019, country = "Czech Republic", artist_name = "Lake Malawi", song_name = "Friend of a Friend", video_id = "", seek_to = 0 },
                new Song { id = 443, year = 2019, country = "Hungary", artist_name = "Joci Papai", song_name = "Az en apam", video_id = "", seek_to = 0 },
                new Song { id = 442, year = 2019, country = "Belarus", artist_name = "ZENA", song_name = "Like It", video_id = "", seek_to = 0 },
                new Song { id = 441, year = 2019, country = "Serbia", artist_name = "Nevena Bozovic", song_name = "Kruna", video_id = "", seek_to = 0 },
                new Song { id = 440, year = 2019, country = "Belgium", artist_name = "Eliot", song_name = "Wake Up", video_id = "", seek_to = 0 },
                new Song { id = 439, year = 2019, country = "Georgia", artist_name = "Oto Nemsadze", song_name = "Keep on Going", video_id = "", seek_to = 0 },
                new Song { id = 438, year = 2019, country = "Australia", artist_name = "Kate Miller-Heidke", song_name = "Zero Gravity", video_id = "", seek_to = 0 },
                new Song { id = 437, year = 2019, country = "Iceland", artist_name = "Hatari", song_name = "Hatrio mun sigra", video_id = "", seek_to = 0 },
                new Song { id = 436, year = 2019, country = "Estonia", artist_name = "Victor Crone", song_name = "Storm", video_id = "", seek_to = 0 },
                new Song { id = 435, year = 2019, country = "Portugal", artist_name = "Conan Osiris", song_name = "TelemOveis", video_id = "", seek_to = 0 },
                new Song { id = 434, year = 2019, country = "Greece", artist_name = "Katerine Duska", song_name = "Better Love", video_id = "", seek_to = 0 },
                new Song { id = 433, year = 2019, country = "San Marino", artist_name = "Serhat", song_name = "Say Na Na Na", video_id = "", seek_to = 0 },
                new Song { id = 432, year = 2019, country = "Armenia", artist_name = "Srbuk", song_name = "Walking Out", video_id = "", seek_to = 0 },
                new Song { id = 431, year = 2019, country = "Ireland", artist_name = "Sarah McTernan", song_name = "22", video_id = "", seek_to = 0 },
                new Song { id = 430, year = 2019, country = "Moldova", artist_name = "Anna Odobescu", song_name = "Stay", video_id = "", seek_to = 0 },
                new Song { id = 429, year = 2019, country = "Switzerland", artist_name = "Luca Hanni", song_name = "She Got Me", video_id = "", seek_to = 0 },
                new Song { id = 428, year = 2019, country = "Latvia", artist_name = "Carousel", song_name = "That Night", video_id = "", seek_to = 0 },
                new Song { id = 427, year = 2019, country = "Romania", artist_name = "Ester Peony", song_name = "On a Sunday", video_id = "", seek_to = 0 },
                new Song { id = 426, year = 2019, country = "Denmark", artist_name = "Leonora", song_name = "Love Is Forever", video_id = "", seek_to = 0 },
                new Song { id = 425, year = 2019, country = "Sweden", artist_name = "John Lundvik", song_name = "Too Late for Love", video_id = "", seek_to = 0 },
                new Song { id = 424, year = 2019, country = "Austria", artist_name = "PAENDA", song_name = "Limits", video_id = "", seek_to = 0 },
                new Song { id = 423, year = 2019, country = "Croatia", artist_name = "Roko", song_name = "The Dream", video_id = "", seek_to = 0 },
                new Song { id = 422, year = 2019, country = "Malta", artist_name = "Michela", song_name = "Chameleon", video_id = "", seek_to = 0 },
                new Song { id = 421, year = 2019, country = "Lithuania", artist_name = "Jurij Veklenko", song_name = "Run with the Lions", video_id = "", seek_to = 0 },
                new Song { id = 420, year = 2019, country = "Russia", artist_name = "Sergey Lazarev", song_name = "Scream", video_id = "", seek_to = 0 },
                new Song { id = 419, year = 2019, country = "Albania", artist_name = "Jonida Maliqi", song_name = "Ktheju tokes", video_id = "", seek_to = 0 },
                new Song { id = 418, year = 2019, country = "Norway", artist_name = "KEiiNO", song_name = "Spirit in the Sky", video_id = "", seek_to = 0 },
                new Song { id = 417, year = 2019, country = "Netherlands", artist_name = "Duncan Laurence", song_name = "Arcade", video_id = "", seek_to = 0 },
                new Song { id = 416, year = 2019, country = "North Macedonia", artist_name = "Tamara Todevska", song_name = "Proud", video_id = "", seek_to = 0 },
                new Song { id = 415, year = 2019, country = "Azerbaijan", artist_name = "Chingiz", song_name = "Truth", video_id = "", seek_to = 0 },
                new Song { id = 414, year = 2019, country = "Germany", artist_name = "S!sters", song_name = "Sister", video_id = "", seek_to = 0 },
                new Song { id = 413, year = 2019, country = "Israel", artist_name = "Kobi Marimi", song_name = "Home", video_id = "", seek_to = 0 },
                new Song { id = 412, year = 2019, country = "United Kingdom", artist_name = "Michael Rice", song_name = "Bigger than Us", video_id = "", seek_to = 0 },
                new Song { id = 411, year = 2019, country = "France", artist_name = "Bilal Hassani", song_name = "Roi", video_id = "", seek_to = 0 },
                new Song { id = 410, year = 2019, country = "Italy", artist_name = "Mahmood", song_name = "Soldi", video_id = "", seek_to = 0 },
                new Song { id = 409, year = 2019, country = "Spain", artist_name = "Miki", song_name = "La Venda", video_id = "", seek_to = 0 },
                new Song { id = 408, year = 2018, country = "Azerbaijan", artist_name = "Aisel", song_name = "X My Heart", video_id = "", seek_to = 0 },
                new Song { id = 407, year = 2018, country = "Iceland", artist_name = "Ari Olafsson", song_name = "Our Choice", video_id = "", seek_to = 0 },
                new Song { id = 406, year = 2018, country = "Albania", artist_name = "Eugent Bushpepa", song_name = "Mall", video_id = "", seek_to = 0 },
                new Song { id = 405, year = 2018, country = "Belgium", artist_name = "Sennek", song_name = "A Matter of Time", video_id = "", seek_to = 0 },
                new Song { id = 404, year = 2018, country = "Czech Republic", artist_name = "Mikolas Josef", song_name = "Lie to Me", video_id = "", seek_to = 0 },
                new Song { id = 403, year = 2018, country = "Lithuania", artist_name = "Ieva Zasimauskaite", song_name = "When We're Old", video_id = "", seek_to = 0 },
                new Song { id = 402, year = 2018, country = "Israel", artist_name = "Netta", song_name = "Toy", video_id = "", seek_to = 0 },
                new Song { id = 401, year = 2018, country = "Belarus", artist_name = "Alekseev", song_name = "Forever", video_id = "", seek_to = 0 },
                new Song { id = 400, year = 2018, country = "Estonia", artist_name = "Elina Nechayeva", song_name = "La forza", video_id = "", seek_to = 0 },
                new Song { id = 399, year = 2018, country = "Bulgaria", artist_name = "Equinox", song_name = "Bones", video_id = "", seek_to = 0 },
                new Song { id = 398, year = 2018, country = "North Macedonia", artist_name = "Eye Cue", song_name = "Lost and Found", video_id = "", seek_to = 0 },
                new Song { id = 397, year = 2018, country = "Croatia", artist_name = "Franka", song_name = "Crazy", video_id = "", seek_to = 0 },
                new Song { id = 396, year = 2018, country = "Austria", artist_name = "Cesar Sampson", song_name = "Nobody but You", video_id = "", seek_to = 0 },
                new Song { id = 395, year = 2018, country = "Greece", artist_name = "Yianna Terzi", song_name = "Oniro mou", video_id = "", seek_to = 0 },
                new Song { id = 394, year = 2018, country = "Finland", artist_name = "Saara Aalto", song_name = "Monsters", video_id = "", seek_to = 0 },
                new Song { id = 393, year = 2018, country = "Armenia", artist_name = "Sevak Khanagyan", song_name = "Qami", video_id = "", seek_to = 0 },
                new Song { id = 392, year = 2018, country = "Switzerland", artist_name = "ZiBBZ", song_name = "Stones", video_id = "", seek_to = 0 },
                new Song { id = 391, year = 2018, country = "Ireland", artist_name = "Ryan O'Shaughnessy", song_name = "Together", video_id = "", seek_to = 0 },
                new Song { id = 390, year = 2018, country = "Cyprus", artist_name = "Eleni Foureira", song_name = "Fuego", video_id = "", seek_to = 0 },
                new Song { id = 389, year = 2018, country = "Norway", artist_name = "Alexander Rybak", song_name = "That's How You Write a Song", video_id = "", seek_to = 0 },
                new Song { id = 388, year = 2018, country = "Romania", artist_name = "The Humans", song_name = "Goodbye", video_id = "", seek_to = 0 },
                new Song { id = 387, year = 2018, country = "Serbia", artist_name = "Sanja Ilic & Balkanika", song_name = "Nova deca", video_id = "", seek_to = 0 },
                new Song { id = 386, year = 2018, country = "San Marino", artist_name = "Jessika feat. Jenifer Brening", song_name = "Who We Are", video_id = "", seek_to = 0 },
                new Song { id = 385, year = 2018, country = "Denmark", artist_name = "Rasmussen", song_name = "Higher Ground", video_id = "", seek_to = 0 },
                new Song { id = 384, year = 2018, country = "Russia", artist_name = "Julia Samoylova", song_name = "I Won't Break", video_id = "", seek_to = 0 },
                new Song { id = 383, year = 2018, country = "Moldova", artist_name = "DoReDoS", song_name = "My Lucky Day", video_id = "", seek_to = 0 },
                new Song { id = 382, year = 2018, country = "Netherlands", artist_name = "Waylon", song_name = "Outlaw in 'Em", video_id = "", seek_to = 0 },
                new Song { id = 381, year = 2018, country = "Australia", artist_name = "Jessica Mauboy", song_name = "We Got Love", video_id = "", seek_to = 0 },
                new Song { id = 380, year = 2018, country = "Georgia", artist_name = "Ethno-Jazz Band Iriao", song_name = "For You", video_id = "", seek_to = 0 },
                new Song { id = 379, year = 2018, country = "Poland", artist_name = "Gromee feat. Lukas Meijer", song_name = "Light Me Up", video_id = "", seek_to = 0 },
                new Song { id = 378, year = 2018, country = "Malta", artist_name = "Christabelle", song_name = "Taboo", video_id = "", seek_to = 0 },
                new Song { id = 377, year = 2018, country = "Hungary", artist_name = "AWS", song_name = "Viszlat nyar", video_id = "", seek_to = 0 },
                new Song { id = 376, year = 2018, country = "Latvia", artist_name = "Laura Rizzotto", song_name = "Funny Girl", video_id = "", seek_to = 0 },
                new Song { id = 375, year = 2018, country = "Sweden", artist_name = "Benjamin Ingrosso", song_name = "Dance You Off", video_id = "", seek_to = 0 },
                new Song { id = 374, year = 2018, country = "Montenegro", artist_name = "Vanja Radovanovic", song_name = "Inje", video_id = "", seek_to = 0 },
                new Song { id = 373, year = 2018, country = "Slovenia", artist_name = "Lea Sirk", song_name = "Hvala, ne!", video_id = "", seek_to = 0 },
                new Song { id = 372, year = 2018, country = "Ukraine", artist_name = "Melovin", song_name = "Under the Ladder", video_id = "", seek_to = 0 },
                new Song { id = 371, year = 2018, country = "Portugal", artist_name = "Claudia Pascoal", song_name = "O jardim", video_id = "", seek_to = 0 },
                new Song { id = 370, year = 2018, country = "United Kingdom", artist_name = "SuRie", song_name = "Storm", video_id = "", seek_to = 0 },
                new Song { id = 369, year = 2018, country = "Germany", artist_name = "Michael Schulte", song_name = "You Let Me Walk Alone", video_id = "", seek_to = 0 },
                new Song { id = 368, year = 2018, country = "France", artist_name = "Madame Monsieur", song_name = "Mercy", video_id = "", seek_to = 0 },
                new Song { id = 367, year = 2018, country = "Italy", artist_name = "Ermal Meta & Fabrizio Moro", song_name = "Non mi avete fatto niente", video_id = "", seek_to = 0 },
                new Song { id = 366, year = 2018, country = "Spain", artist_name = "Amaia & Alfred", song_name = "Tu canciOn", video_id = "", seek_to = 0 },
                new Song { id = 365, year = 2017, country = "Sweden", artist_name = "Robin Bengtsson", song_name = "I Can't Go On", video_id = "", seek_to = 0 },
                new Song { id = 364, year = 2017, country = "Georgia", artist_name = "Tamara Gachechiladze", song_name = "Keep the Faith", video_id = "", seek_to = 0 },
                new Song { id = 363, year = 2017, country = "Australia", artist_name = "Isaiah", song_name = "Don't Come Easy", video_id = "", seek_to = 0 },
                new Song { id = 362, year = 2017, country = "Albania", artist_name = "Lindita", song_name = "World", video_id = "", seek_to = 0 },
                new Song { id = 361, year = 2017, country = "Belgium", artist_name = "Blanche", song_name = "City Lights", video_id = "", seek_to = 0 },
                new Song { id = 360, year = 2017, country = "Montenegro", artist_name = "Slavko Kalezic", song_name = "Space", video_id = "", seek_to = 0 },
                new Song { id = 359, year = 2017, country = "Finland", artist_name = "Norma John", song_name = "Blackbird", video_id = "", seek_to = 0 },
                new Song { id = 358, year = 2017, country = "Azerbaijan", artist_name = "Dihaj", song_name = "Skeletons", video_id = "", seek_to = 0 },
                new Song { id = 357, year = 2017, country = "Portugal", artist_name = "Salvador Sobral", song_name = "Amar pelos dois", video_id = "", seek_to = 0 },
                new Song { id = 356, year = 2017, country = "Greece", artist_name = "Demy", song_name = "This Is Love", video_id = "", seek_to = 0 },
                new Song { id = 355, year = 2017, country = "Poland", artist_name = "Kasia Mos", song_name = "Flashlight", video_id = "", seek_to = 0 },
                new Song { id = 354, year = 2017, country = "Moldova", artist_name = "Sunstroke Project", song_name = "Hey, Mamma!", video_id = "", seek_to = 0 },
                new Song { id = 353, year = 2017, country = "Iceland", artist_name = "Svala", song_name = "Paper", video_id = "", seek_to = 0 },
                new Song { id = 352, year = 2017, country = "Czech Republic", artist_name = "Martina Barta", song_name = "My Turn", video_id = "", seek_to = 0 },
                new Song { id = 351, year = 2017, country = "Cyprus", artist_name = "Hovig", song_name = "Gravity", video_id = "", seek_to = 0 },
                new Song { id = 350, year = 2017, country = "Armenia", artist_name = "Artsvik", song_name = "Fly with Me", video_id = "", seek_to = 0 },
                new Song { id = 349, year = 2017, country = "Slovenia", artist_name = "Omar Naber", song_name = "On My Way", video_id = "", seek_to = 0 },
                new Song { id = 348, year = 2017, country = "Latvia", artist_name = "Triana Park", song_name = "Line", video_id = "", seek_to = 0 },
                new Song { id = 347, year = 2017, country = "Serbia", artist_name = "Tijana Bogicevic", song_name = "In Too Deep", video_id = "", seek_to = 0 },
                new Song { id = 346, year = 2017, country = "Austria", artist_name = "Nathan Trent", song_name = "Running on Air", video_id = "", seek_to = 0 },
                new Song { id = 345, year = 2017, country = "North Macedonia", artist_name = "Jana Burceska", song_name = "Dance Alone", video_id = "", seek_to = 0 },
                new Song { id = 344, year = 2017, country = "Malta", artist_name = "Claudia Faniello", song_name = "Breathlessly", video_id = "", seek_to = 0 },
                new Song { id = 343, year = 2017, country = "Romania", artist_name = "Ilinca ft. Alex Florea", song_name = "Yodel It!", video_id = "", seek_to = 0 },
                new Song { id = 342, year = 2017, country = "Netherlands", artist_name = "O'G3NE", song_name = "Lights and Shadows", video_id = "", seek_to = 0 },
                new Song { id = 341, year = 2017, country = "Hungary", artist_name = "Joci Papai", song_name = "Origo", video_id = "", seek_to = 0 },
                new Song { id = 340, year = 2017, country = "Denmark", artist_name = "Anja", song_name = "Where I Am", video_id = "", seek_to = 0 },
                new Song { id = 339, year = 2017, country = "Ireland", artist_name = "Brendan Murray", song_name = "Dying to Try", video_id = "", seek_to = 0 },
                new Song { id = 338, year = 2017, country = "San Marino", artist_name = "Valentina Monetta and Jimmie Wilson", song_name = "Spirit of the Night", video_id = "", seek_to = 0 },
                new Song { id = 337, year = 2017, country = "Croatia", artist_name = "Jacques Houdek", song_name = "My Friend", video_id = "", seek_to = 0 },
                new Song { id = 336, year = 2017, country = "Norway", artist_name = "JOWST", song_name = "Grab the Moment", video_id = "", seek_to = 0 },
                new Song { id = 335, year = 2017, country = "Switzerland", artist_name = "Timebelle", song_name = "Apollo", video_id = "", seek_to = 0 },
                new Song { id = 334, year = 2017, country = "Belarus", artist_name = "Naviband", song_name = "Story of My Life", video_id = "", seek_to = 0 },
                new Song { id = 333, year = 2017, country = "Bulgaria", artist_name = "Kristian Kostov", song_name = "Beautiful Mess", video_id = "", seek_to = 0 },
                new Song { id = 332, year = 2017, country = "Lithuania", artist_name = "Fusedmarc", song_name = "Rain of Revolution", video_id = "", seek_to = 0 },
                new Song { id = 331, year = 2017, country = "Estonia", artist_name = "Koit Toome and Laura", song_name = "Verona", video_id = "", seek_to = 0 },
                new Song { id = 330, year = 2017, country = "Israel", artist_name = "IMRI", song_name = "I Feel Alive", video_id = "", seek_to = 0 },
                new Song { id = 329, year = 2017, country = "Italy", artist_name = "Francesco Gabbani", song_name = "Occidentali's Karma", video_id = "", seek_to = 0 },
                new Song { id = 328, year = 2017, country = "Spain", artist_name = "Manel Navarro", song_name = "Do It for Your Lover", video_id = "", seek_to = 0 },
                new Song { id = 327, year = 2017, country = "United Kingdom", artist_name = "Lucie Jones", song_name = "Never Give Up on You", video_id = "", seek_to = 0 },
                new Song { id = 326, year = 2017, country = "Germany", artist_name = "Levina", song_name = "Perfect Life", video_id = "", seek_to = 0 },
                new Song { id = 325, year = 2017, country = "Ukraine", artist_name = "O.Torvald", song_name = "Time", video_id = "", seek_to = 0 },
                new Song { id = 324, year = 2017, country = "France", artist_name = "Alma", song_name = "Requiem", video_id = "", seek_to = 0 },
                new Song { id = 323, year = 2016, country = "Finland", artist_name = "Sandhja", song_name = "Sing It Away", video_id = "", seek_to = 0 },
                new Song { id = 322, year = 2016, country = "Greece", artist_name = "Argo", song_name = "Utopian Land", video_id = "", seek_to = 0 },
                new Song { id = 321, year = 2016, country = "Moldova", artist_name = "Lidia Isac", song_name = "Falling Stars", video_id = "", seek_to = 0 },
                new Song { id = 320, year = 2016, country = "Hungary", artist_name = "Freddie", song_name = "Pioneer", video_id = "", seek_to = 0 },
                new Song { id = 319, year = 2016, country = "Croatia", artist_name = "Nina Kraljic", song_name = "Lighthouse", video_id = "", seek_to = 0 },
                new Song { id = 318, year = 2016, country = "Netherlands", artist_name = "Douwe Bob", song_name = "Slow Down", video_id = "", seek_to = 0 },
                new Song { id = 317, year = 2016, country = "Armenia", artist_name = "Iveta Mukuchyan", song_name = "LoveWave", video_id = "", seek_to = 0 },
                new Song { id = 316, year = 2016, country = "San Marino", artist_name = "Serhat", song_name = "I Didn't Know", video_id = "", seek_to = 0 },
                new Song { id = 315, year = 2016, country = "Russia", artist_name = "Sergey Lazarev", song_name = "You Are the Only One", video_id = "", seek_to = 0 },
                new Song { id = 314, year = 2016, country = "Czech Republic", artist_name = "Gabriela Guncikova", song_name = "I Stand", video_id = "", seek_to = 0 },
                new Song { id = 313, year = 2016, country = "Cyprus", artist_name = "Minus One", song_name = "Alter Ego", video_id = "", seek_to = 0 },
                new Song { id = 312, year = 2016, country = "Austria", artist_name = "Zoe", song_name = "Loin d'ici", video_id = "", seek_to = 0 },
                new Song { id = 311, year = 2016, country = "Estonia", artist_name = "Juri Pootsmann", song_name = "Play", video_id = "", seek_to = 0 },
                new Song { id = 310, year = 2016, country = "Azerbaijan", artist_name = "Samra", song_name = "Miracle", video_id = "", seek_to = 0 },
                new Song { id = 309, year = 2016, country = "Montenegro", artist_name = "Highway", song_name = "The Real Thing", video_id = "", seek_to = 0 },
                new Song { id = 308, year = 2016, country = "Iceland", artist_name = "Greta SalOme", song_name = "Hear Them Calling", video_id = "", seek_to = 0 },
                new Song { id = 307, year = 2016, country = "Bosnia and Herzegovina", artist_name = "Dalal & Deen feat Ana Rucner and Jala", song_name = "Ljubav je", video_id = "", seek_to = 0 },
                new Song { id = 306, year = 2016, country = "Malta", artist_name = "Ira Losco", song_name = "Walk on Water", video_id = "", seek_to = 0 },
                new Song { id = 305, year = 2016, country = "Latvia", artist_name = "Justs", song_name = "Heartbeat", video_id = "", seek_to = 0 },
                new Song { id = 304, year = 2016, country = "Poland", artist_name = "Michal Szpak", song_name = "Color of Your Life", video_id = "", seek_to = 0 },
                new Song { id = 303, year = 2016, country = "Switzerland", artist_name = "Rykka", song_name = "The Last of Our Kind", video_id = "", seek_to = 0 },
                new Song { id = 302, year = 2016, country = "Israel", artist_name = "Hovi Star", song_name = "Made of Stars", video_id = "", seek_to = 0 },
                new Song { id = 301, year = 2016, country = "Belarus", artist_name = "Ivan", song_name = "Help You Fly", video_id = "", seek_to = 0 },
                new Song { id = 300, year = 2016, country = "Serbia", artist_name = "Sanja Vucic ZAA", song_name = "Goodbye (Shelter)", video_id = "", seek_to = 0 },
                new Song { id = 299, year = 2016, country = "Ireland", artist_name = "Nicky Byrne", song_name = "Sunlight", video_id = "", seek_to = 0 },
                new Song { id = 298, year = 2016, country = "North Macedonia", artist_name = "Kaliopi", song_name = "Dona", video_id = "", seek_to = 0 },
                new Song { id = 297, year = 2016, country = "Lithuania", artist_name = "Donny Montell", song_name = "I've Been Waiting for This Night", video_id = "", seek_to = 0 },
                new Song { id = 296, year = 2016, country = "Australia", artist_name = "Dami Im", song_name = "Sound of Silence", video_id = "", seek_to = 0 },
                new Song { id = 295, year = 2016, country = "Slovenia", artist_name = "ManuElla", song_name = "Blue and Red", video_id = "", seek_to = 0 },
                new Song { id = 294, year = 2016, country = "Bulgaria", artist_name = "Poli Genova", song_name = "If Love Was a Crime", video_id = "", seek_to = 0 },
                new Song { id = 293, year = 2016, country = "Denmark", artist_name = "Lighthouse X", song_name = "Soldiers of Love", video_id = "", seek_to = 0 },
                new Song { id = 292, year = 2016, country = "Ukraine", artist_name = "Jamala", song_name = "1944", video_id = "", seek_to = 0 },
                new Song { id = 291, year = 2016, country = "Norway", artist_name = "Agnete", song_name = "Icebreaker", video_id = "", seek_to = 0 },
                new Song { id = 290, year = 2016, country = "Georgia", artist_name = "Nika Kocharov & Young Georgian Lolitaz", song_name = "Midnight Gold", video_id = "", seek_to = 0 },
                new Song { id = 289, year = 2016, country = "Albania", artist_name = "Eneda Tarifa", song_name = "Fairytale", video_id = "", seek_to = 0 },
                new Song { id = 288, year = 2016, country = "Belgium", artist_name = "Laura Tesoro", song_name = "What's the Pressure", video_id = "", seek_to = 0 },
                new Song { id = 287, year = 2016, country = "Italy", artist_name = "Francesca Michielin", song_name = "No Degree of Separation", video_id = "", seek_to = 0 },
                new Song { id = 286, year = 2016, country = "Sweden", artist_name = "Frans", song_name = "If I Were Sorry", video_id = "", seek_to = 0 },
                new Song { id = 285, year = 2016, country = "Germany", artist_name = "Jamie-Lee", song_name = "Ghost", video_id = "", seek_to = 0 },
                new Song { id = 284, year = 2016, country = "France", artist_name = "Amir", song_name = "J'ai cherche", video_id = "", seek_to = 0 },
                new Song { id = 283, year = 2016, country = "Spain", artist_name = "Barei", song_name = "Say Yay!", video_id = "", seek_to = 0 },
                new Song { id = 282, year = 2016, country = "United Kingdom", artist_name = "Joe and Jake", song_name = "You're Not Alone", video_id = "", seek_to = 0 },
                new Song { id = 281, year = 2015, country = "Moldova", artist_name = "Eduard Romanyuta", song_name = "I Want Your Love", video_id = "", seek_to = 0 },
                new Song { id = 280, year = 2015, country = "Armenia", artist_name = "Genealogy", song_name = "Face the Shadow", video_id = "", seek_to = 0 },
                new Song { id = 279, year = 2015, country = "Belgium", artist_name = "Loic Nottet", song_name = "Rhythm Inside", video_id = "", seek_to = 0 },
                new Song { id = 278, year = 2015, country = "Netherlands", artist_name = "Trijntje Oosterhuis", song_name = "Walk Along", video_id = "", seek_to = 0 },
                new Song { id = 277, year = 2015, country = "Finland", artist_name = "Pertti Kurikan Nimipaivat", song_name = "Aina mun pitaa", video_id = "", seek_to = 0 },
                new Song { id = 276, year = 2015, country = "Greece", artist_name = "Maria Elena Kyriakou", song_name = "One Last Breath", video_id = "", seek_to = 0 },
                new Song { id = 275, year = 2015, country = "Estonia", artist_name = "Elina Born & Stig Rasta", song_name = "Goodbye to Yesterday", video_id = "", seek_to = 0 },
                new Song { id = 274, year = 2015, country = "North Macedonia", artist_name = "Daniel Kajmakoski", song_name = "Autumn Leaves", video_id = "", seek_to = 0 },
                new Song { id = 273, year = 2015, country = "Serbia", artist_name = "Bojana Stamenov", song_name = "Beauty Never Lies", video_id = "", seek_to = 0 },
                new Song { id = 272, year = 2015, country = "Hungary", artist_name = "Boggie", song_name = "Wars for Nothing", video_id = "", seek_to = 0 },
                new Song { id = 271, year = 2015, country = "Belarus", artist_name = "Uzari & Maimuna", song_name = "Time", video_id = "", seek_to = 0 },
                new Song { id = 270, year = 2015, country = "Russia", artist_name = "Polina Gagarina", song_name = "A Million Voices", video_id = "", seek_to = 0 },
                new Song { id = 269, year = 2015, country = "Denmark", artist_name = "Anti Social Media", song_name = "The Way You Are", video_id = "", seek_to = 0 },
                new Song { id = 268, year = 2015, country = "Albania", artist_name = "Elhaida Dani", song_name = "I'm Alive", video_id = "", seek_to = 0 },
                new Song { id = 267, year = 2015, country = "Romania", artist_name = "Voltaj", song_name = "De la capat", video_id = "", seek_to = 0 },
                new Song { id = 266, year = 2015, country = "Georgia", artist_name = "Nina Sublatti", song_name = "Warrior", video_id = "", seek_to = 0 },
                new Song { id = 265, year = 2015, country = "Lithuania", artist_name = "Monika Linkyte & Vaidas Baumila", song_name = "This Time", video_id = "", seek_to = 0 },
                new Song { id = 264, year = 2015, country = "Ireland", artist_name = "Molly Sterling", song_name = "Playing with Numbers", video_id = "", seek_to = 0 },
                new Song { id = 263, year = 2015, country = "San Marino", artist_name = "Anita Simoncini & Michele Perniola", song_name = "Chain of Lights", video_id = "", seek_to = 0 },
                new Song { id = 262, year = 2015, country = "Montenegro", artist_name = "Knez", song_name = "Adio", video_id = "", seek_to = 0 },
                new Song { id = 261, year = 2015, country = "Malta", artist_name = "Amber", song_name = "Warrior", video_id = "", seek_to = 0 },
                new Song { id = 260, year = 2015, country = "Norway", artist_name = "Morland & Debrah Scarlett", song_name = "A Monster Like Me", video_id = "", seek_to = 0 },
                new Song { id = 259, year = 2015, country = "Portugal", artist_name = "Leonor Andrade", song_name = "Ha um mar que nos separa", video_id = "", seek_to = 0 },
                new Song { id = 258, year = 2015, country = "Czech Republic", artist_name = "Marta Jandova & Vaclav Noid Barta", song_name = "Hope Never Dies", video_id = "", seek_to = 0 },
                new Song { id = 257, year = 2015, country = "Israel", artist_name = "Nadav Guedj", song_name = "Golden Boy", video_id = "", seek_to = 0 },
                new Song { id = 256, year = 2015, country = "Latvia", artist_name = "Aminata", song_name = "Love Injected", video_id = "", seek_to = 0 },
                new Song { id = 255, year = 2015, country = "Azerbaijan", artist_name = "Elnur Huseynov", song_name = "Hour of the Wolf", video_id = "", seek_to = 0 },
                new Song { id = 254, year = 2015, country = "Iceland", artist_name = "Maria Olafs", song_name = "Unbroken", video_id = "", seek_to = 0 },
                new Song { id = 253, year = 2015, country = "Sweden", artist_name = "Mans Zelmerlow", song_name = "Heroes", video_id = "", seek_to = 0 },
                new Song { id = 252, year = 2015, country = "Switzerland", artist_name = "Melanie Rene", song_name = "Time to Shine", video_id = "", seek_to = 0 },
                new Song { id = 251, year = 2015, country = "Cyprus", artist_name = "John Karayiannis", song_name = "One Thing I Should Have Done", video_id = "", seek_to = 0 },
                new Song { id = 250, year = 2015, country = "Slovenia", artist_name = "Maraaya", song_name = "Here for You", video_id = "", seek_to = 0 },
                new Song { id = 249, year = 2015, country = "Poland", artist_name = "Monika Kuszynska", song_name = "In the Name of Love", video_id = "", seek_to = 0 },
                new Song { id = 248, year = 2015, country = "France", artist_name = "Lisa Angell", song_name = "N'oubliez pas", video_id = "", seek_to = 0 },
                new Song { id = 247, year = 2015, country = "United Kingdom", artist_name = "Electro Velvet", song_name = "Still in Love with You", video_id = "", seek_to = 0 },
                new Song { id = 246, year = 2015, country = "Austria", artist_name = "The Makemakes", song_name = "I Am Yours", video_id = "", seek_to = 0 },
                new Song { id = 245, year = 2015, country = "Germany", artist_name = "Ann Sophie", song_name = "Black Smoke", video_id = "", seek_to = 0 },
                new Song { id = 244, year = 2015, country = "Spain", artist_name = "Edurne", song_name = "Amanecer", video_id = "", seek_to = 0 },
                new Song { id = 243, year = 2015, country = "Italy", artist_name = "Il Volo", song_name = "Grande amore", video_id = "", seek_to = 0 },
                new Song { id = 242, year = 2014, country = "Armenia", artist_name = "Aram MP3", song_name = "Not Alone", video_id = "", seek_to = 0 },
                new Song { id = 241, year = 2014, country = "Latvia", artist_name = "Aarzemnieki", song_name = "Cake to Bake", video_id = "", seek_to = 0 },
                new Song { id = 240, year = 2014, country = "Estonia", artist_name = "Tanja", song_name = "Amazing", video_id = "", seek_to = 0 },
                new Song { id = 239, year = 2014, country = "Sweden", artist_name = "Sanna Nielsen", song_name = "Undo", video_id = "", seek_to = 0 },
                new Song { id = 238, year = 2014, country = "Iceland", artist_name = "Pollaponk", song_name = "No Prejudice", video_id = "", seek_to = 0 },
                new Song { id = 237, year = 2014, country = "Albania", artist_name = "Hersi", song_name = "One Night's Anger", video_id = "", seek_to = 0 },
                new Song { id = 236, year = 2014, country = "Russia", artist_name = "Tolmachevy Sisters", song_name = "Shine", video_id = "", seek_to = 0 },
                new Song { id = 235, year = 2014, country = "Azerbaijan", artist_name = "Dilara Kazimova", song_name = "Start a Fire", video_id = "", seek_to = 0 },
                new Song { id = 234, year = 2014, country = "Ukraine", artist_name = "Mariya Yaremchuk", song_name = "Tick-Tock", video_id = "", seek_to = 0 },
                new Song { id = 233, year = 2014, country = "Belgium", artist_name = "Axel Hirsoux", song_name = "Mother", video_id = "", seek_to = 0 },
                new Song { id = 232, year = 2014, country = "Moldova", artist_name = "Cristina Scarlat", song_name = "Wild Soul", video_id = "", seek_to = 0 },
                new Song { id = 231, year = 2014, country = "San Marino", artist_name = "Valentina Monetta", song_name = "Maybe", video_id = "", seek_to = 0 },
                new Song { id = 230, year = 2014, country = "Portugal", artist_name = "Suzy", song_name = "Quero ser tua", video_id = "", seek_to = 0 },
                new Song { id = 229, year = 2014, country = "Netherlands", artist_name = "The Common Linnets", song_name = "Calm After the Storm", video_id = "", seek_to = 0 },
                new Song { id = 228, year = 2014, country = "Montenegro", artist_name = "Sergej cetkovic", song_name = "Moj svijet", video_id = "", seek_to = 0 },
                new Song { id = 227, year = 2014, country = "Hungary", artist_name = "Andras Kallay-Saunders", song_name = "Running", video_id = "", seek_to = 0 },
                new Song { id = 226, year = 2014, country = "Malta", artist_name = "Firelight", song_name = "Coming Home", video_id = "", seek_to = 0 },
                new Song { id = 225, year = 2014, country = "Israel", artist_name = "Mei Finegold", song_name = "Same Heart", video_id = "", seek_to = 0 },
                new Song { id = 224, year = 2014, country = "Norway", artist_name = "Carl Espen", song_name = "Silent Storm", video_id = "", seek_to = 0 },
                new Song { id = 223, year = 2014, country = "Georgia", artist_name = "The Shin and Mariko", song_name = "Three Minutes to Earth", video_id = "", seek_to = 0 },
                new Song { id = 222, year = 2014, country = "Poland", artist_name = "Donatan & Cleo", song_name = "My Slowianie   We Are Slavic", video_id = "", seek_to = 0 },
                new Song { id = 221, year = 2014, country = "Austria", artist_name = "Conchita Wurst", song_name = "Rise Like a Phoenix", video_id = "", seek_to = 0 },
                new Song { id = 220, year = 2014, country = "Lithuania", artist_name = "Vilija", song_name = "Attention", video_id = "", seek_to = 0 },
                new Song { id = 219, year = 2014, country = "Finland", artist_name = "Softengine", song_name = "Something Better", video_id = "", seek_to = 0 },
                new Song { id = 218, year = 2014, country = "Ireland", artist_name = "Can-Linn feat. Kasey Smith", song_name = "Heartbeat", video_id = "", seek_to = 0 },
                new Song { id = 217, year = 2014, country = "Belarus", artist_name = "Teo", song_name = "Cheesecake", video_id = "", seek_to = 0 },
                new Song { id = 216, year = 2014, country = "North Macedonia", artist_name = "Tijana", song_name = "To the Sky", video_id = "", seek_to = 0 },
                new Song { id = 215, year = 2014, country = "Switzerland", artist_name = "Sebalter", song_name = "Hunter of Stars", video_id = "", seek_to = 0 },
                new Song { id = 214, year = 2014, country = "Greece", artist_name = "Freaky Fortune feat. RiskyKidd", song_name = "Rise Up", video_id = "", seek_to = 0 },
                new Song { id = 213, year = 2014, country = "Slovenia", artist_name = "Tinkara Kovac", song_name = "Round and Round", video_id = "", seek_to = 0 },
                new Song { id = 212, year = 2014, country = "Romania", artist_name = "Paula Seling & Ovi", song_name = "Miracle", video_id = "", seek_to = 0 },
                new Song { id = 211, year = 2014, country = "Germany", artist_name = "Elaiza", song_name = "Is It Right", video_id = "", seek_to = 0 },
                new Song { id = 210, year = 2014, country = "France", artist_name = "TWIN TWIN", song_name = "Moustache", video_id = "", seek_to = 0 },
                new Song { id = 209, year = 2014, country = "Italy", artist_name = "Emma", song_name = "La mia citta", video_id = "", seek_to = 0 },
                new Song { id = 208, year = 2014, country = "Spain", artist_name = "Ruth Lorenzo", song_name = "Dancing in the Rain", video_id = "", seek_to = 0 },
                new Song { id = 207, year = 2014, country = "Denmark", artist_name = "Basim", song_name = "Cliche Love Song", video_id = "", seek_to = 0 },
                new Song { id = 206, year = 2014, country = "United Kingdom", artist_name = "Molly", song_name = "Children of the Universe", video_id = "", seek_to = 0 },
                new Song { id = 205, year = 2013, country = "Austria", artist_name = "Natalia Kelly", song_name = "Shine", video_id = "", seek_to = 0 },
                new Song { id = 204, year = 2013, country = "Estonia", artist_name = "Birgit", song_name = "Et uus saaks alguse", video_id = "", seek_to = 0 },
                new Song { id = 203, year = 2013, country = "Slovenia", artist_name = "Hannah", song_name = "Straight Into Love", video_id = "", seek_to = 0 },
                new Song { id = 202, year = 2013, country = "Croatia", artist_name = "Klapa s Mora", song_name = "Mizerja", video_id = "", seek_to = 0 },
                new Song { id = 201, year = 2013, country = "Denmark", artist_name = "Emmelie de Forest", song_name = "Only Teardrops", video_id = "", seek_to = 0 },
                new Song { id = 200, year = 2013, country = "Russia", artist_name = "Dina Garipova", song_name = "What If", video_id = "", seek_to = 0 },
                new Song { id = 199, year = 2013, country = "Ukraine", artist_name = "Zlata Ognevich", song_name = "Gravity", video_id = "", seek_to = 0 },
                new Song { id = 198, year = 2013, country = "Netherlands", artist_name = "Anouk", song_name = "Birds", video_id = "", seek_to = 0 },
                new Song { id = 197, year = 2013, country = "Montenegro", artist_name = "Who See", song_name = "Igranka", video_id = "", seek_to = 0 },
                new Song { id = 196, year = 2013, country = "Lithuania", artist_name = "Andrius Pojavis", song_name = "Something", video_id = "", seek_to = 0 },
                new Song { id = 195, year = 2013, country = "Belarus", artist_name = "Alyona Lanskaya", song_name = "Solayoh", video_id = "", seek_to = 0 },
                new Song { id = 194, year = 2013, country = "Moldova", artist_name = "Aliona Moon", song_name = "O mie", video_id = "", seek_to = 0 },
                new Song { id = 193, year = 2013, country = "Ireland", artist_name = "Ryan Dolan", song_name = "Only Love Survives", video_id = "", seek_to = 0 },
                new Song { id = 192, year = 2013, country = "Cyprus", artist_name = "Despina Olympiou", song_name = "An me thimasai", video_id = "", seek_to = 0 },
                new Song { id = 191, year = 2013, country = "Belgium", artist_name = "Roberto Bellarosa", song_name = "Love Kills", video_id = "", seek_to = 0 },
                new Song { id = 190, year = 2013, country = "Serbia", artist_name = "Moje 3", song_name = "Ljubav je svuda", video_id = "", seek_to = 0 },
                new Song { id = 189, year = 2013, country = "Latvia", artist_name = "PeR", song_name = "Here We Go", video_id = "", seek_to = 0 },
                new Song { id = 188, year = 2013, country = "San Marino", artist_name = "Valentina Monetta", song_name = "Crisalide (Vola)", video_id = "", seek_to = 0 },
                new Song { id = 187, year = 2013, country = "North Macedonia", artist_name = "Esma & Lozano", song_name = "Pred da se razdeni", video_id = "", seek_to = 0 },
                new Song { id = 186, year = 2013, country = "Azerbaijan", artist_name = "Farid Mammadov", song_name = "Hold Me", video_id = "", seek_to = 0 },
                new Song { id = 185, year = 2013, country = "Finland", artist_name = "Krista Siegfrids", song_name = "Marry Me", video_id = "", seek_to = 0 },
                new Song { id = 184, year = 2013, country = "Malta", artist_name = "Gianluca", song_name = "Tomorrow", video_id = "", seek_to = 0 },
                new Song { id = 183, year = 2013, country = "Bulgaria", artist_name = "Elitsa Todorova & Stoyan Yankoulov", song_name = "Samo shampioni", video_id = "", seek_to = 0 },
                new Song { id = 182, year = 2013, country = "Iceland", artist_name = "Eythor Ingi", song_name = "Eg a lif", video_id = "", seek_to = 0 },
                new Song { id = 181, year = 2013, country = "Greece", artist_name = "Koza Mostra feat. Agathon Iakovidis", song_name = "Alcohol Is Free", video_id = "", seek_to = 0 },
                new Song { id = 180, year = 2013, country = "Israel", artist_name = "Moran Mazor", song_name = "Rak Bishvilo", video_id = "", seek_to = 0 },
                new Song { id = 179, year = 2013, country = "Armenia", artist_name = "Dorians", song_name = "Lonely Planet", video_id = "", seek_to = 0 },
                new Song { id = 178, year = 2013, country = "Hungary", artist_name = "ByeAlex", song_name = "Kedvesem (Zoohacker Remix)", video_id = "", seek_to = 0 },
                new Song { id = 177, year = 2013, country = "Norway", artist_name = "Margaret Berger", song_name = "I Feed You My Love", video_id = "", seek_to = 0 },
                new Song { id = 176, year = 2013, country = "Albania", artist_name = "Adrian Lulgjuraj & Bledar Sejko", song_name = "Identitet", video_id = "", seek_to = 0 },
                new Song { id = 175, year = 2013, country = "Georgia", artist_name = "Nodi Tatishvili & Sophie Gelovani", song_name = "Waterfall", video_id = "", seek_to = 0 },
                new Song { id = 174, year = 2013, country = "Switzerland", artist_name = "Takasa", song_name = "You and Me", video_id = "", seek_to = 0 },
                new Song { id = 173, year = 2013, country = "Romania", artist_name = "Cezar", song_name = "It's My Life", video_id = "", seek_to = 0 },
                new Song { id = 172, year = 2013, country = "France", artist_name = "Amandine Bourgeois", song_name = "L'enfer et moi", video_id = "", seek_to = 0 },
                new Song { id = 171, year = 2013, country = "Spain", artist_name = "ESDM", song_name = "Contigo hasta el final", video_id = "", seek_to = 0 },
                new Song { id = 170, year = 2013, country = "Germany", artist_name = "Cascada", song_name = "Glorious", video_id = "", seek_to = 0 },
                new Song { id = 169, year = 2013, country = "United Kingdom", artist_name = "Bonnie Tyler", song_name = "Believe in Me", video_id = "", seek_to = 0 },
                new Song { id = 168, year = 2013, country = "Sweden", artist_name = "Robin Stjernberg", song_name = "You", video_id = "", seek_to = 0 },
                new Song { id = 167, year = 2013, country = "Italy", artist_name = "Marco Mengoni", song_name = "L'essenziale", video_id = "", seek_to = 0 },
                new Song { id = 166, year = 2012, country = "Montenegro", artist_name = "Rambo Amadeus", song_name = "Euro Neuro", video_id = "", seek_to = 0 },
                new Song { id = 165, year = 2012, country = "Iceland", artist_name = "Greta Salome and Jonsi", song_name = "Never Forget", video_id = "", seek_to = 0 },
                new Song { id = 164, year = 2012, country = "Greece", artist_name = "Eleftheria Eleftheriou", song_name = "Aphrodisiac", video_id = "", seek_to = 0 },
                new Song { id = 163, year = 2012, country = "Latvia", artist_name = "Anmary", song_name = "Beautiful Song", video_id = "", seek_to = 0 },
                new Song { id = 162, year = 2012, country = "Albania", artist_name = "Rona Nishliu", song_name = "Suus3", video_id = "", seek_to = 0 },
                new Song { id = 161, year = 2012, country = "Romania", artist_name = "Mandinga", song_name = "Zaleilah", video_id = "", seek_to = 0 },
                new Song { id = 160, year = 2012, country = "Switzerland", artist_name = "Sinplus", song_name = "Unbreakable", video_id = "", seek_to = 0 },
                new Song { id = 159, year = 2012, country = "Belgium", artist_name = "Iris", song_name = "Would You?", video_id = "", seek_to = 0 },
                new Song { id = 158, year = 2012, country = "Finland", artist_name = "Pernilla Karlsson", song_name = "Nar jag blundar", video_id = "", seek_to = 0 },
                new Song { id = 157, year = 2012, country = "Israel", artist_name = "Izabo", song_name = "Time", video_id = "", seek_to = 0 },
                new Song { id = 156, year = 2012, country = "San Marino", artist_name = "Valentina Monetta", song_name = "The Social Network Song (Oh Oh-Uh-Oh Oh)", video_id = "", seek_to = 0 },
                new Song { id = 155, year = 2012, country = "Cyprus", artist_name = "Ivi Adamou", song_name = "La La Love", video_id = "", seek_to = 0 },
                new Song { id = 154, year = 2012, country = "Denmark", artist_name = "Soluna Samay", song_name = "Should've Known Better", video_id = "", seek_to = 0 },
                new Song { id = 153, year = 2012, country = "Russia", artist_name = "Buranovskiye Babushki", song_name = "Party for Everybody", video_id = "", seek_to = 0 },
                new Song { id = 152, year = 2012, country = "Hungary", artist_name = "Compact Disco", song_name = "Sound of Our Hearts", video_id = "", seek_to = 0 },
                new Song { id = 151, year = 2012, country = "Austria", artist_name = "Trackshittaz", song_name = "Woki mit deim Popo", video_id = "", seek_to = 0 },
                new Song { id = 150, year = 2012, country = "Moldova", artist_name = "Pasha Parfeny", song_name = "Lautar", video_id = "", seek_to = 0 },
                new Song { id = 149, year = 2012, country = "Ireland", artist_name = "Jedward", song_name = "Waterline", video_id = "", seek_to = 0 },
                new Song { id = 148, year = 2012, country = "Serbia", artist_name = "zeljko Joksimovic", song_name = "Nije ljubav stvar ", video_id = "", seek_to = 0 },
                new Song { id = 147, year = 2012, country = "North Macedonia", artist_name = "Kaliopi", song_name = "Crno i belo", video_id = "", seek_to = 0 },
                new Song { id = 146, year = 2012, country = "Netherlands", artist_name = "Joan Franka", song_name = "You and Me", video_id = "", seek_to = 0 },
                new Song { id = 145, year = 2012, country = "Malta", artist_name = "Kurt Calleja", song_name = "This Is the Night", video_id = "", seek_to = 0 },
                new Song { id = 144, year = 2012, country = "Belarus", artist_name = "Litesound", song_name = "We Are the Heroes", video_id = "", seek_to = 0 },
                new Song { id = 143, year = 2012, country = "Portugal", artist_name = "Filipa Sousa", song_name = "Vida minha", video_id = "", seek_to = 0 },
                new Song { id = 142, year = 2012, country = "Ukraine", artist_name = "Gaitana", song_name = "Be My Guest", video_id = "", seek_to = 0 },
                new Song { id = 141, year = 2012, country = "Bulgaria", artist_name = "Sofi Marinova", song_name = "Love Unlimited", video_id = "", seek_to = 0 },
                new Song { id = 140, year = 2012, country = "Slovenia", artist_name = "Eva Boto", song_name = "Verjamem", video_id = "", seek_to = 0 },
                new Song { id = 139, year = 2012, country = "Croatia", artist_name = "Nina Badric", song_name = "Nebo", video_id = "", seek_to = 0 },
                new Song { id = 138, year = 2012, country = "Sweden", artist_name = "Loreen", song_name = "Euphoria", video_id = "", seek_to = 0 },
                new Song { id = 137, year = 2012, country = "Georgia", artist_name = "Anri Jokhadze", song_name = "I'm a Joker", video_id = "", seek_to = 0 },
                new Song { id = 136, year = 2012, country = "Turkey", artist_name = "Can Bonomo", song_name = "Love Me Back", video_id = "", seek_to = 0 },
                new Song { id = 135, year = 2012, country = "Estonia", artist_name = "Ott Lepland", song_name = "Kuula", video_id = "", seek_to = 0 },
                new Song { id = 134, year = 2012, country = "Slovakia", artist_name = "Max Jason Mai", song_name = "Don't Close Your Eyes", video_id = "", seek_to = 0 },
                new Song { id = 133, year = 2012, country = "Norway", artist_name = "Tooji", song_name = "Stay", video_id = "", seek_to = 0 },
                new Song { id = 132, year = 2012, country = "Bosnia and Herzegovina", artist_name = "Maya Sar", song_name = "Korake ti znam", video_id = "", seek_to = 0 },
                new Song { id = 131, year = 2012, country = "Lithuania", artist_name = "Donny Montell", song_name = "Love Is Blind", video_id = "", seek_to = 0 },
                new Song { id = 130, year = 2012, country = "United Kingdom", artist_name = "Engelbert Humperdinck", song_name = "Love Will Set You Free", video_id = "", seek_to = 0 },
                new Song { id = 129, year = 2012, country = "France", artist_name = "Anggun", song_name = "Echo (You and I)", video_id = "", seek_to = 0 },
                new Song { id = 128, year = 2012, country = "Italy", artist_name = "Nina Zilli", song_name = "L'amore e femmina (Out of Love)", video_id = "", seek_to = 0 },
                new Song { id = 127, year = 2012, country = "Azerbaijan", artist_name = "Sabina Babayeva", song_name = "When the Music Dies", video_id = "", seek_to = 0 },
                new Song { id = 126, year = 2012, country = "Spain", artist_name = "Pastora Soler", song_name = "Quedate conmigo (Stay With Me)", video_id = "", seek_to = 0 },
                new Song { id = 125, year = 2012, country = "Germany", artist_name = "Roman Lob", song_name = "Standing Still", video_id = "", seek_to = 0 },
                new Song { id = 124, year = 2011, country = "Poland", artist_name = "Magdalena Tul", song_name = "Jestem", video_id = "", seek_to = 0 },
                new Song { id = 123, year = 2011, country = "Norway", artist_name = "Stella Mwangi", song_name = "Haba Haba", video_id = "", seek_to = 0 },
                new Song { id = 122, year = 2011, country = "Albania", artist_name = "Aurela Ga e", song_name = "Feel the Passion", video_id = "", seek_to = 0 },
                new Song { id = 121, year = 2011, country = "Armenia", artist_name = "Emmy", song_name = "Boom Boom", video_id = "", seek_to = 0 },
                new Song { id = 120, year = 2011, country = "Turkey", artist_name = "Yuksek Sadakat", song_name = "Live It Up", video_id = "", seek_to = 0 },
                new Song { id = 119, year = 2011, country = "Serbia", artist_name = "Nina", song_name = "Caroban", video_id = "", seek_to = 0 },
                new Song { id = 118, year = 2011, country = "Russia", artist_name = "Alexey Vorobyov", song_name = "Get You", video_id = "", seek_to = 0 },
                new Song { id = 117, year = 2011, country = "Switzerland", artist_name = "Anna Rossinelli", song_name = "In Love for a While", video_id = "", seek_to = 0 },
                new Song { id = 116, year = 2011, country = "Georgia", artist_name = "Eldrine", song_name = "One More Day", video_id = "", seek_to = 0 },
                new Song { id = 115, year = 2011, country = "Finland", artist_name = "Paradise Oskar", song_name = "Da Da Dam", video_id = "", seek_to = 0 },
                new Song { id = 114, year = 2011, country = "Malta", artist_name = "Glen Vella", song_name = "One Life", video_id = "", seek_to = 0 },
                new Song { id = 113, year = 2011, country = "San Marino", artist_name = "Senit", song_name = "Stand By", video_id = "", seek_to = 0 },
                new Song { id = 112, year = 2011, country = "Croatia", artist_name = "Daria", song_name = "Celebrate", video_id = "", seek_to = 0 },
                new Song { id = 111, year = 2011, country = "Iceland", artist_name = "Sjonni's Friends", song_name = "Coming Home", video_id = "", seek_to = 0 },
                new Song { id = 110, year = 2011, country = "Hungary", artist_name = "Kati Wolf", song_name = "What About My Dreams?", video_id = "", seek_to = 0 },
                new Song { id = 109, year = 2011, country = "Portugal", artist_name = "Homens da Luta", song_name = "A luta e alegria", video_id = "", seek_to = 0 },
                new Song { id = 108, year = 2011, country = "Lithuania", artist_name = "Evelina Sasenko", song_name = "C'est ma vie", video_id = "", seek_to = 0 },
                new Song { id = 107, year = 2011, country = "Azerbaijan", artist_name = "Ell & Nikki", song_name = "Running Scared", video_id = "", seek_to = 0 },
                new Song { id = 106, year = 2011, country = "Greece", artist_name = "Loukas Giorkas feat. Stereo Mike", song_name = "Watch My Dance", video_id = "", seek_to = 0 },
                new Song { id = 105, year = 2011, country = "Bosnia and Herzegovina", artist_name = "Dino Merlin", song_name = "Love in Rewind", video_id = "", seek_to = 0 },
                new Song { id = 104, year = 2011, country = "Austria", artist_name = "Nadine Beiler", song_name = "The Secret Is Love", video_id = "", seek_to = 0 },
                new Song { id = 103, year = 2011, country = "Netherlands", artist_name = "3JS", song_name = "Never Alone", video_id = "", seek_to = 0 },
                new Song { id = 102, year = 2011, country = "Belgium", artist_name = "Witloof Bay", song_name = "With Love Baby", video_id = "", seek_to = 0 },
                new Song { id = 101, year = 2011, country = "Slovakia", artist_name = "TWiiNS", song_name = "I'm Still Alive", video_id = "", seek_to = 0 },
                new Song { id = 100, year = 2011, country = "Ukraine", artist_name = "Mika Newton", song_name = "Angel", video_id = "", seek_to = 0 },
                new Song { id = 99, year = 2011, country = "Moldova", artist_name = "Zdob si Zdub", song_name = "So Lucky", video_id = "", seek_to = 0 },
                new Song { id = 98, year = 2011, country = "Sweden", artist_name = "Eric Saade", song_name = "Popular", video_id = "", seek_to = 0 },
                new Song { id = 97, year = 2011, country = "Cyprus", artist_name = "Christos Mylordos", song_name = "San aggelos s'agapisa", video_id = "", seek_to = 0 },
                new Song { id = 96, year = 2011, country = "Bulgaria", artist_name = "Poli Genova", song_name = "Na inat", video_id = "", seek_to = 0 },
                new Song { id = 95, year = 2011, country = "North Macedonia", artist_name = "Vlatko Ilievski", song_name = "Rusinka", video_id = "", seek_to = 0 },
                new Song { id = 94, year = 2011, country = "Israel", artist_name = "Dana International", song_name = "Ding Dong", video_id = "", seek_to = 0 },
                new Song { id = 93, year = 2011, country = "Slovenia", artist_name = "Maja Keuc", song_name = "No One", video_id = "", seek_to = 0 },
                new Song { id = 92, year = 2011, country = "Romania", artist_name = "Hotel FM", song_name = "Change", video_id = "", seek_to = 0 },
                new Song { id = 91, year = 2011, country = "Estonia", artist_name = "Getter Jaani", song_name = "Rockefeller Street", video_id = "", seek_to = 0 },
                new Song { id = 90, year = 2011, country = "Belarus", artist_name = "Anastasia Vinnikova", song_name = "I Love Belarus", video_id = "", seek_to = 0 },
                new Song { id = 89, year = 2011, country = "Latvia", artist_name = "Musiqq", song_name = "Angel in Disguise", video_id = "", seek_to = 0 },
                new Song { id = 88, year = 2011, country = "Denmark", artist_name = "A Friend in London", song_name = "New Tomorrow", video_id = "", seek_to = 0 },
                new Song { id = 87, year = 2011, country = "Ireland", artist_name = "Jedward", song_name = "Lipstick", video_id = "", seek_to = 0 },
                new Song { id = 86, year = 2011, country = "France", artist_name = "Amaury Vassili", song_name = "Sognu", video_id = "", seek_to = 0 },
                new Song { id = 85, year = 2011, country = "Italy", artist_name = "Raphael Gualazzi", song_name = "Madness of Love", video_id = "", seek_to = 0 },
                new Song { id = 84, year = 2011, country = "United Kingdom", artist_name = "Blue", song_name = "I Can", video_id = "", seek_to = 0 },
                new Song { id = 83, year = 2011, country = "Germany", artist_name = "Lena", song_name = "Taken by a Stranger", video_id = "", seek_to = 0 },
                new Song { id = 82, year = 2011, country = "Spain", artist_name = "Lucia Perez", song_name = "Que me quiten lo bailao", video_id = "", seek_to = 0 },
                new Song { id = 81, year = 2010, country = "Moldova", artist_name = "SunStroke Project and Olia Tira", song_name = "Run Away", video_id = "", seek_to = 0 },
                new Song { id = 80, year = 2010, country = "Russia", artist_name = "Peter Nalitch and Friends", song_name = "Lost and Forgotten", video_id = "", seek_to = 0 },
                new Song { id = 79, year = 2010, country = "Estonia", artist_name = "Malcolm Lincoln", song_name = "Siren", video_id = "", seek_to = 0 },
                new Song { id = 78, year = 2010, country = "Slovakia", artist_name = "Kristina", song_name = "Horehronie", video_id = "", seek_to = 0 },
                new Song { id = 77, year = 2010, country = "Finland", artist_name = "Kuunkuiskaajat", song_name = "Tyolki ellaa", video_id = "", seek_to = 0 },
                new Song { id = 76, year = 2010, country = "Latvia", artist_name = "Aisha", song_name = "What For?", video_id = "", seek_to = 0 },
                new Song { id = 75, year = 2010, country = "Serbia", artist_name = "Milan Stankovic", song_name = "Ovo je Balkan", video_id = "", seek_to = 0 },
                new Song { id = 74, year = 2010, country = "Bosnia and Herzegovina", artist_name = "Vukasin Brajic", song_name = "Thunder and Lightning", video_id = "", seek_to = 0 },
                new Song { id = 73, year = 2010, country = "Poland", artist_name = "Marcin Mrozinski", song_name = "Legenda", video_id = "", seek_to = 0 },
                new Song { id = 72, year = 2010, country = "Belgium", artist_name = "Tom Dice", song_name = "Me and My Guitar", video_id = "", seek_to = 0 },
                new Song { id = 71, year = 2010, country = "Malta", artist_name = "Thea Garrett", song_name = "My Dream", video_id = "", seek_to = 0 },
                new Song { id = 70, year = 2010, country = "Albania", artist_name = "Juliana Pasha", song_name = "It's All About You", video_id = "", seek_to = 0 },
                new Song { id = 69, year = 2010, country = "Greece", artist_name = "Giorgos Alkaios and Friends", song_name = "OPA", video_id = "", seek_to = 0 },
                new Song { id = 68, year = 2010, country = "Portugal", artist_name = "Filipa Azevedo", song_name = "Ha dias assim", video_id = "", seek_to = 0 },
                new Song { id = 67, year = 2010, country = "North Macedonia", artist_name = "Gjoko Taneski", song_name = "Jas ja imam silata", video_id = "", seek_to = 0 },
                new Song { id = 66, year = 2010, country = "Belarus", artist_name = "3+2 feat Robert Wells", song_name = "Butterflies", video_id = "", seek_to = 0 },
                new Song { id = 65, year = 2010, country = "Iceland", artist_name = "Hera Bjork", song_name = "Je ne sais quoi", video_id = "", seek_to = 0 },
                new Song { id = 64, year = 2010, country = "Lithuania", artist_name = "InCulto", song_name = "Eastern European Funk", video_id = "", seek_to = 0 },
                new Song { id = 63, year = 2010, country = "Armenia", artist_name = "Eva Rivas", song_name = "Apricot Stone", video_id = "", seek_to = 0 },
                new Song { id = 62, year = 2010, country = "Israel", artist_name = "Harel Skaat", song_name = "Milim", video_id = "", seek_to = 0 },
                new Song { id = 61, year = 2010, country = "Denmark", artist_name = "Chanee and N'evergreen", song_name = "In a Moment Like This", video_id = "", seek_to = 0 },
                new Song { id = 60, year = 2010, country = "Switzerland", artist_name = "Michael von der Heide", song_name = "Il pleut de l'or", video_id = "", seek_to = 0 },
                new Song { id = 59, year = 2010, country = "Sweden", artist_name = "Anna Bergendahl", song_name = "This Is My Life", video_id = "", seek_to = 0 },
                new Song { id = 58, year = 2010, country = "Azerbaijan", artist_name = "Safura", song_name = "Drip Drop", video_id = "", seek_to = 0 },
                new Song { id = 57, year = 2010, country = "Ukraine", artist_name = "Alyosha", song_name = "Sweet People", video_id = "", seek_to = 0 },
                new Song { id = 56, year = 2010, country = "Netherlands", artist_name = "Sieneke", song_name = "Ik ben verliefd", video_id = "", seek_to = 0 },
                new Song { id = 55, year = 2010, country = "Romania", artist_name = "Paula Seling and Ovi", song_name = "Playing with Fire", video_id = "", seek_to = 0 },
                new Song { id = 54, year = 2010, country = "Slovenia", artist_name = "Ansambel zlindra and Kalamari", song_name = "Narodnozabavni rock", video_id = "", seek_to = 0 },
                new Song { id = 53, year = 2010, country = "Ireland", artist_name = "Niamh Kavanagh", song_name = "It's for You", video_id = "", seek_to = 0 },
                new Song { id = 52, year = 2010, country = "Bulgaria", artist_name = "Miro", song_name = "Angel si ti", video_id = "", seek_to = 0 },
                new Song { id = 51, year = 2010, country = "Cyprus", artist_name = "Jon Lilygreen and The Islanders", song_name = "Life Looks Better in Spring", video_id = "", seek_to = 0 },
                new Song { id = 50, year = 2010, country = "Croatia", artist_name = "Feminnem", song_name = "Lako je sve", video_id = "", seek_to = 0 },
                new Song { id = 49, year = 2010, country = "Georgia", artist_name = "Sofia Nizharadze", song_name = "Shine", video_id = "", seek_to = 0 },
                new Song { id = 48, year = 2010, country = "Turkey", artist_name = "maNga", song_name = "We Could Be the Same", video_id = "", seek_to = 0 },
                new Song { id = 47, year = 2010, country = "Spain", artist_name = "Daniel Diges", song_name = "Algo pequenito", video_id = "", seek_to = 0 },
                new Song { id = 46, year = 2010, country = "Norway", artist_name = "Didrik Solli-Tangen", song_name = "My Heart Is Yours", video_id = "", seek_to = 0 },
                new Song { id = 45, year = 2010, country = "United Kingdom", artist_name = "Josh Dubovie", song_name = "That Sounds Good to Me", video_id = "", seek_to = 0 },
                new Song { id = 44, year = 2010, country = "France", artist_name = "Jessy Matador", song_name = "Allez Ola Ole", video_id = "", seek_to = 0 },
                new Song { id = 43, year = 2010, country = "Germany", artist_name = "Lena", song_name = "Satellite", video_id = "", seek_to = 0 },
                new Song { id = 42, year = 2009, country = "Montenegro", artist_name = "Andrea Demirovic", song_name = "Just Get Out of My Life", video_id = "", seek_to = 0 },
                new Song { id = 41, year = 2009, country = "Czech Republic", artist_name = "Gipsy.cz", song_name = "Aven Romale", video_id = "", seek_to = 0 },
                new Song { id = 40, year = 2009, country = "Belgium", artist_name = "Copycat", song_name = "Copycat", video_id = "", seek_to = 0 },
                new Song { id = 39, year = 2009, country = "Belarus", artist_name = "Petr Elfimov", song_name = "Eyes That Never Lie", video_id = "", seek_to = 0 },
                new Song { id = 38, year = 2009, country = "Sweden", artist_name = "Malena Ernman", song_name = "La voix", video_id = "", seek_to = 0 },
                new Song { id = 37, year = 2009, country = "Armenia", artist_name = "Inga and Anush", song_name = "Jan Jan", video_id = "", seek_to = 0 },
                new Song { id = 36, year = 2009, country = "Andorra", artist_name = "Susanne Georgi", song_name = "La teva decisio (Get a Life)", video_id = "", seek_to = 0 },
                new Song { id = 35, year = 2009, country = "Switzerland", artist_name = "Lovebugs", song_name = "The Highest Heights", video_id = "", seek_to = 0 },
                new Song { id = 34, year = 2009, country = "Turkey", artist_name = "Hadise", song_name = "Dum Tek Tek", video_id = "", seek_to = 0 },
                new Song { id = 33, year = 2009, country = "Israel", artist_name = "Noa and Mira Awad", song_name = "There Must Be Another Way", video_id = "", seek_to = 0 },
                new Song { id = 32, year = 2009, country = "Bulgaria", artist_name = "Krassimir Avramov", song_name = "Illusion", video_id = "", seek_to = 0 },
                new Song { id = 31, year = 2009, country = "Iceland", artist_name = "Yohanna", song_name = "Is It True?", video_id = "", seek_to = 0 },
                new Song { id = 30, year = 2009, country = "North Macedonia", artist_name = "Next Time", song_name = "Nesto sto kje ostane", video_id = "", seek_to = 0 },
                new Song { id = 29, year = 2009, country = "Romania", artist_name = "Elena", song_name = "The Balkan Girls", video_id = "", seek_to = 0 },
                new Song { id = 28, year = 2009, country = "Finland", artist_name = "Waldo's People", song_name = "Lose Control", video_id = "", seek_to = 0 },
                new Song { id = 27, year = 2009, country = "Portugal", artist_name = "Flor-de-Lis", song_name = "Todas as ruas do amor", video_id = "", seek_to = 0 },
                new Song { id = 26, year = 2009, country = "Malta", artist_name = "Chiara", song_name = "What If We", video_id = "", seek_to = 0 },
                new Song { id = 25, year = 2009, country = "Bosnia and Herzegovina", artist_name = "Regina", song_name = "Bistra voda", video_id = "", seek_to = 0 },
                new Song { id = 24, year = 2009, country = "Croatia", artist_name = "Igor Cukrov feat. Andrea", song_name = "Lijepa Tena", video_id = "", seek_to = 0 },
                new Song { id = 23, year = 2009, country = "Ireland", artist_name = "Sinead Mulvey and Black Daisy", song_name = "Et Cetera", video_id = "", seek_to = 0 },
                new Song { id = 22, year = 2009, country = "Latvia", artist_name = "Intars Busulis", song_name = "Probka", video_id = "", seek_to = 0 },
                new Song { id = 21, year = 2009, country = "Serbia", artist_name = "Marko Kon and Milaan", song_name = "Cipela", video_id = "", seek_to = 0 },
                new Song { id = 20, year = 2009, country = "Poland", artist_name = "Lidia Kopania", song_name = "I Don't Wanna Leave", video_id = "", seek_to = 0 },
                new Song { id = 19, year = 2009, country = "Norway", artist_name = "Alexander Rybak", song_name = "Fairytale", video_id = "", seek_to = 0 },
                new Song { id = 18, year = 2009, country = "Cyprus", artist_name = "Christina Metaxa", song_name = "Firefly", video_id = "", seek_to = 0 },
                new Song { id = 17, year = 2009, country = "Slovakia", artist_name = "Kamil Mikulcik and Nela Pociskova", song_name = "Let tmou", video_id = "", seek_to = 0 },
                new Song { id = 16, year = 2009, country = "Denmark", artist_name = "Niels Brinck", song_name = "Believe Again", video_id = "", seek_to = 0 },
                new Song { id = 15, year = 2009, country = "Slovenia", artist_name = "Quartissimo feat. Martina", song_name = "Love Symphony", video_id = "", seek_to = 0 },
                new Song { id = 14, year = 2009, country = "Hungary", artist_name = "Zoli adok", song_name = "Dance with Me", video_id = "", seek_to = 0 },
                new Song { id = 13, year = 2009, country = "Azerbaijan", artist_name = "AySel and Arash", song_name = "Always", video_id = "", seek_to = 0 },
                new Song { id = 12, year = 2009, country = "Greece", artist_name = "Sakis Rouvas", song_name = "This Is Our Night", video_id = "", seek_to = 0 },
                new Song { id = 11, year = 2009, country = "Lithuania", artist_name = "Sasha Son", song_name = "Love", video_id = "", seek_to = 0 },
                new Song { id = 10, year = 2009, country = "Moldova", artist_name = "Nelly Ciobanu", song_name = "Hora din Moldova", video_id = "", seek_to = 0 },
                new Song { id = 9, year = 2009, country = "Albania", artist_name = "Kejsi Tola", song_name = "Carry Me in Your Dreams", video_id = "", seek_to = 0 },
                new Song { id = 8, year = 2009, country = "Ukraine", artist_name = "Svetlana Loboda", song_name = "Be My Valentine! (Anti-Crisis Girl)", video_id = "", seek_to = 0 },
                new Song { id = 7, year = 2009, country = "Estonia", artist_name = "Urban Symphony", song_name = "Randajad", video_id = "", seek_to = 0 },
                new Song { id = 6, year = 2009, country = "Netherlands", artist_name = "The Toppers", song_name = "Shine", video_id = "", seek_to = 0 },
                new Song { id = 5, year = 2009, country = "France", artist_name = "Patricia Kaas", song_name = "Et s'il fallait le faire", video_id = "", seek_to = 0 },
                new Song { id = 4, year = 2009, country = "Russia", artist_name = "Anastasiya Prikhodko", song_name = "Mamo", video_id = "", seek_to = 0 },
                new Song { id = 3, year = 2009, country = "Germany", artist_name = "Alex Swings Oscar Sings!", song_name = "Miss Kiss Kiss Bang", video_id = "", seek_to = 0 },
                new Song { id = 2, year = 2009, country = "United Kingdom", artist_name = "Jade Ewen", song_name = "It's My Time", video_id = "", seek_to = 0 },
                new Song { id = 1, year = 2009, country = "Spain", artist_name = "Soraya Arnelas", song_name = "La noche es para mi", video_id = "", seek_to = 0 }
            );
            #endregion
        }
    }
}
