using Euroguessr.Data.Tables;

namespace Euroguessr.Data
{
    public static class Worker_Song
    {
        /// <summary>
        /// Returns the default song table
        /// </summary>
        public static IEnumerable<Song> GetSongs()
        {
            List<object[]> raw_data = new List<object[]>
            {
                /*           ____________________________________________________________________________________________________________________________________________________
                             | ID | YEAR | COUNTRY                | ARTIST_NAME                            | SONG_NAME                                 | VIDEO_ID     | SEEK_TO | */
                new object[] { 528, 2022, "Albania",                "Ronela Hajati",                         "Sekret",                                   "iMu47raqbcc", 10 },
                new object[] { 527, 2022, "Latvia",                 "Citi Zeni",                             "Eat Your Salad",                           "Ni5UEqfoOu0", 0 },
                new object[] { 526, 2022, "Lithuania",              "Monika Liu",                            "Sentimentai",                              "acya6UcJP1k", 4 },
                new object[] { 525, 2022, "Switzerland",            "Marius Bear",                           "Boys Do Cry",                              "ubNIpxo-gMo", 0 },
                new object[] { 524, 2022, "Slovenia",               "LPS",                                   "Disko",                                    "S9fhdc-e4_Y", 0 },
                new object[] { 523, 2022, "Ukraine",                "Kalush Orchestra",                      "Stefania",                                 "Z8Z51no1TD0", 0 },
                new object[] { 522, 2022, "Bulgaria",               "Intelligent Music Project",             "Intention",                                "UBIj9VGdT-A", 0 },
                new object[] { 521, 2022, "Netherlands",            "S10",                                   "De diepte",                                "I7NyzU1ob_M", 0 },
                new object[] { 520, 2022, "Moldova",                "Zdob si Zdub and Advahov Brothers",     "Trenuletul",                               "3Mc_QsVPf7k", 0 },
                new object[] { 519, 2022, "Portugal",               "Maro",                                  "Saudade, saudade",                         "tIgwFHV78jg", 0 },
                new object[] { 518, 2022, "Croatia",                "Mia Dimsic",                            "Guilty Pleasure",                          "VdOitl6KekY", 0 },
                new object[] { 517, 2022, "Denmark",                "Reddi",                                 "The Show",                                 "kjZnFKceS3M", 0 },
                new object[] { 516, 2022, "Austria",                "Lumix feat. Pia Maria",                 "Halo",                                     "lyRUUshYqDM", 0 },
                new object[] { 515, 2022, "Iceland",                "Systur",                                "Meo aekkandi sol",                         "PAItdosVx8g", 0 },
                new object[] { 514, 2022, "Greece",                 "Amanda Georgiadi Tenfjord",             "Die Together",                             "SDICrEVOh6o", 0 },
                new object[] { 513, 2022, "Norway",                 "Subwoolfer",                            "Give That Wolf a Banana",                  "sDvXhZtcp0w", 0 },
                new object[] { 512, 2022, "Armenia",                "Rosa Linn",                             "Snap",                                     "gVqGKkm7xBE", 4 },
                new object[] { 511, 2022, "Finland",                "The Rasmus",                            "Jezebel",                                  "FDpTiIectII", 1 },
                new object[] { 510, 2022, "Israel",                 "Michael Ben David",                     "I.M",                                      "D3LEEpIsxSs", 0 },
                new object[] { 509, 2022, "Serbia",                 "Konstrakta",                            "In corpore sano",                          "2ilIAT5WbtI", 0 },
                new object[] { 508, 2022, "Azerbaijan",             "Nadir Rustamli",                        "Fade to Black",                            "hkE2ISzZDnc", 0 },
                new object[] { 507, 2022, "Georgia",                "Circus Mircus",                         "Lock Me In",                               "O6UqeUwCldM", 0 },
                new object[] { 506, 2022, "Malta",                  "Emma Muscat",                           "I Am What I Am",                           "F_bT29reBkI", 0 },
                new object[] { 505, 2022, "San Marino",             "Achille Lauro",                         "Stripper",                                 "PtKc-GaEiR8", 0 },
                new object[] { 504, 2022, "Australia",              "Sheldon Riley",                         "Not the Same",                             "QL3uK_sR-Xw", 0 },
                new object[] { 503, 2022, "Cyprus",                 "Andromache",                            "Ela",                                      "YcGNhJhR4HY", 5 },
                new object[] { 502, 2022, "Ireland",                "Brooke",                                "That's Rich",                              "AeRbnNFowwo", 0 },
                new object[] { 501, 2022, "North Macedonia",        "Andrea",                                "Circles",                                  "eAdg0tBSJdI", 0 },
                new object[] { 500, 2022, "Estonia",                "Stefan",                                "Hope",                                     "tE2KYttAHWA", 0 },
                new object[] { 499, 2022, "Romania",                "WRS",                                   "Llamame",                                  "HK0d9vz-Wso", 0 },
                new object[] { 498, 2022, "Poland",                 "Ochman",                                "River",                                    "xmZSvJ5LYBQ", 0 },
                new object[] { 497, 2022, "Montenegro",             "Vladana",                               "Breathe",                                  "mq7g1OYDB0k", 1 },
                new object[] { 496, 2022, "Belgium",                "Jeremie Makiese",                       "Miss You",                                 "TrerTgHa32M", 0 },
                new object[] { 495, 2022, "Sweden",                 "Cornelia Jakobs",                       "Hold Me Closer",                           "ysiygd9U35E", 0 },
                new object[] { 494, 2022, "Czech Republic",         "We Are Domi",                           "Lights Off",                               "ikTT6M61kCk", 0 },
                new object[] { 493, 2022, "Italy",                  "Mahmood and Blanco",                    "Brividi",                                  "ipu8FndEWeY", 0 },
                new object[] { 492, 2022, "Spain",                  "Chanel",                                "SloMo",                                    "3XlYDbdYXyw", 0 },
                new object[] { 491, 2022, "Germany",                "Malik Harris",                          "Rockstars",                                "aEGGO-jzgiY", 0 },
                new object[] { 490, 2022, "United Kingdom",         "Sam Ryder",                             "Space Man",                                "rjOZitwirzg", 0 },
                new object[] { 489, 2022, "France",                 "Alvan and Ahez",                        "Fulenn",                                   "pe29d9luZOc", 0 },
                new object[] { 488, 2021, "Lithuania",              "The Roop",                              "Discoteque",                               "o8DugwLhYvE", 0 },
                new object[] { 487, 2021, "Slovenia",               "Ana Soklic",                            "Amen",                                     "5qg5XOVNuXI", 0 },
                new object[] { 486, 2021, "Russia",                 "Manizha",                               "Russian Woman",                            "Rb7fXgMuV9k", 0 },
                new object[] { 485, 2021, "Sweden",                 "Tusse",                                 "Voices",                                   "ufeuSX6QPBo", 0 },
                new object[] { 484, 2021, "Australia",              "Montaigne",                             "Technicolour",                             "IMZDCMrEjMQ", 0 },
                new object[] { 483, 2021, "North Macedonia",        "Vasil",                                 "Here I Stand",                             "nd4YfjVWrro", 38 },
                new object[] { 482, 2021, "Ireland",                "Lesley Roy",                            "Maps",                                     "gWUfTfKkQZs", 0 },
                new object[] { 481, 2021, "Cyprus",                 "Elena Tsagrinou",                       "El Diablo",                                "HRIvhTSUDnU", 7 },
                new object[] { 480, 2021, "Norway",                 "Tix",                                   "Fallen Angel",                             "Hj3dHbpPhaE", 47 },
                new object[] { 479, 2021, "Croatia",                "Albina",                                "Tick-Tock",                                "Rj7-MgWdm6I", 0 },
                new object[] { 478, 2021, "Belgium",                "Hooverphonic",                          "The Wrong Place",                          "0EQyG1Yjlgw", 5 },
                new object[] { 477, 2021, "Israel",                 "Eden Alene",                            "Set Me Free",                              "9nss3FsrgJo", 5 },
                new object[] { 476, 2021, "Romania",                "Roxen",                                 "Amnesia",                                  "m6Yv8LmGTy4", 0 },
                new object[] { 475, 2021, "Azerbaijan",             "Efendi",                                "Mata Hari",                                "HSiZmR1c7Q4", 5 },
                new object[] { 474, 2021, "Ukraine",                "Go_A",                                  "Shum",                                     "HBzdC8_RSfs", 0 },
                new object[] { 473, 2021, "Malta",                  "Destiny",                               "Je me casse",                              "PQKiHr5qEfA", 27 },
                new object[] { 472, 2021, "San Marino",             "Senhit",                                "Adrenalina",                               "Zj6374-kXRk", 2 },
                new object[] { 471, 2021, "Estonia",                "Uku Suviste",                           "The Lucky One",                            "Xqjx8n4K82g", 1 },
                new object[] { 470, 2021, "Czech Republic",         "Benny Cristo",                          "Omaga",                                    "Kxa3ZtxIdxQ", 7 },
                new object[] { 469, 2021, "Greece",                 "Stefania",                              "Last Dance",                               "N7UulPncNqw", 1 },
                new object[] { 468, 2021, "Austria",                "Vincent Bueno",                         "Amen",                                     "1sY76L68rfs", 7 },
                new object[] { 467, 2021, "Poland",                 "Rafal",                                 "The Ride",                                 "y1ODgGzZOhs", 0 },
                new object[] { 466, 2021, "Moldova",                "Natalia Gordienko",                     "Sugar",                                    "1zvnsvxA3to", 9 },
                new object[] { 465, 2021, "Iceland",                "Dadi og Gagnamagnio",                   "10 Years",                                 "1zTbVRPh5EI", 68 },
                new object[] { 464, 2021, "Serbia",                 "Hurricane",                             "Loco Loco",                                "FSTMz-_kbVQ", 5 },
                new object[] { 463, 2021, "Georgia",                "Tornike Kipiani",                       "You",                                      "w6jzan8nfxc", 17 },
                new object[] { 462, 2021, "Albania",                "Anxhela Peristeri",                     "Karma",                                    "lilMt7mD510", 1 },
                new object[] { 461, 2021, "Portugal",               "The Black Mamba",                       "Love Is on My Side",                       "2hAlp3Khsnk", 5 },
                new object[] { 460, 2021, "Bulgaria",               "Victoria",                              "Growing Up Is Getting Old",                "-CsJNMid1_s", 0 },
                new object[] { 459, 2021, "Finland",                "Blind Channel",                         "Dark Side",                                "rhQftHLS0gw", 0 },
                new object[] { 458, 2021, "Latvia",                 "Samanta Tina",                          "The Moon Is Rising",                       "2WElcu0gDOA", 0 },
                new object[] { 457, 2021, "Switzerland",            "Gjon's Tears",                          "Tout l'univers",                           "EuimHmJMEFA", 0 },
                new object[] { 456, 2021, "Denmark",                "Fyr og Flamme",                         "Ove os pa hinanden",                       "xaTdsOPzoHU", 0 },
                new object[] { 455, 2021, "Netherlands",            "Jeangu Macrooy",                        "Birth of a New Age",                       "Md6DAg2P1jc", 3 },
                new object[] { 454, 2021, "Spain",                  "Blas Canto",                            "Voy a quedarme",                           "AcACERgLajE", 0 },
                new object[] { 453, 2021, "United Kingdom",         "James Newman",                          "Embers",                                   "5F02ZPH3syo", 0 },
                new object[] { 452, 2021, "Germany",                "Jendrik",                               "I Don't Feel Hate",                        "iDQw0s6KmTk", 0 },
                new object[] { 451, 2021, "France",                 "Barbara Pravi",                         "Voila",                                    "H8VHF_qYk_o", 0 },
                new object[] { 450, 2021, "Italy",                  "Maneskin",                              "Zitti e buoni",                            "QN1odfjtMoo", 0 },
                new object[] { 449, 2019, "Cyprus",                 "Tamta",                                 "Replay",                                   "", 0 },
                new object[] { 448, 2019, "Montenegro",             "D mol",                                 "Heaven",                                   "", 0 },
                new object[] { 447, 2019, "Finland",                "Darude feat. Sebastian Rejman",         "Look Away",                                "", 0 },
                new object[] { 446, 2019, "Poland",                 "Tulia",                                 "Fire of Love",                             "", 0 },
                new object[] { 445, 2019, "Slovenia",               "Zala Kralj & Gasper santl",             "Sebi",                                     "", 0 },
                new object[] { 444, 2019, "Czech Republic",         "Lake Malawi",                           "Friend of a Friend",                       "", 0 },
                new object[] { 443, 2019, "Hungary",                "Joci Papai",                            "Az en apam",                               "", 0 },
                new object[] { 442, 2019, "Belarus",                "ZENA",                                  "Like It",                                  "", 0 },
                new object[] { 441, 2019, "Serbia",                 "Nevena Bozovic",                        "Kruna",                                    "", 0 },
                new object[] { 440, 2019, "Belgium",                "Eliot",                                 "Wake Up",                                  "", 0 },
                new object[] { 439, 2019, "Georgia",                "Oto Nemsadze",                          "Keep on Going",                            "", 0 },
                new object[] { 438, 2019, "Australia",              "Kate Miller-Heidke",                    "Zero Gravity",                             "", 0 },
                new object[] { 437, 2019, "Iceland",                "Hatari",                                "Hatrio mun sigra",                         "", 0 },
                new object[] { 436, 2019, "Estonia",                "Victor Crone",                          "Storm",                                    "", 0 },
                new object[] { 435, 2019, "Portugal",               "Conan Osiris",                          "TelemOveis",                               "", 0 },
                new object[] { 434, 2019, "Greece",                 "Katerine Duska",                        "Better Love",                              "", 0 },
                new object[] { 433, 2019, "San Marino",             "Serhat",                                "Say Na Na Na",                             "", 0 },
                new object[] { 432, 2019, "Armenia",                "Srbuk",                                 "Walking Out",                              "", 0 },
                new object[] { 431, 2019, "Ireland",                "Sarah McTernan",                        "22",                                       "", 0 },
                new object[] { 430, 2019, "Moldova",                "Anna Odobescu",                         "Stay",                                     "", 0 },
                new object[] { 429, 2019, "Switzerland",            "Luca Hanni",                            "She Got Me",                               "", 0 },
                new object[] { 428, 2019, "Latvia",                 "Carousel",                              "That Night",                               "", 0 },
                new object[] { 427, 2019, "Romania",                "Ester Peony",                           "On a Sunday",                              "", 0 },
                new object[] { 426, 2019, "Denmark",                "Leonora",                               "Love Is Forever",                          "", 0 },
                new object[] { 425, 2019, "Sweden",                 "John Lundvik",                          "Too Late for Love",                        "", 0 },
                new object[] { 424, 2019, "Austria",                "PAENDA",                                "Limits",                                   "", 0 },
                new object[] { 423, 2019, "Croatia",                "Roko",                                  "The Dream",                                "", 0 },
                new object[] { 422, 2019, "Malta",                  "Michela",                               "Chameleon",                                "", 0 },
                new object[] { 421, 2019, "Lithuania",              "Jurij Veklenko",                        "Run with the Lions",                       "", 0 },
                new object[] { 420, 2019, "Russia",                 "Sergey Lazarev",                        "Scream",                                   "", 0 },
                new object[] { 419, 2019, "Albania",                "Jonida Maliqi",                         "Ktheju tokes",                             "", 0 },
                new object[] { 418, 2019, "Norway",                 "KEiiNO",                                "Spirit in the Sky",                        "", 0 },
                new object[] { 417, 2019, "Netherlands",            "Duncan Laurence",                       "Arcade",                                   "", 0 },
                new object[] { 416, 2019, "North Macedonia",        "Tamara Todevska",                       "Proud",                                    "", 0 },
                new object[] { 415, 2019, "Azerbaijan",             "Chingiz",                               "Truth",                                    "", 0 },
                new object[] { 414, 2019, "Germany",                "S!sters",                               "Sister",                                   "", 0 },
                new object[] { 413, 2019, "Israel",                 "Kobi Marimi",                           "Home",                                     "", 0 },
                new object[] { 412, 2019, "United Kingdom",         "Michael Rice",                          "Bigger than Us",                           "", 0 },
                new object[] { 411, 2019, "France",                 "Bilal Hassani",                         "Roi",                                      "", 0 },
                new object[] { 410, 2019, "Italy",                  "Mahmood",                               "Soldi",                                    "", 0 },
                new object[] { 409, 2019, "Spain",                  "Miki",                                  "La Venda",                                 "", 0 },
                new object[] { 408, 2018, "Azerbaijan",             "Aisel",                                 "X My Heart",                               "", 0 },
                new object[] { 407, 2018, "Iceland",                "Ari Olafsson",                          "Our Choice",                               "", 0 },
                new object[] { 406, 2018, "Albania",                "Eugent Bushpepa",                       "Mall",                                     "", 0 },
                new object[] { 405, 2018, "Belgium",                "Sennek",                                "A Matter of Time",                         "", 0 },
                new object[] { 404, 2018, "Czech Republic",         "Mikolas Josef",                         "Lie to Me",                                "", 0 },
                new object[] { 403, 2018, "Lithuania",              "Ieva Zasimauskaite",                    "When We're Old",                           "", 0 },
                new object[] { 402, 2018, "Israel",                 "Netta",                                 "Toy",                                      "", 0 },
                new object[] { 401, 2018, "Belarus",                "Alekseev",                              "Forever",                                  "", 0 },
                new object[] { 400, 2018, "Estonia",                "Elina Nechayeva",                       "La forza",                                 "", 0 },
                new object[] { 399, 2018, "Bulgaria",               "Equinox",                               "Bones",                                    "", 0 },
                new object[] { 398, 2018, "North Macedonia",        "Eye Cue",                               "Lost and Found",                           "", 0 },
                new object[] { 397, 2018, "Croatia",                "Franka",                                "Crazy",                                    "", 0 },
                new object[] { 396, 2018, "Austria",                "Cesar Sampson",                         "Nobody but You",                           "", 0 },
                new object[] { 395, 2018, "Greece",                 "Yianna Terzi",                          "Oniro mou",                                "", 0 },
                new object[] { 394, 2018, "Finland",                "Saara Aalto",                           "Monsters",                                 "", 0 },
                new object[] { 393, 2018, "Armenia",                "Sevak Khanagyan",                       "Qami",                                     "", 0 },
                new object[] { 392, 2018, "Switzerland",            "ZiBBZ",                                 "Stones",                                   "", 0 },
                new object[] { 391, 2018, "Ireland",                "Ryan O'Shaughnessy",                    "Together",                                 "", 0 },
                new object[] { 390, 2018, "Cyprus",                 "Eleni Foureira",                        "Fuego",                                    "", 0 },
                new object[] { 389, 2018, "Norway",                 "Alexander Rybak",                       "That's How You Write a Song",              "", 0 },
                new object[] { 388, 2018, "Romania",                "The Humans",                            "Goodbye",                                  "", 0 },
                new object[] { 387, 2018, "Serbia",                 "Sanja Ilic & Balkanika",                "Nova deca",                                "", 0 },
                new object[] { 386, 2018, "San Marino",             "Jessika feat. Jenifer Brening",         "Who We Are",                               "", 0 },
                new object[] { 385, 2018, "Denmark",                "Rasmussen",                             "Higher Ground",                            "", 0 },
                new object[] { 384, 2018, "Russia",                 "Julia Samoylova",                       "I Won't Break",                            "", 0 },
                new object[] { 383, 2018, "Moldova",                "DoReDoS",                               "My Lucky Day",                             "", 0 },
                new object[] { 382, 2018, "Netherlands",            "Waylon",                                "Outlaw in 'Em",                            "", 0 },
                new object[] { 381, 2018, "Australia",              "Jessica Mauboy",                        "We Got Love",                              "", 0 },
                new object[] { 380, 2018, "Georgia",                "Ethno-Jazz Band Iriao",                 "For You",                                  "", 0 },
                new object[] { 379, 2018, "Poland",                 "Gromee feat. Lukas Meijer",             "Light Me Up",                              "", 0 },
                new object[] { 378, 2018, "Malta",                  "Christabelle",                          "Taboo",                                    "", 0 },
                new object[] { 377, 2018, "Hungary",                "AWS",                                   "Viszlat nyar",                             "", 0 },
                new object[] { 376, 2018, "Latvia",                 "Laura Rizzotto",                        "Funny Girl",                               "", 0 },
                new object[] { 375, 2018, "Sweden",                 "Benjamin Ingrosso",                     "Dance You Off",                            "", 0 },
                new object[] { 374, 2018, "Montenegro",             "Vanja Radovanovic",                     "Inje",                                     "", 0 },
                new object[] { 373, 2018, "Slovenia",               "Lea Sirk",                              "Hvala, ne!",                               "", 0 },
                new object[] { 372, 2018, "Ukraine",                "Melovin",                               "Under the Ladder",                         "", 0 },
                new object[] { 371, 2018, "Portugal",               "Claudia Pascoal",                       "O jardim",                                 "", 0 },
                new object[] { 370, 2018, "United Kingdom",         "SuRie",                                 "Storm",                                    "", 0 },
                new object[] { 369, 2018, "Germany",                "Michael Schulte",                       "You Let Me Walk Alone",                    "", 0 },
                new object[] { 368, 2018, "France",                 "Madame Monsieur",                       "Mercy",                                    "", 0 },
                new object[] { 367, 2018, "Italy",                  "Ermal Meta & Fabrizio Moro",            "Non mi avete fatto niente",                "", 0 },
                new object[] { 366, 2018, "Spain",                  "Amaia & Alfred",                        "Tu canciOn",                               "", 0 },
                new object[] { 365, 2017, "Sweden",                 "Robin Bengtsson",                       "I Can't Go On",                            "", 0 },
                new object[] { 364, 2017, "Georgia",                "Tamara Gachechiladze",                  "Keep the Faith",                           "", 0 },
                new object[] { 363, 2017, "Australia",              "Isaiah",                                "Don't Come Easy",                          "", 0 },
                new object[] { 362, 2017, "Albania",                "Lindita",                               "World",                                    "", 0 },
                new object[] { 361, 2017, "Belgium",                "Blanche",                               "City Lights",                              "", 0 },
                new object[] { 360, 2017, "Montenegro",             "Slavko Kalezic",                        "Space",                                    "", 0 },
                new object[] { 359, 2017, "Finland",                "Norma John",                            "Blackbird",                                "", 0 },
                new object[] { 358, 2017, "Azerbaijan",             "Dihaj",                                 "Skeletons",                                "", 0 },
                new object[] { 357, 2017, "Portugal",               "Salvador Sobral",                       "Amar pelos dois",                          "", 0 },
                new object[] { 356, 2017, "Greece",                 "Demy",                                  "This Is Love",                             "", 0 },
                new object[] { 355, 2017, "Poland",                 "Kasia Mos",                             "Flashlight",                               "", 0 },
                new object[] { 354, 2017, "Moldova",                "Sunstroke Project",                     "Hey, Mamma!",                              "", 0 },
                new object[] { 353, 2017, "Iceland",                "Svala",                                 "Paper",                                    "", 0 },
                new object[] { 352, 2017, "Czech Republic",         "Martina Barta",                         "My Turn",                                  "", 0 },
                new object[] { 351, 2017, "Cyprus",                 "Hovig",                                 "Gravity",                                  "", 0 },
                new object[] { 350, 2017, "Armenia",                "Artsvik",                               "Fly with Me",                              "", 0 },
                new object[] { 349, 2017, "Slovenia",               "Omar Naber",                            "On My Way",                                "", 0 },
                new object[] { 348, 2017, "Latvia",                 "Triana Park",                           "Line",                                     "", 0 },
                new object[] { 347, 2017, "Serbia",                 "Tijana Bogicevic",                      "In Too Deep",                              "", 0 },
                new object[] { 346, 2017, "Austria",                "Nathan Trent",                          "Running on Air",                           "", 0 },
                new object[] { 345, 2017, "North Macedonia",        "Jana Burceska",                         "Dance Alone",                              "", 0 },
                new object[] { 344, 2017, "Malta",                  "Claudia Faniello",                      "Breathlessly",                             "", 0 },
                new object[] { 343, 2017, "Romania",                "Ilinca ft. Alex Florea",                "Yodel It!",                                "", 0 },
                new object[] { 342, 2017, "Netherlands",            "O'G3NE",                                "Lights and Shadows",                       "", 0 },
                new object[] { 341, 2017, "Hungary",                "Joci Papai",                            "Origo",                                    "", 0 },
                new object[] { 340, 2017, "Denmark",                "Anja",                                  "Where I Am",                               "", 0 },
                new object[] { 339, 2017, "Ireland",                "Brendan Murray",                        "Dying to Try",                             "", 0 },
                new object[] { 338, 2017, "San Marino",             "Valentina Monetta and Jimmie Wilson",   "Spirit of the Night",                      "", 0 },
                new object[] { 337, 2017, "Croatia",                "Jacques Houdek",                        "My Friend",                                "", 0 },
                new object[] { 336, 2017, "Norway",                 "JOWST",                                 "Grab the Moment",                          "", 0 },
                new object[] { 335, 2017, "Switzerland",            "Timebelle",                             "Apollo",                                   "", 0 },
                new object[] { 334, 2017, "Belarus",                "Naviband",                              "Story of My Life",                         "", 0 },
                new object[] { 333, 2017, "Bulgaria",               "Kristian Kostov",                       "Beautiful Mess",                           "", 0 },
                new object[] { 332, 2017, "Lithuania",              "Fusedmarc",                             "Rain of Revolution",                       "", 0 },
                new object[] { 331, 2017, "Estonia",                "Koit Toome and Laura",                  "Verona",                                   "", 0 },
                new object[] { 330, 2017, "Israel",                 "IMRI",                                  "I Feel Alive",                             "", 0 },
                new object[] { 329, 2017, "Italy",                  "Francesco Gabbani",                     "Occidentali's Karma",                      "", 0 },
                new object[] { 328, 2017, "Spain",                  "Manel Navarro",                         "Do It for Your Lover",                     "", 0 },
                new object[] { 327, 2017, "United Kingdom",         "Lucie Jones",                           "Never Give Up on You",                     "", 0 },
                new object[] { 326, 2017, "Germany",                "Levina",                                "Perfect Life",                             "", 0 },
                new object[] { 325, 2017, "Ukraine",                "O.Torvald",                             "Time",                                     "", 0 },
                new object[] { 324, 2017, "France",                 "Alma",                                  "Requiem",                                  "", 0 },
                new object[] { 323, 2016, "Finland",                "Sandhja",                               "Sing It Away",                             "", 0 },
                new object[] { 322, 2016, "Greece",                 "Argo",                                  "Utopian Land",                             "", 0 },
                new object[] { 321, 2016, "Moldova",                "Lidia Isac",                            "Falling Stars",                            "", 0 },
                new object[] { 320, 2016, "Hungary",                "Freddie",                               "Pioneer",                                  "", 0 },
                new object[] { 319, 2016, "Croatia",                "Nina Kraljic",                          "Lighthouse",                               "", 0 },
                new object[] { 318, 2016, "Netherlands",            "Douwe Bob",                             "Slow Down",                                "", 0 },
                new object[] { 317, 2016, "Armenia",                "Iveta Mukuchyan",                       "LoveWave",                                 "", 0 },
                new object[] { 316, 2016, "San Marino",             "Serhat",                                "I Didn't Know",                            "", 0 },
                new object[] { 315, 2016, "Russia",                 "Sergey Lazarev",                        "You Are the Only One",                     "", 0 },
                new object[] { 314, 2016, "Czech Republic",         "Gabriela Guncikova",                    "I Stand",                                  "", 0 },
                new object[] { 313, 2016, "Cyprus",                 "Minus One",                             "Alter Ego",                                "", 0 },
                new object[] { 312, 2016, "Austria",                "Zoe",                                   "Loin d'ici",                               "", 0 },
                new object[] { 311, 2016, "Estonia",                "Juri Pootsmann",                        "Play",                                     "", 0 },
                new object[] { 310, 2016, "Azerbaijan",             "Samra",                                 "Miracle",                                  "", 0 },
                new object[] { 309, 2016, "Montenegro",             "Highway",                               "The Real Thing",                           "", 0 },
                new object[] { 308, 2016, "Iceland",                "Greta SalOme",                          "Hear Them Calling",                        "", 0 },
                new object[] { 307, 2016, "Bosnia and Herzegovina", "Dalal & Deen feat Ana Rucner and Jala", "Ljubav je",                                "", 0 },
                new object[] { 306, 2016, "Malta",                  "Ira Losco",                             "Walk on Water",                            "", 0 },
                new object[] { 305, 2016, "Latvia",                 "Justs",                                 "Heartbeat",                                "", 0 },
                new object[] { 304, 2016, "Poland",                 "Michal Szpak",                          "Color of Your Life",                       "", 0 },
                new object[] { 303, 2016, "Switzerland",            "Rykka",                                 "The Last of Our Kind",                     "", 0 },
                new object[] { 302, 2016, "Israel",                 "Hovi Star",                             "Made of Stars",                            "", 0 },
                new object[] { 301, 2016, "Belarus",                "Ivan",                                  "Help You Fly",                             "", 0 },
                new object[] { 300, 2016, "Serbia",                 "Sanja Vucic ZAA",                       "Goodbye (Shelter)",                        "", 0 },
                new object[] { 299, 2016, "Ireland",                "Nicky Byrne",                           "Sunlight",                                 "", 0 },
                new object[] { 298, 2016, "North Macedonia",        "Kaliopi",                               "Dona",                                     "", 0 },
                new object[] { 297, 2016, "Lithuania",              "Donny Montell",                         "I've Been Waiting for This Night",         "", 0 },
                new object[] { 296, 2016, "Australia",              "Dami Im",                               "Sound of Silence",                         "", 0 },
                new object[] { 295, 2016, "Slovenia",               "ManuElla",                              "Blue and Red",                             "", 0 },
                new object[] { 294, 2016, "Bulgaria",               "Poli Genova",                           "If Love Was a Crime",                      "", 0 },
                new object[] { 293, 2016, "Denmark",                "Lighthouse X",                          "Soldiers of Love",                         "", 0 },
                new object[] { 292, 2016, "Ukraine",                "Jamala",                                "1944",                                     "", 0 },
                new object[] { 291, 2016, "Norway",                 "Agnete",                                "Icebreaker",                               "", 0 },
                new object[] { 290, 2016, "Georgia",                "Nika Kocharov & Young Georgian Lolitaz","Midnight Gold",                            "", 0 },
                new object[] { 289, 2016, "Albania",                "Eneda Tarifa",                          "Fairytale",                                "", 0 },
                new object[] { 288, 2016, "Belgium",                "Laura Tesoro",                          "What's the Pressure",                      "", 0 },
                new object[] { 287, 2016, "Italy",                  "Francesca Michielin",                   "No Degree of Separation",                  "", 0 },
                new object[] { 286, 2016, "Sweden",                 "Frans",                                 "If I Were Sorry",                          "", 0 },
                new object[] { 285, 2016, "Germany",                "Jamie-Lee",                             "Ghost",                                    "", 0 },
                new object[] { 284, 2016, "France",                 "Amir",                                  "J'ai cherche",                             "", 0 },
                new object[] { 283, 2016, "Spain",                  "Barei",                                 "Say Yay!",                                 "", 0 },
                new object[] { 282, 2016, "United Kingdom",         "Joe and Jake",                          "You're Not Alone",                         "", 0 },
                new object[] { 281, 2015, "Moldova",                "Eduard Romanyuta",                      "I Want Your Love",                         "", 0 },
                new object[] { 280, 2015, "Armenia",                "Genealogy",                             "Face the Shadow",                          "", 0 },
                new object[] { 279, 2015, "Belgium",                "Loic Nottet",                           "Rhythm Inside",                            "", 0 },
                new object[] { 278, 2015, "Netherlands",            "Trijntje Oosterhuis",                   "Walk Along",                               "", 0 },
                new object[] { 277, 2015, "Finland",                "Pertti Kurikan Nimipaivat",             "Aina mun pitaa",                           "", 0 },
                new object[] { 276, 2015, "Greece",                 "Maria Elena Kyriakou",                  "One Last Breath",                          "", 0 },
                new object[] { 275, 2015, "Estonia",                "Elina Born & Stig Rasta",               "Goodbye to Yesterday",                     "", 0 },
                new object[] { 274, 2015, "North Macedonia",        "Daniel Kajmakoski",                     "Autumn Leaves",                            "", 0 },
                new object[] { 273, 2015, "Serbia",                 "Bojana Stamenov",                       "Beauty Never Lies",                        "", 0 },
                new object[] { 272, 2015, "Hungary",                "Boggie",                                "Wars for Nothing",                         "", 0 },
                new object[] { 271, 2015, "Belarus",                "Uzari & Maimuna",                       "Time",                                     "", 0 },
                new object[] { 270, 2015, "Russia",                 "Polina Gagarina",                       "A Million Voices",                         "", 0 },
                new object[] { 269, 2015, "Denmark",                "Anti Social Media",                     "The Way You Are",                          "", 0 },
                new object[] { 268, 2015, "Albania",                "Elhaida Dani",                          "I'm Alive",                                "", 0 },
                new object[] { 267, 2015, "Romania",                "Voltaj",                                "De la capat",                              "", 0 },
                new object[] { 266, 2015, "Georgia",                "Nina Sublatti",                         "Warrior",                                  "", 0 },
                new object[] { 265, 2015, "Lithuania",              "Monika Linkyte & Vaidas Baumila",       "This Time",                                "", 0 },
                new object[] { 264, 2015, "Ireland",                "Molly Sterling",                        "Playing with Numbers",                     "", 0 },
                new object[] { 263, 2015, "San Marino",             "Anita Simoncini & Michele Perniola",    "Chain of Lights",                          "", 0 },
                new object[] { 262, 2015, "Montenegro",             "Knez",                                  "Adio",                                     "", 0 },
                new object[] { 261, 2015, "Malta",                  "Amber",                                 "Warrior",                                  "", 0 },
                new object[] { 260, 2015, "Norway",                 "Morland & Debrah Scarlett",             "A Monster Like Me",                        "", 0 },
                new object[] { 259, 2015, "Portugal",               "Leonor Andrade",                        "Ha um mar que nos separa",                 "", 0 },
                new object[] { 258, 2015, "Czech Republic",         "Marta Jandova & Vaclav Noid Barta",     "Hope Never Dies",                          "", 0 },
                new object[] { 257, 2015, "Israel",                 "Nadav Guedj",                           "Golden Boy",                               "", 0 },
                new object[] { 256, 2015, "Latvia",                 "Aminata",                               "Love Injected",                            "", 0 },
                new object[] { 255, 2015, "Azerbaijan",             "Elnur Huseynov",                        "Hour of the Wolf",                         "", 0 },
                new object[] { 254, 2015, "Iceland",                "Maria Olafs",                           "Unbroken",                                 "", 0 },
                new object[] { 253, 2015, "Sweden",                 "Mans Zelmerlow",                        "Heroes",                                   "", 0 },
                new object[] { 252, 2015, "Switzerland",            "Melanie Rene",                          "Time to Shine",                            "", 0 },
                new object[] { 251, 2015, "Cyprus",                 "John Karayiannis",                      "One Thing I Should Have Done",             "", 0 },
                new object[] { 250, 2015, "Slovenia",               "Maraaya",                               "Here for You",                             "", 0 },
                new object[] { 249, 2015, "Poland",                 "Monika Kuszynska",                      "In the Name of Love",                      "", 0 },
                new object[] { 248, 2015, "France",                 "Lisa Angell",                           "N'oubliez pas",                            "", 0 },
                new object[] { 247, 2015, "United Kingdom",         "Electro Velvet",                        "Still in Love with You",                   "", 0 },
                new object[] { 246, 2015, "Austria",                "The Makemakes",                         "I Am Yours",                               "", 0 },
                new object[] { 245, 2015, "Germany",                "Ann Sophie",                            "Black Smoke",                              "", 0 },
                new object[] { 244, 2015, "Spain",                  "Edurne",                                "Amanecer",                                 "", 0 },
                new object[] { 243, 2015, "Italy",                  "Il Volo",                               "Grande amore",                             "", 0 },
                new object[] { 242, 2014, "Armenia",                "Aram MP3",                              "Not Alone",                                "", 0 },
                new object[] { 241, 2014, "Latvia",                 "Aarzemnieki",                           "Cake to Bake",                             "", 0 },
                new object[] { 240, 2014, "Estonia",                "Tanja",                                 "Amazing",                                  "", 0 },
                new object[] { 239, 2014, "Sweden",                 "Sanna Nielsen",                         "Undo",                                     "", 0 },
                new object[] { 238, 2014, "Iceland",                "Pollaponk",                             "No Prejudice",                             "", 0 },
                new object[] { 237, 2014, "Albania",                "Hersi",                                 "One Night's Anger",                        "", 0 },
                new object[] { 236, 2014, "Russia",                 "Tolmachevy Sisters",                    "Shine",                                    "", 0 },
                new object[] { 235, 2014, "Azerbaijan",             "Dilara Kazimova",                       "Start a Fire",                             "", 0 },
                new object[] { 234, 2014, "Ukraine",                "Mariya Yaremchuk",                      "Tick-Tock",                                "", 0 },
                new object[] { 233, 2014, "Belgium",                "Axel Hirsoux",                          "Mother",                                   "", 0 },
                new object[] { 232, 2014, "Moldova",                "Cristina Scarlat",                      "Wild Soul",                                "", 0 },
                new object[] { 231, 2014, "San Marino",             "Valentina Monetta",                     "Maybe",                                    "", 0 },
                new object[] { 230, 2014, "Portugal",               "Suzy",                                  "Quero ser tua",                            "", 0 },
                new object[] { 229, 2014, "Netherlands",            "The Common Linnets",                    "Calm After the Storm",                     "", 0 },
                new object[] { 228, 2014, "Montenegro",             "Sergej cetkovic",                       "Moj svijet",                               "", 0 },
                new object[] { 227, 2014, "Hungary",                "Andras Kallay-Saunders",                "Running",                                  "", 0 },
                new object[] { 226, 2014, "Malta",                  "Firelight",                             "Coming Home",                              "", 0 },
                new object[] { 225, 2014, "Israel",                 "Mei Finegold",                          "Same Heart",                               "", 0 },
                new object[] { 224, 2014, "Norway",                 "Carl Espen",                            "Silent Storm",                             "", 0 },
                new object[] { 223, 2014, "Georgia",                "The Shin and Mariko",                   "Three Minutes to Earth",                   "", 0 },
                new object[] { 222, 2014, "Poland",                 "Donatan & Cleo",                        "My Slowianie   We Are Slavic",             "", 0 },
                new object[] { 221, 2014, "Austria",                "Conchita Wurst",                        "Rise Like a Phoenix",                      "", 0 },
                new object[] { 220, 2014, "Lithuania",              "Vilija",                                "Attention",                                "", 0 },
                new object[] { 219, 2014, "Finland",                "Softengine",                            "Something Better",                         "", 0 },
                new object[] { 218, 2014, "Ireland",                "Can-Linn feat. Kasey Smith",            "Heartbeat",                                "", 0 },
                new object[] { 217, 2014, "Belarus",                "Teo",                                   "Cheesecake",                               "", 0 },
                new object[] { 216, 2014, "North Macedonia",        "Tijana",                                "To the Sky",                               "", 0 },
                new object[] { 215, 2014, "Switzerland",            "Sebalter",                              "Hunter of Stars",                          "", 0 },
                new object[] { 214, 2014, "Greece",                 "Freaky Fortune feat. RiskyKidd",        "Rise Up",                                  "", 0 },
                new object[] { 213, 2014, "Slovenia",               "Tinkara Kovac",                         "Round and Round",                          "", 0 },
                new object[] { 212, 2014, "Romania",                "Paula Seling & Ovi",                    "Miracle",                                  "", 0 },
                new object[] { 211, 2014, "Germany",                "Elaiza",                                "Is It Right",                              "", 0 },
                new object[] { 210, 2014, "France",                 "TWIN TWIN",                             "Moustache",                                "", 0 },
                new object[] { 209, 2014, "Italy",                  "Emma",                                  "La mia citta",                             "", 0 },
                new object[] { 208, 2014, "Spain",                  "Ruth Lorenzo",                          "Dancing in the Rain",                      "", 0 },
                new object[] { 207, 2014, "Denmark",                "Basim",                                 "Cliche Love Song",                         "", 0 },
                new object[] { 206, 2014, "United Kingdom",         "Molly",                                 "Children of the Universe",                 "", 0 },
                new object[] { 205, 2013, "Austria",                "Natalia Kelly",                         "Shine",                                    "", 0 },
                new object[] { 204, 2013, "Estonia",                "Birgit",                                "Et uus saaks alguse",                      "", 0 },
                new object[] { 203, 2013, "Slovenia",               "Hannah",                                "Straight Into Love",                       "", 0 },
                new object[] { 202, 2013, "Croatia",                "Klapa s Mora",                          "Mizerja",                                  "", 0 },
                new object[] { 201, 2013, "Denmark",                "Emmelie de Forest",                     "Only Teardrops",                           "", 0 },
                new object[] { 200, 2013, "Russia",                 "Dina Garipova",                         "What If",                                  "", 0 },
                new object[] { 199, 2013, "Ukraine",                "Zlata Ognevich",                        "Gravity",                                  "", 0 },
                new object[] { 198, 2013, "Netherlands",            "Anouk",                                 "Birds",                                    "", 0 },
                new object[] { 197, 2013, "Montenegro",             "Who See",                               "Igranka",                                  "", 0 },
                new object[] { 196, 2013, "Lithuania",              "Andrius Pojavis",                       "Something",                                "", 0 },
                new object[] { 195, 2013, "Belarus",                "Alyona Lanskaya",                       "Solayoh",                                  "", 0 },
                new object[] { 194, 2013, "Moldova",                "Aliona Moon",                           "O mie",                                    "", 0 },
                new object[] { 193, 2013, "Ireland",                "Ryan Dolan",                            "Only Love Survives",                       "", 0 },
                new object[] { 192, 2013, "Cyprus",                 "Despina Olympiou",                      "An me thimasai",                           "", 0 },
                new object[] { 191, 2013, "Belgium",                "Roberto Bellarosa",                     "Love Kills",                               "", 0 },
                new object[] { 190, 2013, "Serbia",                 "Moje 3",                                "Ljubav je svuda",                          "", 0 },
                new object[] { 189, 2013, "Latvia",                 "PeR",                                   "Here We Go",                               "", 0 },
                new object[] { 188, 2013, "San Marino",             "Valentina Monetta",                     "Crisalide (Vola)",                         "", 0 },
                new object[] { 187, 2013, "North Macedonia",        "Esma & Lozano",                         "Pred da se razdeni",                       "", 0 },
                new object[] { 186, 2013, "Azerbaijan",             "Farid Mammadov",                        "Hold Me",                                  "", 0 },
                new object[] { 185, 2013, "Finland",                "Krista Siegfrids",                      "Marry Me",                                 "", 0 },
                new object[] { 184, 2013, "Malta",                  "Gianluca",                              "Tomorrow",                                 "", 0 },
                new object[] { 183, 2013, "Bulgaria",               "Elitsa Todorova & Stoyan Yankoulov",    "Samo shampioni",                           "", 0 },
                new object[] { 182, 2013, "Iceland",                "Eythor Ingi",                           "Eg a lif",                                 "", 0 },
                new object[] { 181, 2013, "Greece",                 "Koza Mostra feat. Agathon Iakovidis",   "Alcohol Is Free",                          "", 0 },
                new object[] { 180, 2013, "Israel",                 "Moran Mazor",                           "Rak Bishvilo",                             "", 0 },
                new object[] { 179, 2013, "Armenia",                "Dorians",                               "Lonely Planet",                            "", 0 },
                new object[] { 178, 2013, "Hungary",                "ByeAlex",                               "Kedvesem (Zoohacker Remix)",               "", 0 },
                new object[] { 177, 2013, "Norway",                 "Margaret Berger",                       "I Feed You My Love",                       "", 0 },
                new object[] { 176, 2013, "Albania",                "Adrian Lulgjuraj & Bledar Sejko",       "Identitet",                                "", 0 },
                new object[] { 175, 2013, "Georgia",                "Nodi Tatishvili & Sophie Gelovani",     "Waterfall",                                "", 0 },
                new object[] { 174, 2013, "Switzerland",            "Takasa",                                "You and Me",                               "", 0 },
                new object[] { 173, 2013, "Romania",                "Cezar",                                 "It's My Life",                             "", 0 },
                new object[] { 172, 2013, "France",                 "Amandine Bourgeois",                    "L'enfer et moi",                           "", 0 },
                new object[] { 171, 2013, "Spain",                  "ESDM",                                  "Contigo hasta el final",                   "", 0 },
                new object[] { 170, 2013, "Germany",                "Cascada",                               "Glorious",                                 "", 0 },
                new object[] { 169, 2013, "United Kingdom",         "Bonnie Tyler",                          "Believe in Me",                            "", 0 },
                new object[] { 168, 2013, "Sweden",                 "Robin Stjernberg",                      "You",                                      "", 0 },
                new object[] { 167, 2013, "Italy",                  "Marco Mengoni",                         "L'essenziale",                             "", 0 },
                new object[] { 166, 2012, "Montenegro",             "Rambo Amadeus",                         "Euro Neuro",                               "", 0 },
                new object[] { 165, 2012, "Iceland",                "Greta Salome and Jonsi",                "Never Forget",                             "", 0 },
                new object[] { 164, 2012, "Greece",                 "Eleftheria Eleftheriou",                "Aphrodisiac",                              "", 0 },
                new object[] { 163, 2012, "Latvia",                 "Anmary",                                "Beautiful Song",                           "", 0 },
                new object[] { 162, 2012, "Albania",                "Rona Nishliu",                          "Suus3",                                    "", 0 },
                new object[] { 161, 2012, "Romania",                "Mandinga",                              "Zaleilah",                                 "", 0 },
                new object[] { 160, 2012, "Switzerland",            "Sinplus",                               "Unbreakable",                              "", 0 },
                new object[] { 159, 2012, "Belgium",                "Iris",                                  "Would You?",                               "", 0 },
                new object[] { 158, 2012, "Finland",                "Pernilla Karlsson",                     "Nar jag blundar",                          "", 0 },
                new object[] { 157, 2012, "Israel",                 "Izabo",                                 "Time",                                     "", 0 },
                new object[] { 156, 2012, "San Marino",             "Valentina Monetta",                     "The Social Network Song (Oh Oh-Uh-Oh Oh)", "", 0 },
                new object[] { 155, 2012, "Cyprus",                 "Ivi Adamou",                            "La La Love",                               "", 0 },
                new object[] { 154, 2012, "Denmark",                "Soluna Samay",                          "Should've Known Better",                   "", 0 },
                new object[] { 153, 2012, "Russia",                 "Buranovskiye Babushki",                 "Party for Everybody",                      "", 0 },
                new object[] { 152, 2012, "Hungary",                "Compact Disco",                         "Sound of Our Hearts",                      "", 0 },
                new object[] { 151, 2012, "Austria",                "Trackshittaz",                          "Woki mit deim Popo",                       "", 0 },
                new object[] { 150, 2012, "Moldova",                "Pasha Parfeny",                         "Lautar",                                   "", 0 },
                new object[] { 149, 2012, "Ireland",                "Jedward",                               "Waterline",                                "", 0 },
                new object[] { 148, 2012, "Serbia",                 "zeljko Joksimovic",                     "Nije ljubav stvar ",                       "", 0 },
                new object[] { 147, 2012, "North Macedonia",        "Kaliopi",                               "Crno i belo",                              "", 0 },
                new object[] { 146, 2012, "Netherlands",            "Joan Franka",                           "You and Me",                               "", 0 },
                new object[] { 145, 2012, "Malta",                  "Kurt Calleja",                          "This Is the Night",                        "", 0 },
                new object[] { 144, 2012, "Belarus",                "Litesound",                             "We Are the Heroes",                        "", 0 },
                new object[] { 143, 2012, "Portugal",               "Filipa Sousa",                          "Vida minha",                               "", 0 },
                new object[] { 142, 2012, "Ukraine",                "Gaitana",                               "Be My Guest",                              "", 0 },
                new object[] { 141, 2012, "Bulgaria",               "Sofi Marinova",                         "Love Unlimited",                           "", 0 },
                new object[] { 140, 2012, "Slovenia",               "Eva Boto",                              "Verjamem",                                 "", 0 },
                new object[] { 139, 2012, "Croatia",                "Nina Badric",                           "Nebo",                                     "", 0 },
                new object[] { 138, 2012, "Sweden",                 "Loreen",                                "Euphoria",                                 "", 0 },
                new object[] { 137, 2012, "Georgia",                "Anri Jokhadze",                         "I'm a Joker",                              "", 0 },
                new object[] { 136, 2012, "Turkey",                 "Can Bonomo",                            "Love Me Back",                             "", 0 },
                new object[] { 135, 2012, "Estonia",                "Ott Lepland",                           "Kuula",                                    "", 0 },
                new object[] { 134, 2012, "Slovakia",               "Max Jason Mai",                         "Don't Close Your Eyes",                    "", 0 },
                new object[] { 133, 2012, "Norway",                 "Tooji",                                 "Stay",                                     "", 0 },
                new object[] { 132, 2012, "Bosnia and Herzegovina", "Maya Sar",                              "Korake ti znam",                           "", 0 },
                new object[] { 131, 2012, "Lithuania",              "Donny Montell",                         "Love Is Blind",                            "", 0 },
                new object[] { 130, 2012, "United Kingdom",         "Engelbert Humperdinck",                 "Love Will Set You Free",                   "", 0 },
                new object[] { 129, 2012, "France",                 "Anggun",                                "Echo (You and I)",                         "", 0 },
                new object[] { 128, 2012, "Italy",                  "Nina Zilli",                            "L'amore e femmina (Out of Love)",          "", 0 },
                new object[] { 127, 2012, "Azerbaijan",             "Sabina Babayeva",                       "When the Music Dies",                      "", 0 },
                new object[] { 126, 2012, "Spain",                  "Pastora Soler",                         "Quedate conmigo (Stay With Me)",           "", 0 },
                new object[] { 125, 2012, "Germany",                "Roman Lob",                             "Standing Still",                           "", 0 },
                new object[] { 124, 2011, "Poland",                 "Magdalena Tul",                         "Jestem",                                   "", 0 },
                new object[] { 123, 2011, "Norway",                 "Stella Mwangi",                         "Haba Haba",                                "", 0 },
                new object[] { 122, 2011, "Albania",                "Aurela Ga e",                           "Feel the Passion",                         "", 0 },
                new object[] { 121, 2011, "Armenia",                "Emmy",                                  "Boom Boom",                                "", 0 },
                new object[] { 120, 2011, "Turkey",                 "Yuksek Sadakat",                        "Live It Up",                               "", 0 },
                new object[] { 119, 2011, "Serbia",                 "Nina",                                  "Caroban",                                  "", 0 },
                new object[] { 118, 2011, "Russia",                 "Alexey Vorobyov",                       "Get You",                                  "", 0 },
                new object[] { 117, 2011, "Switzerland",            "Anna Rossinelli",                       "In Love for a While",                      "", 0 },
                new object[] { 116, 2011, "Georgia",                "Eldrine",                               "One More Day",                             "", 0 },
                new object[] { 115, 2011, "Finland",                "Paradise Oskar",                        "Da Da Dam",                                "", 0 },
                new object[] { 114, 2011, "Malta",                  "Glen Vella",                            "One Life",                                 "", 0 },
                new object[] { 113, 2011, "San Marino",             "Senit",                                 "Stand By",                                 "", 0 },
                new object[] { 112, 2011, "Croatia",                "Daria",                                 "Celebrate",                                "", 0 },
                new object[] { 111, 2011, "Iceland",                "Sjonni's Friends",                      "Coming Home",                              "", 0 },
                new object[] { 110, 2011, "Hungary",                "Kati Wolf",                             "What About My Dreams?",                    "", 0 },
                new object[] { 109, 2011, "Portugal",               "Homens da Luta",                        "A luta e alegria",                         "", 0 },
                new object[] { 108, 2011, "Lithuania",              "Evelina Sasenko",                       "C'est ma vie",                             "", 0 },
                new object[] { 107, 2011, "Azerbaijan",             "Ell & Nikki",                           "Running Scared",                           "", 0 },
                new object[] { 106, 2011, "Greece",                 "Loukas Giorkas feat. Stereo Mike",      "Watch My Dance",                           "", 0 },
                new object[] { 105, 2011, "Bosnia and Herzegovina", "Dino Merlin",                           "Love in Rewind",                           "", 0 },
                new object[] { 104, 2011, "Austria",                "Nadine Beiler",                         "The Secret Is Love",                       "", 0 },
                new object[] { 103, 2011, "Netherlands",            "3JS",                                   "Never Alone",                              "", 0 },
                new object[] { 102, 2011, "Belgium",                "Witloof Bay",                           "With Love Baby",                           "", 0 },
                new object[] { 101, 2011, "Slovakia",               "TWiiNS",                                "I'm Still Alive",                          "", 0 },
                new object[] { 100, 2011, "Ukraine",                "Mika Newton",                           "Angel",                                    "", 0 },
                new object[] { 99,  2011, "Moldova",                "Zdob si Zdub",                          "So Lucky",                                 "", 0 },
                new object[] { 98,  2011, "Sweden",                 "Eric Saade",                            "Popular",                                  "", 0 },
                new object[] { 97,  2011, "Cyprus",                 "Christos Mylordos",                     "San aggelos s'agapisa",                    "", 0 },
                new object[] { 96,  2011, "Bulgaria",               "Poli Genova",                           "Na inat",                                  "", 0 },
                new object[] { 95,  2011, "North Macedonia",        "Vlatko Ilievski",                       "Rusinka",                                  "", 0 },
                new object[] { 94,  2011, "Israel",                 "Dana International",                    "Ding Dong",                                "", 0 },
                new object[] { 93,  2011, "Slovenia",               "Maja Keuc",                             "No One",                                   "", 0 },
                new object[] { 92,  2011, "Romania",                "Hotel FM",                              "Change",                                   "", 0 },
                new object[] { 91,  2011, "Estonia",                "Getter Jaani",                          "Rockefeller Street",                       "", 0 },
                new object[] { 90,  2011, "Belarus",                "Anastasia Vinnikova",                   "I Love Belarus",                           "", 0 },
                new object[] { 89,  2011, "Latvia",                 "Musiqq",                                "Angel in Disguise",                        "", 0 },
                new object[] { 88,  2011, "Denmark",                "A Friend in London",                    "New Tomorrow",                             "", 0 },
                new object[] { 87,  2011, "Ireland",                "Jedward",                               "Lipstick",                                 "", 0 },
                new object[] { 86,  2011, "France",                 "Amaury Vassili",                        "Sognu",                                    "", 0 },
                new object[] { 85,  2011, "Italy",                  "Raphael Gualazzi",                      "Madness of Love",                          "", 0 },
                new object[] { 84,  2011, "United Kingdom",         "Blue",                                  "I Can",                                    "", 0 },
                new object[] { 83,  2011, "Germany",                "Lena",                                  "Taken by a Stranger",                      "", 0 },
                new object[] { 82,  2011, "Spain",                  "Lucia Perez",                           "Que me quiten lo bailao",                  "", 0 },
                new object[] { 81,  2010, "Moldova",                "SunStroke Project and Olia Tira",       "Run Away",                                 "", 0 },
                new object[] { 80,  2010, "Russia",                 "Peter Nalitch and Friends",             "Lost and Forgotten",                       "", 0 },
                new object[] { 79,  2010, "Estonia",                "Malcolm Lincoln",                       "Siren",                                    "", 0 },
                new object[] { 78,  2010, "Slovakia",               "Kristina",                              "Horehronie",                               "", 0 },
                new object[] { 77,  2010, "Finland",                "Kuunkuiskaajat",                        "Tyolki ellaa",                             "", 0 },
                new object[] { 76,  2010, "Latvia",                 "Aisha",                                 "What For?",                                "", 0 },
                new object[] { 75,  2010, "Serbia",                 "Milan Stankovic",                       "Ovo je Balkan",                            "", 0 },
                new object[] { 74,  2010, "Bosnia and Herzegovina", "Vukasin Brajic",                        "Thunder and Lightning",                    "", 0 },
                new object[] { 73,  2010, "Poland",                 "Marcin Mrozinski",                      "Legenda",                                  "", 0 },
                new object[] { 72,  2010, "Belgium",                "Tom Dice",                              "Me and My Guitar",                         "", 0 },
                new object[] { 71,  2010, "Malta",                  "Thea Garrett",                          "My Dream",                                 "", 0 },
                new object[] { 70,  2010, "Albania",                "Juliana Pasha",                         "It's All About You",                       "", 0 },
                new object[] { 69,  2010, "Greece",                 "Giorgos Alkaios and Friends",           "OPA",                                      "", 0 },
                new object[] { 68,  2010, "Portugal",               "Filipa Azevedo",                        "Ha dias assim",                            "", 0 },
                new object[] { 67,  2010, "North Macedonia",        "Gjoko Taneski",                         "Jas ja imam silata",                       "", 0 },
                new object[] { 66,  2010, "Belarus",                "3+2 feat Robert Wells",                 "Butterflies",                              "", 0 },
                new object[] { 65,  2010, "Iceland",                "Hera Bjork",                            "Je ne sais quoi",                          "", 0 },
                new object[] { 64,  2010, "Lithuania",              "InCulto",                               "Eastern European Funk",                    "", 0 },
                new object[] { 63,  2010, "Armenia",                "Eva Rivas",                             "Apricot Stone",                            "", 0 },
                new object[] { 62,  2010, "Israel",                 "Harel Skaat",                           "Milim",                                    "", 0 },
                new object[] { 61,  2010, "Denmark",                "Chanee and N'evergreen",                "In a Moment Like This",                    "", 0 },
                new object[] { 60,  2010, "Switzerland",            "Michael von der Heide",                 "Il pleut de l'or",                         "", 0 },
                new object[] { 59,  2010, "Sweden",                 "Anna Bergendahl",                       "This Is My Life",                          "", 0 },
                new object[] { 58,  2010, "Azerbaijan",             "Safura",                                "Drip Drop",                                "", 0 },
                new object[] { 57,  2010, "Ukraine",                "Alyosha",                               "Sweet People",                             "", 0 },
                new object[] { 56,  2010, "Netherlands",            "Sieneke",                               "Ik ben verliefd",                          "", 0 },
                new object[] { 55,  2010, "Romania",                "Paula Seling and Ovi",                  "Playing with Fire",                        "", 0 },
                new object[] { 54,  2010, "Slovenia",               "Ansambel zlindra and Kalamari",         "Narodnozabavni rock",                      "", 0 },
                new object[] { 53,  2010, "Ireland",                "Niamh Kavanagh",                        "It's for You",                             "", 0 },
                new object[] { 52,  2010, "Bulgaria",               "Miro",                                  "Angel si ti",                              "", 0 },
                new object[] { 51,  2010, "Cyprus",                 "Jon Lilygreen and The Islanders",       "Life Looks Better in Spring",              "", 0 },
                new object[] { 50,  2010, "Croatia",                "Feminnem",                              "Lako je sve",                              "", 0 },
                new object[] { 49,  2010, "Georgia",                "Sofia Nizharadze",                      "Shine",                                    "", 0 },
                new object[] { 48,  2010, "Turkey",                 "maNga",                                 "We Could Be the Same",                     "", 0 },
                new object[] { 47,  2010, "Spain",                  "Daniel Diges",                          "Algo pequenito",                           "", 0 },
                new object[] { 46,  2010, "Norway",                 "Didrik Solli-Tangen",                   "My Heart Is Yours",                        "", 0 },
                new object[] { 45,  2010, "United Kingdom",         "Josh Dubovie",                          "That Sounds Good to Me",                   "", 0 },
                new object[] { 44,  2010, "France",                 "Jessy Matador",                         "Allez Ola Ole",                            "", 0 },
                new object[] { 43,  2010, "Germany",                "Lena",                                  "Satellite",                                "", 0 },
                new object[] { 42,  2009, "Montenegro",             "Andrea Demirovic",                      "Just Get Out of My Life",                  "", 0 },
                new object[] { 41,  2009, "Czech Republic",         "Gipsy.cz",                              "Aven Romale",                              "", 0 },
                new object[] { 40,  2009, "Belgium",                "Copycat",                               "Copycat",                                  "", 0 },
                new object[] { 39,  2009, "Belarus",                "Petr Elfimov",                          "Eyes That Never Lie",                      "", 0 },
                new object[] { 38,  2009, "Sweden",                 "Malena Ernman",                         "La voix",                                  "", 0 },
                new object[] { 37,  2009, "Armenia",                "Inga and Anush",                        "Jan Jan",                                  "", 0 },
                new object[] { 36,  2009, "Andorra",                "Susanne Georgi",                        "La teva decisio (Get a Life)",             "", 0 },
                new object[] { 35,  2009, "Switzerland",            "Lovebugs",                              "The Highest Heights",                      "", 0 },
                new object[] { 34,  2009, "Turkey",                 "Hadise",                                "Dum Tek Tek",                              "", 0 },
                new object[] { 33,  2009, "Israel",                 "Noa and Mira Awad",                     "There Must Be Another Way",                "", 0 },
                new object[] { 32,  2009, "Bulgaria",               "Krassimir Avramov",                     "Illusion",                                 "", 0 },
                new object[] { 31,  2009, "Iceland",                "Yohanna",                               "Is It True?",                              "", 0 },
                new object[] { 30,  2009, "North Macedonia",        "Next Time",                             "Nesto sto kje ostane",                     "", 0 },
                new object[] { 29,  2009, "Romania",                "Elena",                                 "The Balkan Girls",                         "", 0 },
                new object[] { 28,  2009, "Finland",                "Waldo's People",                        "Lose Control",                             "", 0 },
                new object[] { 27,  2009, "Portugal",               "Flor-de-Lis",                           "Todas as ruas do amor",                    "", 0 },
                new object[] { 26,  2009, "Malta",                  "Chiara",                                "What If We",                               "", 0 },
                new object[] { 25,  2009, "Bosnia and Herzegovina", "Regina",                                "Bistra voda",                              "", 0 },
                new object[] { 24,  2009, "Croatia",                "Igor Cukrov feat. Andrea",              "Lijepa Tena",                              "", 0 },
                new object[] { 23,  2009, "Ireland",                "Sinead Mulvey and Black Daisy",         "Et Cetera",                                "", 0 },
                new object[] { 22,  2009, "Latvia",                 "Intars Busulis",                        "Probka",                                   "", 0 },
                new object[] { 21,  2009, "Serbia",                 "Marko Kon and Milaan",                  "Cipela",                                   "", 0 },
                new object[] { 20,  2009, "Poland",                 "Lidia Kopania",                         "I Don't Wanna Leave",                      "", 0 },
                new object[] { 19,  2009, "Norway",                 "Alexander Rybak",                       "Fairytale",                                "", 0 },
                new object[] { 18,  2009, "Cyprus",                 "Christina Metaxa",                      "Firefly",                                  "", 0 },
                new object[] { 17,  2009, "Slovakia",               "Kamil Mikulcik and Nela Pociskova",     "Let tmou",                                 "", 0 },
                new object[] { 16,  2009, "Denmark",                "Niels Brinck",                          "Believe Again",                            "", 0 },
                new object[] { 15,  2009, "Slovenia",               "Quartissimo feat. Martina",             "Love Symphony",                            "", 0 },
                new object[] { 14,  2009, "Hungary",                "Zoli adok",                             "Dance with Me",                            "", 0 },
                new object[] { 13,  2009, "Azerbaijan",             "AySel and Arash",                       "Always",                                   "", 0 },
                new object[] { 12,  2009, "Greece",                 "Sakis Rouvas",                          "This Is Our Night",                        "", 0 },
                new object[] { 11,  2009, "Lithuania",              "Sasha Son",                             "Love",                                     "", 0 },
                new object[] { 10,  2009, "Moldova",                "Nelly Ciobanu",                         "Hora din Moldova",                         "", 0 },
                new object[] { 9,   2009, "Albania",                "Kejsi Tola",                            "Carry Me in Your Dreams",                  "", 0 },
                new object[] { 8,   2009, "Ukraine",                "Svetlana Loboda",                       "Be My Valentine! (Anti-Crisis Girl)",      "", 0 },
                new object[] { 7,   2009, "Estonia",                "Urban Symphony",                        "Randajad",                                 "", 0 },
                new object[] { 6,   2009, "Netherlands",            "The Toppers",                           "Shine",                                    "", 0 },
                new object[] { 5,   2009, "France",                 "Patricia Kaas",                         "Et s'il fallait le faire",                 "", 0 },
                new object[] { 4,   2009, "Russia",                 "Anastasiya Prikhodko",                  "Mamo",                                     "", 0 },
                new object[] { 3,   2009, "Germany",                "Alex Swings Oscar Sings!",              "Miss Kiss Kiss Bang",                      "", 0 },
                new object[] { 2,   2009, "United Kingdom",         "Jade Ewen",                             "It's My Time",                             "", 0 },
                new object[] { 1,   2009, "Spain",                  "Soraya Arnelas",                        "La noche es para mi",                      "", 0 }
            };

            var songs = raw_data.Select(raw_song => new Song { id = Int32.Parse(raw_song[0].ToString()),
                                                               year = Int16.Parse(raw_song[1].ToString()),
                                                               country = raw_song[2].ToString(),
                                                               artist_name = raw_song[3].ToString(),
                                                               song_name = raw_song[4].ToString(),
                                                               video_id = raw_song[5].ToString(),
                                                               seek_to = Int16.Parse(raw_song[6].ToString()) });

            return songs;

        }
    }
}
