using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace Euroguessr.Migrations
{
    /// <inheritdoc />
    public partial class SongsDataAdded : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "Score",
                keyColumns: new[] { "Userunique_token", "date" },
                keyValues: new object[] { "56489489185616", new DateOnly(2023, 10, 7) });

            migrationBuilder.DeleteData(
                table: "User",
                keyColumn: "unique_token",
                keyValue: "56489489185616");

            migrationBuilder.CreateTable(
                name: "Song",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    year = table.Column<short>(type: "smallint", nullable: false),
                    country = table.Column<string>(type: "text", nullable: false),
                    artist_name = table.Column<string>(type: "text", nullable: false),
                    song_name = table.Column<string>(type: "text", nullable: false),
                    video_id = table.Column<string>(type: "character varying(11)", maxLength: 11, nullable: false),
                    seek_to = table.Column<short>(type: "smallint", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Song", x => x.id);
                });

            migrationBuilder.InsertData(
                table: "Song",
                columns: new[] { "id", "artist_name", "country", "seek_to", "song_name", "video_id", "year" },
                values: new object[,]
                {
                    { 1, "Soraya Arnelas", "Spain", (short)0, "La noche es para mi", "", (short)2009 },
                    { 2, "Jade Ewen", "United Kingdom", (short)0, "It's My Time", "", (short)2009 },
                    { 3, "Alex Swings Oscar Sings!", "Germany", (short)0, "Miss Kiss Kiss Bang", "", (short)2009 },
                    { 4, "Anastasiya Prikhodko", "Russia", (short)0, "Mamo", "", (short)2009 },
                    { 5, "Patricia Kaas", "France", (short)0, "Et s'il fallait le faire", "", (short)2009 },
                    { 6, "The Toppers", "Netherlands", (short)0, "Shine", "", (short)2009 },
                    { 7, "Urban Symphony", "Estonia", (short)0, "Randajad", "", (short)2009 },
                    { 8, "Svetlana Loboda", "Ukraine", (short)0, "Be My Valentine! (Anti-Crisis Girl)", "", (short)2009 },
                    { 9, "Kejsi Tola", "Albania", (short)0, "Carry Me in Your Dreams", "", (short)2009 },
                    { 10, "Nelly Ciobanu", "Moldova", (short)0, "Hora din Moldova", "", (short)2009 },
                    { 11, "Sasha Son", "Lithuania", (short)0, "Love", "", (short)2009 },
                    { 12, "Sakis Rouvas", "Greece", (short)0, "This Is Our Night", "", (short)2009 },
                    { 13, "AySel and Arash", "Azerbaijan", (short)0, "Always", "", (short)2009 },
                    { 14, "Zoli adok", "Hungary", (short)0, "Dance with Me", "", (short)2009 },
                    { 15, "Quartissimo feat. Martina", "Slovenia", (short)0, "Love Symphony", "", (short)2009 },
                    { 16, "Niels Brinck", "Denmark", (short)0, "Believe Again", "", (short)2009 },
                    { 17, "Kamil Mikulcik and Nela Pociskova", "Slovakia", (short)0, "Let tmou", "", (short)2009 },
                    { 18, "Christina Metaxa", "Cyprus", (short)0, "Firefly", "", (short)2009 },
                    { 19, "Alexander Rybak", "Norway", (short)0, "Fairytale", "", (short)2009 },
                    { 20, "Lidia Kopania", "Poland", (short)0, "I Don't Wanna Leave", "", (short)2009 },
                    { 21, "Marko Kon and Milaan", "Serbia", (short)0, "Cipela", "", (short)2009 },
                    { 22, "Intars Busulis", "Latvia", (short)0, "Probka", "", (short)2009 },
                    { 23, "Sinead Mulvey and Black Daisy", "Ireland", (short)0, "Et Cetera", "", (short)2009 },
                    { 24, "Igor Cukrov feat. Andrea", "Croatia", (short)0, "Lijepa Tena", "", (short)2009 },
                    { 25, "Regina", "Bosnia and Herzegovina", (short)0, "Bistra voda", "", (short)2009 },
                    { 26, "Chiara", "Malta", (short)0, "What If We", "", (short)2009 },
                    { 27, "Flor-de-Lis", "Portugal", (short)0, "Todas as ruas do amor", "", (short)2009 },
                    { 28, "Waldo's People", "Finland", (short)0, "Lose Control", "", (short)2009 },
                    { 29, "Elena", "Romania", (short)0, "The Balkan Girls", "", (short)2009 },
                    { 30, "Next Time", "North Macedonia", (short)0, "Nesto sto kje ostane", "", (short)2009 },
                    { 31, "Yohanna", "Iceland", (short)0, "Is It True?", "", (short)2009 },
                    { 32, "Krassimir Avramov", "Bulgaria", (short)0, "Illusion", "", (short)2009 },
                    { 33, "Noa and Mira Awad", "Israel", (short)0, "There Must Be Another Way", "", (short)2009 },
                    { 34, "Hadise", "Turkey", (short)0, "Dum Tek Tek", "", (short)2009 },
                    { 35, "Lovebugs", "Switzerland", (short)0, "The Highest Heights", "", (short)2009 },
                    { 36, "Susanne Georgi", "Andorra", (short)0, "La teva decisio (Get a Life)", "", (short)2009 },
                    { 37, "Inga and Anush", "Armenia", (short)0, "Jan Jan", "", (short)2009 },
                    { 38, "Malena Ernman", "Sweden", (short)0, "La voix", "", (short)2009 },
                    { 39, "Petr Elfimov", "Belarus", (short)0, "Eyes That Never Lie", "", (short)2009 },
                    { 40, "Copycat", "Belgium", (short)0, "Copycat", "", (short)2009 },
                    { 41, "Gipsy.cz", "Czech Republic", (short)0, "Aven Romale", "", (short)2009 },
                    { 42, "Andrea Demirovic", "Montenegro", (short)0, "Just Get Out of My Life", "", (short)2009 },
                    { 43, "Lena", "Germany", (short)0, "Satellite", "", (short)2010 },
                    { 44, "Jessy Matador", "France", (short)0, "Allez Ola Ole", "", (short)2010 },
                    { 45, "Josh Dubovie", "United Kingdom", (short)0, "That Sounds Good to Me", "", (short)2010 },
                    { 46, "Didrik Solli-Tangen", "Norway", (short)0, "My Heart Is Yours", "", (short)2010 },
                    { 47, "Daniel Diges", "Spain", (short)0, "Algo pequenito", "", (short)2010 },
                    { 48, "maNga", "Turkey", (short)0, "We Could Be the Same", "", (short)2010 },
                    { 49, "Sofia Nizharadze", "Georgia", (short)0, "Shine", "", (short)2010 },
                    { 50, "Feminnem", "Croatia", (short)0, "Lako je sve", "", (short)2010 },
                    { 51, "Jon Lilygreen and The Islanders", "Cyprus", (short)0, "Life Looks Better in Spring", "", (short)2010 },
                    { 52, "Miro", "Bulgaria", (short)0, "Angel si ti", "", (short)2010 },
                    { 53, "Niamh Kavanagh", "Ireland", (short)0, "It's for You", "", (short)2010 },
                    { 54, "Ansambel zlindra and Kalamari", "Slovenia", (short)0, "Narodnozabavni rock", "", (short)2010 },
                    { 55, "Paula Seling and Ovi", "Romania", (short)0, "Playing with Fire", "", (short)2010 },
                    { 56, "Sieneke", "Netherlands", (short)0, "Ik ben verliefd", "", (short)2010 },
                    { 57, "Alyosha", "Ukraine", (short)0, "Sweet People", "", (short)2010 },
                    { 58, "Safura", "Azerbaijan", (short)0, "Drip Drop", "", (short)2010 },
                    { 59, "Anna Bergendahl", "Sweden", (short)0, "This Is My Life", "", (short)2010 },
                    { 60, "Michael von der Heide", "Switzerland", (short)0, "Il pleut de l'or", "", (short)2010 },
                    { 61, "Chanee and N'evergreen", "Denmark", (short)0, "In a Moment Like This", "", (short)2010 },
                    { 62, "Harel Skaat", "Israel", (short)0, "Milim", "", (short)2010 },
                    { 63, "Eva Rivas", "Armenia", (short)0, "Apricot Stone", "", (short)2010 },
                    { 64, "InCulto", "Lithuania", (short)0, "Eastern European Funk", "", (short)2010 },
                    { 65, "Hera Bjork", "Iceland", (short)0, "Je ne sais quoi", "", (short)2010 },
                    { 66, "3+2 feat Robert Wells", "Belarus", (short)0, "Butterflies", "", (short)2010 },
                    { 67, "Gjoko Taneski", "North Macedonia", (short)0, "Jas ja imam silata", "", (short)2010 },
                    { 68, "Filipa Azevedo", "Portugal", (short)0, "Ha dias assim", "", (short)2010 },
                    { 69, "Giorgos Alkaios and Friends", "Greece", (short)0, "OPA", "", (short)2010 },
                    { 70, "Juliana Pasha", "Albania", (short)0, "It's All About You", "", (short)2010 },
                    { 71, "Thea Garrett", "Malta", (short)0, "My Dream", "", (short)2010 },
                    { 72, "Tom Dice", "Belgium", (short)0, "Me and My Guitar", "", (short)2010 },
                    { 73, "Marcin Mrozinski", "Poland", (short)0, "Legenda", "", (short)2010 },
                    { 74, "Vukasin Brajic", "Bosnia and Herzegovina", (short)0, "Thunder and Lightning", "", (short)2010 },
                    { 75, "Milan Stankovic", "Serbia", (short)0, "Ovo je Balkan", "", (short)2010 },
                    { 76, "Aisha", "Latvia", (short)0, "What For?", "", (short)2010 },
                    { 77, "Kuunkuiskaajat", "Finland", (short)0, "Tyolki ellaa", "", (short)2010 },
                    { 78, "Kristina", "Slovakia", (short)0, "Horehronie", "", (short)2010 },
                    { 79, "Malcolm Lincoln", "Estonia", (short)0, "Siren", "", (short)2010 },
                    { 80, "Peter Nalitch and Friends", "Russia", (short)0, "Lost and Forgotten", "", (short)2010 },
                    { 81, "SunStroke Project and Olia Tira", "Moldova", (short)0, "Run Away", "", (short)2010 },
                    { 82, "Lucia Perez", "Spain", (short)0, "Que me quiten lo bailao", "", (short)2011 },
                    { 83, "Lena", "Germany", (short)0, "Taken by a Stranger", "", (short)2011 },
                    { 84, "Blue", "United Kingdom", (short)0, "I Can", "", (short)2011 },
                    { 85, "Raphael Gualazzi", "Italy", (short)0, "Madness of Love", "", (short)2011 },
                    { 86, "Amaury Vassili", "France", (short)0, "Sognu", "", (short)2011 },
                    { 87, "Jedward", "Ireland", (short)0, "Lipstick", "", (short)2011 },
                    { 88, "A Friend in London", "Denmark", (short)0, "New Tomorrow", "", (short)2011 },
                    { 89, "Musiqq", "Latvia", (short)0, "Angel in Disguise", "", (short)2011 },
                    { 90, "Anastasia Vinnikova", "Belarus", (short)0, "I Love Belarus", "", (short)2011 },
                    { 91, "Getter Jaani", "Estonia", (short)0, "Rockefeller Street", "", (short)2011 },
                    { 92, "Hotel FM", "Romania", (short)0, "Change", "", (short)2011 },
                    { 93, "Maja Keuc", "Slovenia", (short)0, "No One", "", (short)2011 },
                    { 94, "Dana International", "Israel", (short)0, "Ding Dong", "", (short)2011 },
                    { 95, "Vlatko Ilievski", "North Macedonia", (short)0, "Rusinka", "", (short)2011 },
                    { 96, "Poli Genova", "Bulgaria", (short)0, "Na inat", "", (short)2011 },
                    { 97, "Christos Mylordos", "Cyprus", (short)0, "San aggelos s'agapisa", "", (short)2011 },
                    { 98, "Eric Saade", "Sweden", (short)0, "Popular", "", (short)2011 },
                    { 99, "Zdob si Zdub", "Moldova", (short)0, "So Lucky", "", (short)2011 },
                    { 100, "Mika Newton", "Ukraine", (short)0, "Angel", "", (short)2011 },
                    { 101, "TWiiNS", "Slovakia", (short)0, "I'm Still Alive", "", (short)2011 },
                    { 102, "Witloof Bay", "Belgium", (short)0, "With Love Baby", "", (short)2011 },
                    { 103, "3JS", "Netherlands", (short)0, "Never Alone", "", (short)2011 },
                    { 104, "Nadine Beiler", "Austria", (short)0, "The Secret Is Love", "", (short)2011 },
                    { 105, "Dino Merlin", "Bosnia and Herzegovina", (short)0, "Love in Rewind", "", (short)2011 },
                    { 106, "Loukas Giorkas feat. Stereo Mike", "Greece", (short)0, "Watch My Dance", "", (short)2011 },
                    { 107, "Ell & Nikki", "Azerbaijan", (short)0, "Running Scared", "", (short)2011 },
                    { 108, "Evelina Sasenko", "Lithuania", (short)0, "C'est ma vie", "", (short)2011 },
                    { 109, "Homens da Luta", "Portugal", (short)0, "A luta e alegria", "", (short)2011 },
                    { 110, "Kati Wolf", "Hungary", (short)0, "What About My Dreams?", "", (short)2011 },
                    { 111, "Sjonni's Friends", "Iceland", (short)0, "Coming Home", "", (short)2011 },
                    { 112, "Daria", "Croatia", (short)0, "Celebrate", "", (short)2011 },
                    { 113, "Senit", "San Marino", (short)0, "Stand By", "", (short)2011 },
                    { 114, "Glen Vella", "Malta", (short)0, "One Life", "", (short)2011 },
                    { 115, "Paradise Oskar", "Finland", (short)0, "Da Da Dam", "", (short)2011 },
                    { 116, "Eldrine", "Georgia", (short)0, "One More Day", "", (short)2011 },
                    { 117, "Anna Rossinelli", "Switzerland", (short)0, "In Love for a While", "", (short)2011 },
                    { 118, "Alexey Vorobyov", "Russia", (short)0, "Get You", "", (short)2011 },
                    { 119, "Nina", "Serbia", (short)0, "Caroban", "", (short)2011 },
                    { 120, "Yuksek Sadakat", "Turkey", (short)0, "Live It Up", "", (short)2011 },
                    { 121, "Emmy", "Armenia", (short)0, "Boom Boom", "", (short)2011 },
                    { 122, "Aurela Ga e", "Albania", (short)0, "Feel the Passion", "", (short)2011 },
                    { 123, "Stella Mwangi", "Norway", (short)0, "Haba Haba", "", (short)2011 },
                    { 124, "Magdalena Tul", "Poland", (short)0, "Jestem", "", (short)2011 },
                    { 125, "Roman Lob", "Germany", (short)0, "Standing Still", "", (short)2012 },
                    { 126, "Pastora Soler", "Spain", (short)0, "Quedate conmigo (Stay With Me)", "", (short)2012 },
                    { 127, "Sabina Babayeva", "Azerbaijan", (short)0, "When the Music Dies", "", (short)2012 },
                    { 128, "Nina Zilli", "Italy", (short)0, "L'amore e femmina (Out of Love)", "", (short)2012 },
                    { 129, "Anggun", "France", (short)0, "Echo (You and I)", "", (short)2012 },
                    { 130, "Engelbert Humperdinck", "United Kingdom", (short)0, "Love Will Set You Free", "", (short)2012 },
                    { 131, "Donny Montell", "Lithuania", (short)0, "Love Is Blind", "", (short)2012 },
                    { 132, "Maya Sar", "Bosnia and Herzegovina", (short)0, "Korake ti znam", "", (short)2012 },
                    { 133, "Tooji", "Norway", (short)0, "Stay", "", (short)2012 },
                    { 134, "Max Jason Mai", "Slovakia", (short)0, "Don't Close Your Eyes", "", (short)2012 },
                    { 135, "Ott Lepland", "Estonia", (short)0, "Kuula", "", (short)2012 },
                    { 136, "Can Bonomo", "Turkey", (short)0, "Love Me Back", "", (short)2012 },
                    { 137, "Anri Jokhadze", "Georgia", (short)0, "I'm a Joker", "", (short)2012 },
                    { 138, "Loreen", "Sweden", (short)0, "Euphoria", "", (short)2012 },
                    { 139, "Nina Badric", "Croatia", (short)0, "Nebo", "", (short)2012 },
                    { 140, "Eva Boto", "Slovenia", (short)0, "Verjamem", "", (short)2012 },
                    { 141, "Sofi Marinova", "Bulgaria", (short)0, "Love Unlimited", "", (short)2012 },
                    { 142, "Gaitana", "Ukraine", (short)0, "Be My Guest", "", (short)2012 },
                    { 143, "Filipa Sousa", "Portugal", (short)0, "Vida minha", "", (short)2012 },
                    { 144, "Litesound", "Belarus", (short)0, "We Are the Heroes", "", (short)2012 },
                    { 145, "Kurt Calleja", "Malta", (short)0, "This Is the Night", "", (short)2012 },
                    { 146, "Joan Franka", "Netherlands", (short)0, "You and Me", "", (short)2012 },
                    { 147, "Kaliopi", "North Macedonia", (short)0, "Crno i belo", "", (short)2012 },
                    { 148, "zeljko Joksimovic", "Serbia", (short)0, "Nije ljubav stvar ", "", (short)2012 },
                    { 149, "Jedward", "Ireland", (short)0, "Waterline", "", (short)2012 },
                    { 150, "Pasha Parfeny", "Moldova", (short)0, "Lautar", "", (short)2012 },
                    { 151, "Trackshittaz", "Austria", (short)0, "Woki mit deim Popo", "", (short)2012 },
                    { 152, "Compact Disco", "Hungary", (short)0, "Sound of Our Hearts", "", (short)2012 },
                    { 153, "Buranovskiye Babushki", "Russia", (short)0, "Party for Everybody", "", (short)2012 },
                    { 154, "Soluna Samay", "Denmark", (short)0, "Should've Known Better", "", (short)2012 },
                    { 155, "Ivi Adamou", "Cyprus", (short)0, "La La Love", "", (short)2012 },
                    { 156, "Valentina Monetta", "San Marino", (short)0, "The Social Network Song (Oh Oh-Uh-Oh Oh)", "", (short)2012 },
                    { 157, "Izabo", "Israel", (short)0, "Time", "", (short)2012 },
                    { 158, "Pernilla Karlsson", "Finland", (short)0, "Nar jag blundar", "", (short)2012 },
                    { 159, "Iris", "Belgium", (short)0, "Would You?", "", (short)2012 },
                    { 160, "Sinplus", "Switzerland", (short)0, "Unbreakable", "", (short)2012 },
                    { 161, "Mandinga", "Romania", (short)0, "Zaleilah", "", (short)2012 },
                    { 162, "Rona Nishliu", "Albania", (short)0, "Suus3", "", (short)2012 },
                    { 163, "Anmary", "Latvia", (short)0, "Beautiful Song", "", (short)2012 },
                    { 164, "Eleftheria Eleftheriou", "Greece", (short)0, "Aphrodisiac", "", (short)2012 },
                    { 165, "Greta Salome and Jonsi", "Iceland", (short)0, "Never Forget", "", (short)2012 },
                    { 166, "Rambo Amadeus", "Montenegro", (short)0, "Euro Neuro", "", (short)2012 },
                    { 167, "Marco Mengoni", "Italy", (short)0, "L'essenziale", "", (short)2013 },
                    { 168, "Robin Stjernberg", "Sweden", (short)0, "You", "", (short)2013 },
                    { 169, "Bonnie Tyler", "United Kingdom", (short)0, "Believe in Me", "", (short)2013 },
                    { 170, "Cascada", "Germany", (short)0, "Glorious", "", (short)2013 },
                    { 171, "ESDM", "Spain", (short)0, "Contigo hasta el final", "", (short)2013 },
                    { 172, "Amandine Bourgeois", "France", (short)0, "L'enfer et moi", "", (short)2013 },
                    { 173, "Cezar", "Romania", (short)0, "It's My Life", "", (short)2013 },
                    { 174, "Takasa", "Switzerland", (short)0, "You and Me", "", (short)2013 },
                    { 175, "Nodi Tatishvili & Sophie Gelovani", "Georgia", (short)0, "Waterfall", "", (short)2013 },
                    { 176, "Adrian Lulgjuraj & Bledar Sejko", "Albania", (short)0, "Identitet", "", (short)2013 },
                    { 177, "Margaret Berger", "Norway", (short)0, "I Feed You My Love", "", (short)2013 },
                    { 178, "ByeAlex", "Hungary", (short)0, "Kedvesem (Zoohacker Remix)", "", (short)2013 },
                    { 179, "Dorians", "Armenia", (short)0, "Lonely Planet", "", (short)2013 },
                    { 180, "Moran Mazor", "Israel", (short)0, "Rak Bishvilo", "", (short)2013 },
                    { 181, "Koza Mostra feat. Agathon Iakovidis", "Greece", (short)0, "Alcohol Is Free", "", (short)2013 },
                    { 182, "Eythor Ingi", "Iceland", (short)0, "Eg a lif", "", (short)2013 },
                    { 183, "Elitsa Todorova & Stoyan Yankoulov", "Bulgaria", (short)0, "Samo shampioni", "", (short)2013 },
                    { 184, "Gianluca", "Malta", (short)0, "Tomorrow", "", (short)2013 },
                    { 185, "Krista Siegfrids", "Finland", (short)0, "Marry Me", "", (short)2013 },
                    { 186, "Farid Mammadov", "Azerbaijan", (short)0, "Hold Me", "", (short)2013 },
                    { 187, "Esma & Lozano", "North Macedonia", (short)0, "Pred da se razdeni", "", (short)2013 },
                    { 188, "Valentina Monetta", "San Marino", (short)0, "Crisalide (Vola)", "", (short)2013 },
                    { 189, "PeR", "Latvia", (short)0, "Here We Go", "", (short)2013 },
                    { 190, "Moje 3", "Serbia", (short)0, "Ljubav je svuda", "", (short)2013 },
                    { 191, "Roberto Bellarosa", "Belgium", (short)0, "Love Kills", "", (short)2013 },
                    { 192, "Despina Olympiou", "Cyprus", (short)0, "An me thimasai", "", (short)2013 },
                    { 193, "Ryan Dolan", "Ireland", (short)0, "Only Love Survives", "", (short)2013 },
                    { 194, "Aliona Moon", "Moldova", (short)0, "O mie", "", (short)2013 },
                    { 195, "Alyona Lanskaya", "Belarus", (short)0, "Solayoh", "", (short)2013 },
                    { 196, "Andrius Pojavis", "Lithuania", (short)0, "Something", "", (short)2013 },
                    { 197, "Who See", "Montenegro", (short)0, "Igranka", "", (short)2013 },
                    { 198, "Anouk", "Netherlands", (short)0, "Birds", "", (short)2013 },
                    { 199, "Zlata Ognevich", "Ukraine", (short)0, "Gravity", "", (short)2013 },
                    { 200, "Dina Garipova", "Russia", (short)0, "What If", "", (short)2013 },
                    { 201, "Emmelie de Forest", "Denmark", (short)0, "Only Teardrops", "", (short)2013 },
                    { 202, "Klapa s Mora", "Croatia", (short)0, "Mizerja", "", (short)2013 },
                    { 203, "Hannah", "Slovenia", (short)0, "Straight Into Love", "", (short)2013 },
                    { 204, "Birgit", "Estonia", (short)0, "Et uus saaks alguse", "", (short)2013 },
                    { 205, "Natalia Kelly", "Austria", (short)0, "Shine", "", (short)2013 },
                    { 206, "Molly", "United Kingdom", (short)0, "Children of the Universe", "", (short)2014 },
                    { 207, "Basim", "Denmark", (short)0, "Cliche Love Song", "", (short)2014 },
                    { 208, "Ruth Lorenzo", "Spain", (short)0, "Dancing in the Rain", "", (short)2014 },
                    { 209, "Emma", "Italy", (short)0, "La mia citta", "", (short)2014 },
                    { 210, "TWIN TWIN", "France", (short)0, "Moustache", "", (short)2014 },
                    { 211, "Elaiza", "Germany", (short)0, "Is It Right", "", (short)2014 },
                    { 212, "Paula Seling & Ovi", "Romania", (short)0, "Miracle", "", (short)2014 },
                    { 213, "Tinkara Kovac", "Slovenia", (short)0, "Round and Round", "", (short)2014 },
                    { 214, "Freaky Fortune feat. RiskyKidd", "Greece", (short)0, "Rise Up", "", (short)2014 },
                    { 215, "Sebalter", "Switzerland", (short)0, "Hunter of Stars", "", (short)2014 },
                    { 216, "Tijana", "North Macedonia", (short)0, "To the Sky", "", (short)2014 },
                    { 217, "Teo", "Belarus", (short)0, "Cheesecake", "", (short)2014 },
                    { 218, "Can-Linn feat. Kasey Smith", "Ireland", (short)0, "Heartbeat", "", (short)2014 },
                    { 219, "Softengine", "Finland", (short)0, "Something Better", "", (short)2014 },
                    { 220, "Vilija", "Lithuania", (short)0, "Attention", "", (short)2014 },
                    { 221, "Conchita Wurst", "Austria", (short)0, "Rise Like a Phoenix", "", (short)2014 },
                    { 222, "Donatan & Cleo", "Poland", (short)0, "My Slowianie   We Are Slavic", "", (short)2014 },
                    { 223, "The Shin and Mariko", "Georgia", (short)0, "Three Minutes to Earth", "", (short)2014 },
                    { 224, "Carl Espen", "Norway", (short)0, "Silent Storm", "", (short)2014 },
                    { 225, "Mei Finegold", "Israel", (short)0, "Same Heart", "", (short)2014 },
                    { 226, "Firelight", "Malta", (short)0, "Coming Home", "", (short)2014 },
                    { 227, "Andras Kallay-Saunders", "Hungary", (short)0, "Running", "", (short)2014 },
                    { 228, "Sergej cetkovic", "Montenegro", (short)0, "Moj svijet", "", (short)2014 },
                    { 229, "The Common Linnets", "Netherlands", (short)0, "Calm After the Storm", "", (short)2014 },
                    { 230, "Suzy", "Portugal", (short)0, "Quero ser tua", "", (short)2014 },
                    { 231, "Valentina Monetta", "San Marino", (short)0, "Maybe", "", (short)2014 },
                    { 232, "Cristina Scarlat", "Moldova", (short)0, "Wild Soul", "", (short)2014 },
                    { 233, "Axel Hirsoux", "Belgium", (short)0, "Mother", "", (short)2014 },
                    { 234, "Mariya Yaremchuk", "Ukraine", (short)0, "Tick-Tock", "", (short)2014 },
                    { 235, "Dilara Kazimova", "Azerbaijan", (short)0, "Start a Fire", "", (short)2014 },
                    { 236, "Tolmachevy Sisters", "Russia", (short)0, "Shine", "", (short)2014 },
                    { 237, "Hersi", "Albania", (short)0, "One Night's Anger", "", (short)2014 },
                    { 238, "Pollaponk", "Iceland", (short)0, "No Prejudice", "", (short)2014 },
                    { 239, "Sanna Nielsen", "Sweden", (short)0, "Undo", "", (short)2014 },
                    { 240, "Tanja", "Estonia", (short)0, "Amazing", "", (short)2014 },
                    { 241, "Aarzemnieki", "Latvia", (short)0, "Cake to Bake", "", (short)2014 },
                    { 242, "Aram MP3", "Armenia", (short)0, "Not Alone", "", (short)2014 },
                    { 243, "Il Volo", "Italy", (short)0, "Grande amore", "", (short)2015 },
                    { 244, "Edurne", "Spain", (short)0, "Amanecer", "", (short)2015 },
                    { 245, "Ann Sophie", "Germany", (short)0, "Black Smoke", "", (short)2015 },
                    { 246, "The Makemakes", "Austria", (short)0, "I Am Yours", "", (short)2015 },
                    { 247, "Electro Velvet", "United Kingdom", (short)0, "Still in Love with You", "", (short)2015 },
                    { 248, "Lisa Angell", "France", (short)0, "N'oubliez pas", "", (short)2015 },
                    { 249, "Monika Kuszynska", "Poland", (short)0, "In the Name of Love", "", (short)2015 },
                    { 250, "Maraaya", "Slovenia", (short)0, "Here for You", "", (short)2015 },
                    { 251, "John Karayiannis", "Cyprus", (short)0, "One Thing I Should Have Done", "", (short)2015 },
                    { 252, "Melanie Rene", "Switzerland", (short)0, "Time to Shine", "", (short)2015 },
                    { 253, "Mans Zelmerlow", "Sweden", (short)0, "Heroes", "", (short)2015 },
                    { 254, "Maria Olafs", "Iceland", (short)0, "Unbroken", "", (short)2015 },
                    { 255, "Elnur Huseynov", "Azerbaijan", (short)0, "Hour of the Wolf", "", (short)2015 },
                    { 256, "Aminata", "Latvia", (short)0, "Love Injected", "", (short)2015 },
                    { 257, "Nadav Guedj", "Israel", (short)0, "Golden Boy", "", (short)2015 },
                    { 258, "Marta Jandova & Vaclav Noid Barta", "Czech Republic", (short)0, "Hope Never Dies", "", (short)2015 },
                    { 259, "Leonor Andrade", "Portugal", (short)0, "Ha um mar que nos separa", "", (short)2015 },
                    { 260, "Morland & Debrah Scarlett", "Norway", (short)0, "A Monster Like Me", "", (short)2015 },
                    { 261, "Amber", "Malta", (short)0, "Warrior", "", (short)2015 },
                    { 262, "Knez", "Montenegro", (short)0, "Adio", "", (short)2015 },
                    { 263, "Anita Simoncini & Michele Perniola", "San Marino", (short)0, "Chain of Lights", "", (short)2015 },
                    { 264, "Molly Sterling", "Ireland", (short)0, "Playing with Numbers", "", (short)2015 },
                    { 265, "Monika Linkyte & Vaidas Baumila", "Lithuania", (short)0, "This Time", "", (short)2015 },
                    { 266, "Nina Sublatti", "Georgia", (short)0, "Warrior", "", (short)2015 },
                    { 267, "Voltaj", "Romania", (short)0, "De la capat", "", (short)2015 },
                    { 268, "Elhaida Dani", "Albania", (short)0, "I'm Alive", "", (short)2015 },
                    { 269, "Anti Social Media", "Denmark", (short)0, "The Way You Are", "", (short)2015 },
                    { 270, "Polina Gagarina", "Russia", (short)0, "A Million Voices", "", (short)2015 },
                    { 271, "Uzari & Maimuna", "Belarus", (short)0, "Time", "", (short)2015 },
                    { 272, "Boggie", "Hungary", (short)0, "Wars for Nothing", "", (short)2015 },
                    { 273, "Bojana Stamenov", "Serbia", (short)0, "Beauty Never Lies", "", (short)2015 },
                    { 274, "Daniel Kajmakoski", "North Macedonia", (short)0, "Autumn Leaves", "", (short)2015 },
                    { 275, "Elina Born & Stig Rasta", "Estonia", (short)0, "Goodbye to Yesterday", "", (short)2015 },
                    { 276, "Maria Elena Kyriakou", "Greece", (short)0, "One Last Breath", "", (short)2015 },
                    { 277, "Pertti Kurikan Nimipaivat", "Finland", (short)0, "Aina mun pitaa", "", (short)2015 },
                    { 278, "Trijntje Oosterhuis", "Netherlands", (short)0, "Walk Along", "", (short)2015 },
                    { 279, "Loic Nottet", "Belgium", (short)0, "Rhythm Inside", "", (short)2015 },
                    { 280, "Genealogy", "Armenia", (short)0, "Face the Shadow", "", (short)2015 },
                    { 281, "Eduard Romanyuta", "Moldova", (short)0, "I Want Your Love", "", (short)2015 },
                    { 282, "Joe and Jake", "United Kingdom", (short)0, "You're Not Alone", "", (short)2016 },
                    { 283, "Barei", "Spain", (short)0, "Say Yay!", "", (short)2016 },
                    { 284, "Amir", "France", (short)0, "J'ai cherche", "", (short)2016 },
                    { 285, "Jamie-Lee", "Germany", (short)0, "Ghost", "", (short)2016 },
                    { 286, "Frans", "Sweden", (short)0, "If I Were Sorry", "", (short)2016 },
                    { 287, "Francesca Michielin", "Italy", (short)0, "No Degree of Separation", "", (short)2016 },
                    { 288, "Laura Tesoro", "Belgium", (short)0, "What's the Pressure", "", (short)2016 },
                    { 289, "Eneda Tarifa", "Albania", (short)0, "Fairytale", "", (short)2016 },
                    { 290, "Nika Kocharov & Young Georgian Lolitaz", "Georgia", (short)0, "Midnight Gold", "", (short)2016 },
                    { 291, "Agnete", "Norway", (short)0, "Icebreaker", "", (short)2016 },
                    { 292, "Jamala", "Ukraine", (short)0, "1944", "", (short)2016 },
                    { 293, "Lighthouse X", "Denmark", (short)0, "Soldiers of Love", "", (short)2016 },
                    { 294, "Poli Genova", "Bulgaria", (short)0, "If Love Was a Crime", "", (short)2016 },
                    { 295, "ManuElla", "Slovenia", (short)0, "Blue and Red", "", (short)2016 },
                    { 296, "Dami Im", "Australia", (short)0, "Sound of Silence", "", (short)2016 },
                    { 297, "Donny Montell", "Lithuania", (short)0, "I've Been Waiting for This Night", "", (short)2016 },
                    { 298, "Kaliopi", "North Macedonia", (short)0, "Dona", "", (short)2016 },
                    { 299, "Nicky Byrne", "Ireland", (short)0, "Sunlight", "", (short)2016 },
                    { 300, "Sanja Vucic ZAA", "Serbia", (short)0, "Goodbye (Shelter)", "", (short)2016 },
                    { 301, "Ivan", "Belarus", (short)0, "Help You Fly", "", (short)2016 },
                    { 302, "Hovi Star", "Israel", (short)0, "Made of Stars", "", (short)2016 },
                    { 303, "Rykka", "Switzerland", (short)0, "The Last of Our Kind", "", (short)2016 },
                    { 304, "Michal Szpak", "Poland", (short)0, "Color of Your Life", "", (short)2016 },
                    { 305, "Justs", "Latvia", (short)0, "Heartbeat", "", (short)2016 },
                    { 306, "Ira Losco", "Malta", (short)0, "Walk on Water", "", (short)2016 },
                    { 307, "Dalal & Deen feat Ana Rucner and Jala", "Bosnia and Herzegovina", (short)0, "Ljubav je", "", (short)2016 },
                    { 308, "Greta SalOme", "Iceland", (short)0, "Hear Them Calling", "", (short)2016 },
                    { 309, "Highway", "Montenegro", (short)0, "The Real Thing", "", (short)2016 },
                    { 310, "Samra", "Azerbaijan", (short)0, "Miracle", "", (short)2016 },
                    { 311, "Juri Pootsmann", "Estonia", (short)0, "Play", "", (short)2016 },
                    { 312, "Zoe", "Austria", (short)0, "Loin d'ici", "", (short)2016 },
                    { 313, "Minus One", "Cyprus", (short)0, "Alter Ego", "", (short)2016 },
                    { 314, "Gabriela Guncikova", "Czech Republic", (short)0, "I Stand", "", (short)2016 },
                    { 315, "Sergey Lazarev", "Russia", (short)0, "You Are the Only One", "", (short)2016 },
                    { 316, "Serhat", "San Marino", (short)0, "I Didn't Know", "", (short)2016 },
                    { 317, "Iveta Mukuchyan", "Armenia", (short)0, "LoveWave", "", (short)2016 },
                    { 318, "Douwe Bob", "Netherlands", (short)0, "Slow Down", "", (short)2016 },
                    { 319, "Nina Kraljic", "Croatia", (short)0, "Lighthouse", "", (short)2016 },
                    { 320, "Freddie", "Hungary", (short)0, "Pioneer", "", (short)2016 },
                    { 321, "Lidia Isac", "Moldova", (short)0, "Falling Stars", "", (short)2016 },
                    { 322, "Argo", "Greece", (short)0, "Utopian Land", "", (short)2016 },
                    { 323, "Sandhja", "Finland", (short)0, "Sing It Away", "", (short)2016 },
                    { 324, "Alma", "France", (short)0, "Requiem", "", (short)2017 },
                    { 325, "O.Torvald", "Ukraine", (short)0, "Time", "", (short)2017 },
                    { 326, "Levina", "Germany", (short)0, "Perfect Life", "", (short)2017 },
                    { 327, "Lucie Jones", "United Kingdom", (short)0, "Never Give Up on You", "", (short)2017 },
                    { 328, "Manel Navarro", "Spain", (short)0, "Do It for Your Lover", "", (short)2017 },
                    { 329, "Francesco Gabbani", "Italy", (short)0, "Occidentali's Karma", "", (short)2017 },
                    { 330, "IMRI", "Israel", (short)0, "I Feel Alive", "", (short)2017 },
                    { 331, "Koit Toome and Laura", "Estonia", (short)0, "Verona", "", (short)2017 },
                    { 332, "Fusedmarc", "Lithuania", (short)0, "Rain of Revolution", "", (short)2017 },
                    { 333, "Kristian Kostov", "Bulgaria", (short)0, "Beautiful Mess", "", (short)2017 },
                    { 334, "Naviband", "Belarus", (short)0, "Story of My Life", "", (short)2017 },
                    { 335, "Timebelle", "Switzerland", (short)0, "Apollo", "", (short)2017 },
                    { 336, "JOWST", "Norway", (short)0, "Grab the Moment", "", (short)2017 },
                    { 337, "Jacques Houdek", "Croatia", (short)0, "My Friend", "", (short)2017 },
                    { 338, "Valentina Monetta and Jimmie Wilson", "San Marino", (short)0, "Spirit of the Night", "", (short)2017 },
                    { 339, "Brendan Murray", "Ireland", (short)0, "Dying to Try", "", (short)2017 },
                    { 340, "Anja", "Denmark", (short)0, "Where I Am", "", (short)2017 },
                    { 341, "Joci Papai", "Hungary", (short)0, "Origo", "", (short)2017 },
                    { 342, "O'G3NE", "Netherlands", (short)0, "Lights and Shadows", "", (short)2017 },
                    { 343, "Ilinca ft. Alex Florea", "Romania", (short)0, "Yodel It!", "", (short)2017 },
                    { 344, "Claudia Faniello", "Malta", (short)0, "Breathlessly", "", (short)2017 },
                    { 345, "Jana Burceska", "North Macedonia", (short)0, "Dance Alone", "", (short)2017 },
                    { 346, "Nathan Trent", "Austria", (short)0, "Running on Air", "", (short)2017 },
                    { 347, "Tijana Bogicevic", "Serbia", (short)0, "In Too Deep", "", (short)2017 },
                    { 348, "Triana Park", "Latvia", (short)0, "Line", "", (short)2017 },
                    { 349, "Omar Naber", "Slovenia", (short)0, "On My Way", "", (short)2017 },
                    { 350, "Artsvik", "Armenia", (short)0, "Fly with Me", "", (short)2017 },
                    { 351, "Hovig", "Cyprus", (short)0, "Gravity", "", (short)2017 },
                    { 352, "Martina Barta", "Czech Republic", (short)0, "My Turn", "", (short)2017 },
                    { 353, "Svala", "Iceland", (short)0, "Paper", "", (short)2017 },
                    { 354, "Sunstroke Project", "Moldova", (short)0, "Hey, Mamma!", "", (short)2017 },
                    { 355, "Kasia Mos", "Poland", (short)0, "Flashlight", "", (short)2017 },
                    { 356, "Demy", "Greece", (short)0, "This Is Love", "", (short)2017 },
                    { 357, "Salvador Sobral", "Portugal", (short)0, "Amar pelos dois", "", (short)2017 },
                    { 358, "Dihaj", "Azerbaijan", (short)0, "Skeletons", "", (short)2017 },
                    { 359, "Norma John", "Finland", (short)0, "Blackbird", "", (short)2017 },
                    { 360, "Slavko Kalezic", "Montenegro", (short)0, "Space", "", (short)2017 },
                    { 361, "Blanche", "Belgium", (short)0, "City Lights", "", (short)2017 },
                    { 362, "Lindita", "Albania", (short)0, "World", "", (short)2017 },
                    { 363, "Isaiah", "Australia", (short)0, "Don't Come Easy", "", (short)2017 },
                    { 364, "Tamara Gachechiladze", "Georgia", (short)0, "Keep the Faith", "", (short)2017 },
                    { 365, "Robin Bengtsson", "Sweden", (short)0, "I Can't Go On", "", (short)2017 },
                    { 366, "Amaia & Alfred", "Spain", (short)0, "Tu canciOn", "", (short)2018 },
                    { 367, "Ermal Meta & Fabrizio Moro", "Italy", (short)0, "Non mi avete fatto niente", "", (short)2018 },
                    { 368, "Madame Monsieur", "France", (short)0, "Mercy", "", (short)2018 },
                    { 369, "Michael Schulte", "Germany", (short)0, "You Let Me Walk Alone", "", (short)2018 },
                    { 370, "SuRie", "United Kingdom", (short)0, "Storm", "", (short)2018 },
                    { 371, "Claudia Pascoal", "Portugal", (short)0, "O jardim", "", (short)2018 },
                    { 372, "Melovin", "Ukraine", (short)0, "Under the Ladder", "", (short)2018 },
                    { 373, "Lea Sirk", "Slovenia", (short)0, "Hvala, ne!", "", (short)2018 },
                    { 374, "Vanja Radovanovic", "Montenegro", (short)0, "Inje", "", (short)2018 },
                    { 375, "Benjamin Ingrosso", "Sweden", (short)0, "Dance You Off", "", (short)2018 },
                    { 376, "Laura Rizzotto", "Latvia", (short)0, "Funny Girl", "", (short)2018 },
                    { 377, "AWS", "Hungary", (short)0, "Viszlat nyar", "", (short)2018 },
                    { 378, "Christabelle", "Malta", (short)0, "Taboo", "", (short)2018 },
                    { 379, "Gromee feat. Lukas Meijer", "Poland", (short)0, "Light Me Up", "", (short)2018 },
                    { 380, "Ethno-Jazz Band Iriao", "Georgia", (short)0, "For You", "", (short)2018 },
                    { 381, "Jessica Mauboy", "Australia", (short)0, "We Got Love", "", (short)2018 },
                    { 382, "Waylon", "Netherlands", (short)0, "Outlaw in 'Em", "", (short)2018 },
                    { 383, "DoReDoS", "Moldova", (short)0, "My Lucky Day", "", (short)2018 },
                    { 384, "Julia Samoylova", "Russia", (short)0, "I Won't Break", "", (short)2018 },
                    { 385, "Rasmussen", "Denmark", (short)0, "Higher Ground", "", (short)2018 },
                    { 386, "Jessika feat. Jenifer Brening", "San Marino", (short)0, "Who We Are", "", (short)2018 },
                    { 387, "Sanja Ilic & Balkanika", "Serbia", (short)0, "Nova deca", "", (short)2018 },
                    { 388, "The Humans", "Romania", (short)0, "Goodbye", "", (short)2018 },
                    { 389, "Alexander Rybak", "Norway", (short)0, "That's How You Write a Song", "", (short)2018 },
                    { 390, "Eleni Foureira", "Cyprus", (short)0, "Fuego", "", (short)2018 },
                    { 391, "Ryan O'Shaughnessy", "Ireland", (short)0, "Together", "", (short)2018 },
                    { 392, "ZiBBZ", "Switzerland", (short)0, "Stones", "", (short)2018 },
                    { 393, "Sevak Khanagyan", "Armenia", (short)0, "Qami", "", (short)2018 },
                    { 394, "Saara Aalto", "Finland", (short)0, "Monsters", "", (short)2018 },
                    { 395, "Yianna Terzi", "Greece", (short)0, "Oniro mou", "", (short)2018 },
                    { 396, "Cesar Sampson", "Austria", (short)0, "Nobody but You", "", (short)2018 },
                    { 397, "Franka", "Croatia", (short)0, "Crazy", "", (short)2018 },
                    { 398, "Eye Cue", "North Macedonia", (short)0, "Lost and Found", "", (short)2018 },
                    { 399, "Equinox", "Bulgaria", (short)0, "Bones", "", (short)2018 },
                    { 400, "Elina Nechayeva", "Estonia", (short)0, "La forza", "", (short)2018 },
                    { 401, "Alekseev", "Belarus", (short)0, "Forever", "", (short)2018 },
                    { 402, "Netta", "Israel", (short)0, "Toy", "", (short)2018 },
                    { 403, "Ieva Zasimauskaite", "Lithuania", (short)0, "When We're Old", "", (short)2018 },
                    { 404, "Mikolas Josef", "Czech Republic", (short)0, "Lie to Me", "", (short)2018 },
                    { 405, "Sennek", "Belgium", (short)0, "A Matter of Time", "", (short)2018 },
                    { 406, "Eugent Bushpepa", "Albania", (short)0, "Mall", "", (short)2018 },
                    { 407, "Ari Olafsson", "Iceland", (short)0, "Our Choice", "", (short)2018 },
                    { 408, "Aisel", "Azerbaijan", (short)0, "X My Heart", "", (short)2018 },
                    { 409, "Miki", "Spain", (short)0, "La Venda", "", (short)2019 },
                    { 410, "Mahmood", "Italy", (short)0, "Soldi", "", (short)2019 },
                    { 411, "Bilal Hassani", "France", (short)0, "Roi", "", (short)2019 },
                    { 412, "Michael Rice", "United Kingdom", (short)0, "Bigger than Us", "", (short)2019 },
                    { 413, "Kobi Marimi", "Israel", (short)0, "Home", "", (short)2019 },
                    { 414, "S!sters", "Germany", (short)0, "Sister", "", (short)2019 },
                    { 415, "Chingiz", "Azerbaijan", (short)0, "Truth", "", (short)2019 },
                    { 416, "Tamara Todevska", "North Macedonia", (short)0, "Proud", "", (short)2019 },
                    { 417, "Duncan Laurence", "Netherlands", (short)0, "Arcade", "", (short)2019 },
                    { 418, "KEiiNO", "Norway", (short)0, "Spirit in the Sky", "", (short)2019 },
                    { 419, "Jonida Maliqi", "Albania", (short)0, "Ktheju tokes", "", (short)2019 },
                    { 420, "Sergey Lazarev", "Russia", (short)0, "Scream", "", (short)2019 },
                    { 421, "Jurij Veklenko", "Lithuania", (short)0, "Run with the Lions", "", (short)2019 },
                    { 422, "Michela", "Malta", (short)0, "Chameleon", "", (short)2019 },
                    { 423, "Roko", "Croatia", (short)0, "The Dream", "", (short)2019 },
                    { 424, "PAENDA", "Austria", (short)0, "Limits", "", (short)2019 },
                    { 425, "John Lundvik", "Sweden", (short)0, "Too Late for Love", "", (short)2019 },
                    { 426, "Leonora", "Denmark", (short)0, "Love Is Forever", "", (short)2019 },
                    { 427, "Ester Peony", "Romania", (short)0, "On a Sunday", "", (short)2019 },
                    { 428, "Carousel", "Latvia", (short)0, "That Night", "", (short)2019 },
                    { 429, "Luca Hanni", "Switzerland", (short)0, "She Got Me", "", (short)2019 },
                    { 430, "Anna Odobescu", "Moldova", (short)0, "Stay", "", (short)2019 },
                    { 431, "Sarah McTernan", "Ireland", (short)0, "22", "", (short)2019 },
                    { 432, "Srbuk", "Armenia", (short)0, "Walking Out", "", (short)2019 },
                    { 433, "Serhat", "San Marino", (short)0, "Say Na Na Na", "", (short)2019 },
                    { 434, "Katerine Duska", "Greece", (short)0, "Better Love", "", (short)2019 },
                    { 435, "Conan Osiris", "Portugal", (short)0, "TelemOveis", "", (short)2019 },
                    { 436, "Victor Crone", "Estonia", (short)0, "Storm", "", (short)2019 },
                    { 437, "Hatari", "Iceland", (short)0, "Hatrio mun sigra", "", (short)2019 },
                    { 438, "Kate Miller-Heidke", "Australia", (short)0, "Zero Gravity", "", (short)2019 },
                    { 439, "Oto Nemsadze", "Georgia", (short)0, "Keep on Going", "", (short)2019 },
                    { 440, "Eliot", "Belgium", (short)0, "Wake Up", "", (short)2019 },
                    { 441, "Nevena Bozovic", "Serbia", (short)0, "Kruna", "", (short)2019 },
                    { 442, "ZENA", "Belarus", (short)0, "Like It", "", (short)2019 },
                    { 443, "Joci Papai", "Hungary", (short)0, "Az en apam", "", (short)2019 },
                    { 444, "Lake Malawi", "Czech Republic", (short)0, "Friend of a Friend", "", (short)2019 },
                    { 445, "Zala Kralj & Gasper santl", "Slovenia", (short)0, "Sebi", "", (short)2019 },
                    { 446, "Tulia", "Poland", (short)0, "Fire of Love", "", (short)2019 },
                    { 447, "Darude feat. Sebastian Rejman", "Finland", (short)0, "Look Away", "", (short)2019 },
                    { 448, "D mol", "Montenegro", (short)0, "Heaven", "", (short)2019 },
                    { 449, "Tamta", "Cyprus", (short)0, "Replay", "", (short)2019 },
                    { 450, "Maneskin", "Italy", (short)0, "Zitti e buoni", "", (short)2021 },
                    { 451, "Barbara Pravi", "France", (short)0, "Voila", "", (short)2021 },
                    { 452, "Jendrik", "Germany", (short)0, "I Don't Feel Hate", "", (short)2021 },
                    { 453, "James Newman", "United Kingdom", (short)0, "Embers", "", (short)2021 },
                    { 454, "Blas Canto", "Spain", (short)0, "Voy a quedarme", "", (short)2021 },
                    { 455, "Jeangu Macrooy", "Netherlands", (short)0, "Birth of a New Age", "", (short)2021 },
                    { 456, "Fyr og Flamme", "Denmark", (short)0, "Ove os pa hinanden", "", (short)2021 },
                    { 457, "Gjon's Tears", "Switzerland", (short)0, "Tout l'univers", "", (short)2021 },
                    { 458, "Samanta Tina", "Latvia", (short)0, "The Moon Is Rising", "", (short)2021 },
                    { 459, "Blind Channel", "Finland", (short)0, "Dark Side", "", (short)2021 },
                    { 460, "Victoria", "Bulgaria", (short)0, "Growing Up Is Getting Old", "", (short)2021 },
                    { 461, "The Black Mamba", "Portugal", (short)0, "Love Is on My Side", "", (short)2021 },
                    { 462, "Anxhela Peristeri", "Albania", (short)0, "Karma", "", (short)2021 },
                    { 463, "Tornike Kipiani", "Georgia", (short)0, "You", "", (short)2021 },
                    { 464, "Hurricane", "Serbia", (short)0, "Loco Loco", "", (short)2021 },
                    { 465, "Dadi og Gagnamagnio", "Iceland", (short)0, "10 Years", "", (short)2021 },
                    { 466, "Natalia Gordienko", "Moldova", (short)0, "Sugar", "", (short)2021 },
                    { 467, "Rafal", "Poland", (short)0, "The Ride", "", (short)2021 },
                    { 468, "Vincent Bueno", "Austria", (short)0, "Amen", "", (short)2021 },
                    { 469, "Stefania", "Greece", (short)0, "Last Dance", "", (short)2021 },
                    { 470, "Benny Cristo", "Czech Republic", (short)0, "Omaga", "", (short)2021 },
                    { 471, "Uku Suviste", "Estonia", (short)0, "The Lucky One", "", (short)2021 },
                    { 472, "Senhit", "San Marino", (short)0, "Adrenalina", "", (short)2021 },
                    { 473, "Destiny", "Malta", (short)0, "Je me casse", "", (short)2021 },
                    { 474, "Go_A", "Ukraine", (short)0, "Shum", "", (short)2021 },
                    { 475, "Efendi", "Azerbaijan", (short)0, "Mata Hari", "", (short)2021 },
                    { 476, "Roxen", "Romania", (short)0, "Amnesia", "", (short)2021 },
                    { 477, "Eden Alene", "Israel", (short)0, "Set Me Free", "", (short)2021 },
                    { 478, "Hooverphonic", "Belgium", (short)0, "The Wrong Place", "", (short)2021 },
                    { 479, "Albina", "Croatia", (short)0, "Tick-Tock", "", (short)2021 },
                    { 480, "Tix", "Norway", (short)0, "Fallen Angel", "", (short)2021 },
                    { 481, "Elena Tsagrinou", "Cyprus", (short)0, "El Diablo", "", (short)2021 },
                    { 482, "Lesley Roy", "Ireland", (short)0, "Maps", "", (short)2021 },
                    { 483, "Vasil", "North Macedonia", (short)0, "Here I Stand", "", (short)2021 },
                    { 484, "Montaigne", "Australia", (short)0, "Technicolour", "", (short)2021 },
                    { 485, "Tusse", "Sweden", (short)0, "Voices", "", (short)2021 },
                    { 486, "Manizha", "Russia", (short)0, "Russian Woman", "", (short)2021 },
                    { 487, "Ana Soklic", "Slovenia", (short)0, "Amen", "", (short)2021 },
                    { 488, "The Roop", "Lithuania", (short)0, "Discoteque", "", (short)2021 },
                    { 489, "Alvan and Ahez", "France", (short)0, "Fulenn", "", (short)2022 },
                    { 490, "Sam Ryder", "United Kingdom", (short)0, "Space Man", "", (short)2022 },
                    { 491, "Malik Harris", "Germany", (short)0, "Rockstars", "", (short)2022 },
                    { 492, "Chanel", "Spain", (short)0, "SloMo", "", (short)2022 },
                    { 493, "Mahmood and Blanco", "Italy", (short)0, "Brividi", "", (short)2022 },
                    { 494, "We Are Domi", "Czech Republic", (short)0, "Lights Off", "", (short)2022 },
                    { 495, "Cornelia Jakobs", "Sweden", (short)0, "Hold Me Closer", "", (short)2022 },
                    { 496, "Jeremie Makiese", "Belgium", (short)0, "Miss You", "", (short)2022 },
                    { 497, "Vladana", "Montenegro", (short)0, "Breathe", "", (short)2022 },
                    { 498, "Ochman", "Poland", (short)0, "River", "", (short)2022 },
                    { 499, "WRS", "Romania", (short)0, "Llamame", "", (short)2022 },
                    { 500, "Stefan", "Estonia", (short)0, "Hope", "", (short)2022 },
                    { 501, "Andrea", "North Macedonia", (short)0, "Circles", "", (short)2022 },
                    { 502, "Brooke", "Ireland", (short)0, "That's Rich", "", (short)2022 },
                    { 503, "Andromache", "Cyprus", (short)5, "Ela", "YcGNhJhR4HY", (short)2022 },
                    { 504, "Sheldon Riley", "Australia", (short)0, "Not the Same", "QL3uK_sR-Xw", (short)2022 },
                    { 505, "Achille Lauro", "San Marino", (short)0, "Stripper", "PtKc-GaEiR8", (short)2022 },
                    { 506, "Emma Muscat", "Malta", (short)0, "I Am What I Am", "F_bT29reBkI", (short)2022 },
                    { 507, "Circus Mircus", "Georgia", (short)0, "Lock Me In", "O6UqeUwCldM", (short)2022 },
                    { 508, "Nadir Rustamli", "Azerbaijan", (short)0, "Fade to Black", "hkE2ISzZDnc", (short)2022 },
                    { 509, "Konstrakta", "Serbia", (short)0, "In corpore sano", "2ilIAT5WbtI", (short)2022 },
                    { 510, "Michael Ben David", "Israel", (short)0, "I.M", "D3LEEpIsxSs", (short)2022 },
                    { 511, "The Rasmus", "Finland", (short)0, "Jezebel", "FDpTiIectII", (short)2022 },
                    { 512, "Rosa Linn", "Armenia", (short)4, "Snap", "gVqGKkm7xBE", (short)2022 },
                    { 513, "Subwoolfer", "Norway", (short)0, "Give That Wolf a Banana", "sDvXhZtcp0w", (short)2022 },
                    { 514, "Amanda Georgiadi Tenfjord", "Greece", (short)0, "Die Together", "SDICrEVOh6o", (short)2022 },
                    { 515, "Systur", "Iceland", (short)0, "Meo aekkandi sol", "PAItdosVx8g", (short)2022 },
                    { 516, "Lumix feat. Pia Maria", "Austria", (short)0, "Halo", "lyRUUshYqDM", (short)2022 },
                    { 517, "Reddi", "Denmark", (short)0, "The Show", "kjZnFKceS3M", (short)2022 },
                    { 518, "Mia Dimsic", "Croatia", (short)0, "Guilty Pleasure", "VdOitl6KekY", (short)2022 },
                    { 519, "Maro", "Portugal", (short)0, "Saudade, saudade", "tIgwFHV78jg", (short)2022 },
                    { 520, "Zdob si Zdub and Advahov Brothers", "Moldova", (short)0, "Trenuletul", "3Mc_QsVPf7k", (short)2022 },
                    { 521, "S10", "Netherlands", (short)0, "De diepte", "I7NyzU1ob_M", (short)2022 },
                    { 522, "Intelligent Music Project", "Bulgaria", (short)0, "Intention", "UBIj9VGdT-A", (short)2022 },
                    { 523, "Kalush Orchestra", "Ukraine", (short)0, "Stefania", "Z8Z51no1TD0", (short)2022 },
                    { 524, "LPS", "Slovenia", (short)0, "Disko", "S9fhdc-e4_Y", (short)2022 },
                    { 525, "Marius Bear", "Switzerland", (short)0, "Boys Do Cry", "ubNIpxo-gMo", (short)2022 },
                    { 526, "Monika Liu", "Lithuania", (short)4, "Sentimentai", "acya6UcJP1k", (short)2022 },
                    { 527, "Citi Zeni", "Latvia", (short)0, "Eat Your Salad", "Ni5UEqfoOu0", (short)2022 },
                    { 528, "Ronela Hajati", "Albania", (short)10, "Sekret", "iMu47raqbcc", (short)2022 }
                });

            migrationBuilder.InsertData(
                table: "User",
                column: "unique_token",
                value: "a2a72798-690c-4301-9a01-1cf88e2080cc");

            migrationBuilder.InsertData(
                table: "Score",
                columns: new[] { "Userunique_token", "date", "attempts", "win" },
                values: new object[] { "a2a72798-690c-4301-9a01-1cf88e2080cc", new DateOnly(2023, 11, 7), 3, true });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Song");

            migrationBuilder.DeleteData(
                table: "Score",
                keyColumns: new[] { "Userunique_token", "date" },
                keyValues: new object[] { "a2a72798-690c-4301-9a01-1cf88e2080cc", new DateOnly(2023, 11, 7) });

            migrationBuilder.DeleteData(
                table: "User",
                keyColumn: "unique_token",
                keyValue: "a2a72798-690c-4301-9a01-1cf88e2080cc");

            migrationBuilder.InsertData(
                table: "User",
                column: "unique_token",
                value: "56489489185616");

            migrationBuilder.InsertData(
                table: "Score",
                columns: new[] { "Userunique_token", "date", "attempts", "win" },
                values: new object[] { "56489489185616", new DateOnly(2023, 10, 7), 3, true });
        }
    }
}
