// <auto-generated />
using System;
using Euroguessr.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Euroguessr.Data.Migrations
{
    [DbContext(typeof(EntityContext))]
    partial class EntityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Euroguessr.Data.DailyGuessDto", b =>
                {
                    b.Property<DateOnly>("date")
                        .HasColumnType("date");

                    b.Property<int>("song_id")
                        .HasColumnType("integer");

                    b.HasKey("date");

                    b.HasIndex("song_id");

                    b.ToTable("daily_guess");
                });

            modelBuilder.Entity("Euroguessr.Data.DailyGuessRangeDto", b =>
                {
                    b.Property<int>("min_song_id")
                        .HasColumnType("integer");

                    b.Property<int>("max_song_id")
                        .HasColumnType("integer");

                    b.HasKey("min_song_id", "max_song_id");

                    b.ToTable("daily_guess_range");
                });

            modelBuilder.Entity("Euroguessr.Data.DailyScoreDto", b =>
                {
                    b.Property<string>("account_id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<DateOnly>("date")
                        .HasColumnType("date");

                    b.Property<int>("attempts")
                        .HasColumnType("integer");

                    b.Property<bool>("win")
                        .HasColumnType("boolean");

                    b.HasKey("account_id", "date");

                    b.ToTable("daily_score");
                });

            modelBuilder.Entity("Euroguessr.Data.Tables.AccountDto", b =>
                {
                    b.Property<string>("id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.HasKey("id");

                    b.ToTable("account");
                });

            modelBuilder.Entity("Euroguessr.Data.Tables.SongDto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("artist_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("seek_to")
                        .HasColumnType("smallint");

                    b.Property<string>("song_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("video_id")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<short>("year")
                        .HasColumnType("smallint");

                    b.HasKey("id");

                    b.ToTable("song");
                });

            modelBuilder.Entity("Euroguessr.Data.TrainingScoreDto", b =>
                {
                    b.Property<string>("account_id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("attempts")
                        .HasColumnType("integer");

                    b.Property<int>("song_id")
                        .HasColumnType("integer");

                    b.Property<bool>("win")
                        .HasColumnType("boolean");

                    b.HasKey("account_id", "date");

                    b.HasIndex("song_id");

                    b.ToTable("training_score");
                });

            modelBuilder.Entity("Euroguessr.Data.DailyGuessDto", b =>
                {
                    b.HasOne("Euroguessr.Data.Tables.SongDto", "song")
                        .WithMany("daily_guesses")
                        .HasForeignKey("song_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("song");
                });

            modelBuilder.Entity("Euroguessr.Data.DailyScoreDto", b =>
                {
                    b.HasOne("Euroguessr.Data.Tables.AccountDto", "account")
                        .WithMany("daily_scores")
                        .HasForeignKey("account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("account");
                });

            modelBuilder.Entity("Euroguessr.Data.TrainingScoreDto", b =>
                {
                    b.HasOne("Euroguessr.Data.Tables.AccountDto", "account")
                        .WithMany("training_scores")
                        .HasForeignKey("account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Euroguessr.Data.Tables.SongDto", "song")
                        .WithMany("training_scores")
                        .HasForeignKey("song_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("account");

                    b.Navigation("song");
                });

            modelBuilder.Entity("Euroguessr.Data.Tables.AccountDto", b =>
                {
                    b.Navigation("daily_scores");

                    b.Navigation("training_scores");
                });

            modelBuilder.Entity("Euroguessr.Data.Tables.SongDto", b =>
                {
                    b.Navigation("daily_guesses");

                    b.Navigation("training_scores");
                });
#pragma warning restore 612, 618
        }
    }
}
